Options/WeakAurasOptions.lua, Prototypes.lua, WeakAuras.lua
Add an extra option on Load panel to type the Encounter ID.
Tracks ENCOUNTER_START/END to load and unload the aura, also has
protection agaisnt disconnect and combat leave by zone change.
=> Ticket #4 - Load Condition on ENCOUNTER_START

GenericTrigger.lua, Prototypes.lua, WeakAuras.lua
=> Smallpatches

Prototypes.lua, RegionTypes/aurabar.lua
=> Smallfixes

RegionTypes/dynamicgroup.lua
So that it is based on the center of the group rather than the
top/left for VERTICAL/HORIZONTAL dynamic groups
Ticket-number: 467
=> fix position of centered dynamic groups

RegionTypes/dynamicgroup.lua
=> Fix for dynamic groups not showing border/background

Options/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
correct the texture name for disabled from UI-GuildButton-OfficerNote-Down.blp to UI-GuildButton-OfficerNote-Disabled.blp
=> WeakAuras Ticket 482

Options/RegionOptions/progresstexture.lua, RegionTypes/progresstexture.lua
Also make the background use start and end angle
Make the options code use the exact same code as the texture
And lots of tweaks I forgot
=> Circular Progress: Fix various bugs

Options/RegionOptions/progresstexture.lua, RegionTypes/progresstexture.lua
- 0% Progress showing like 100% progress
- Background Offset not working correctly in the top left corner
- Inverse not allowing a non 90° end angle
=> Circular Progress: Fix a few reported issues

Prototypes.lua, RegionTypes/aurabar.lua, WeakAuras.lua
Load conditions for: mystic dungeons, vehicle and glyphs.
Fix for spark being always visible and fix for a error on login.
=> Various small fixes and features

Options/WeakAurasOptions.lua, Prototypes.lua, WeakAuras.lua
Fix full scan auras resetting their tracked buffs
Fix a error on loading
Add a tooltip to the glyph load condition
=> Fixes for Tickets

BuffTrigger.lua, GenericTrigger.lua, Prototypes.lua, WeakAuras.lua
- Fix Health of temporary pets
- Fix Agony multi aura trigger
- Fix Encounter ID for Archimonde last phase
- Fix Health being updated too seldom
- Add a Item Set Trigger
- Add a Ready Check Trigger
=> A round of fixes + new features

Options/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, Prototypes.lua
=> Fixes for BigWigs

Options/WeakAurasOptions.lua, Prototypes.lua, WeakAuras.lua
Fix the options dialog filter box to not use lua patterns
Add UNIT_DISPLAYPOWER to the trigger events for Power triggers
Clean up OnShow handlers
=> 3 small fixes

Options/RegionOptions/aurabar.lua, Options/RegionOptions/icon.lua, Options/WeakAurasOptions.lua
So make them return a string instead of a fileId
=> AceConfig image functions should return a string

Options/WeakAurasOptions.lua
=> Tweak spell scanning so that it finds more spells

Types.lua
=> Add Insantity to Power_Types.

Prototypes.lua, RegionTypes/progresstexture.lua, WeakAuras.lua
- Fix a bug in the progress texture reported by Shockah on #irc
- Fix a bug in the group aura trigger, which might be the source of a problem reported by elvador on #irc
- Fix that the source unit in the combat log trigger no longer works, reported on discord by Hamsda
=> Fixes for trigger state bugs

Options/WeakAurasOptions.lua, WeakAuras.lua
=> Be consistent what a nil sound_channel means

Options/RegionOptions/dynamicgroup.lua
=> Dynamicgroup: Fix error if child had no color.

GenericTrigger.lua
If we get a SPELL_COOLDOWN_EVENT and a ability is now on the gcd,
we need to treat that as if the ability is not on cooldown. So that
if it was on cooldown previously, a event is sent.
Ticker-Nr: 589
=> Fix Action Useable not update cooldowns correctly

Options/WeakAurasOptions.lua, Prototypes.lua
=> Add a valuesAll function that combines the values() functions

Options/RegionOptions/text.lua, RegionTypes/aurabar.lua, RegionTypes/text.lua, Types.lua, WeakAuras.lua
=> Implement Undelete

RegionTypes/text.lua
=> Fix text font flags

BuffTrigger.lua, GenericTrigger.lua, RegionTypes/dynamicgroup.lua, Templates/TriggerTemplatesData.lua, WeakAuras.lua
hideRegion releases the clone. It was only called if there was a
end animation.
Ticket-Nr: 674
=> Fix a few bugs

WeakAuras.lua
=> Fix ReleaseClone to actually store the clone into the right place

WeakAurasTemplates/TriggerTemplatesData.lua
Probably a whole lot missing....
=> Update Templates for 7.1.5

WeakAuras/Prototypes.lua
=> Fix Item Equiped Trigger for items with ' in their names

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Broke if no item was equipped in a slot
Ticket-Nr: 877
=> Fix Cooldown Progress (Equipment Slot)

WeakAurasTemplates/TriggerTemplatesData.lua
As the T19 bonus for adds a second Shield Block buff.
Ticket-Nr: 898
=> Change the template for "Shield Block" to use full scan

WeakAuras/Prototypes.lua
=> Fix Power Type trigger with "Only if primary"

WeakAuras/GenericTrigger.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/WeakAuras.lua
So people have an easier way to find the aura that is causing issues
=> Add comments to error messages

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/ConditionOptions.lua
Actually requires a new property type.
Ticket-Nr: 939
=> Add Orientation and Inverse property to Progress Texture/Aurabar

WeakAurasOptions/OptionsFrames/MoverSizer.lua, WeakAurasOptions/WeakAurasOptions.lua
Broke in Oct 2015 with commit 78820c4a2a15f1e639e031e6b22a806550c79207
Ticket-Nr: 938
=> Fix aura_env being nil in the options dialog

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
=> By default buttons should not accept keyboard input

WeakAuras/WeakAuras.lua
For example, a condition for "Trigger 1 active" with only one trigger
only triggered once, because actions are only done when the check
changes from inactive to active.
So far, on hiding we stopped checking conditions and thus that check
was always true, and thus could only once transition from inactive
to active.
This patch adds runs another condition check on hiding, which will
deactivate all conditons and their properties.
=> Conditions: Fix actions not triggering twice for some conditions

WeakAuras/Types.lua
So people stop asking about them!
=> Register sounds with LibSharedMedia

WeakAurasOptions/OptionsFrames/TextEditor.lua
=> OptionsFrames/TextEditor: Add Obsidian color scheme

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
Report and patch by Exality on discord.
=> Change one PlaySound to use kit ids

WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/WeakAurasOptions.lua
This is less code, adds a error reporting description and apparently
the Text one didn't show a Expand button previously.
=> Convert a few more TextEditors to use AddCodeOption

WeakAuras/Types.lua
=> Fix Lua errors on Login with certain locales

WeakAuras/Prototypes.lua
=> Implement UnitIsUnit option for Unit Characteristics trigger.

WeakAurasTemplates/TriggerTemplatesData.lua
=> Add Allied Races to templates

WeakAurasTemplates/TriggerTemplatesData.lua
Accidentally added it to all Healer specs, because a comment was wrong.
Also fix some minor issues.
Ticket-Nr: 1082
=> Templates: Add KJ's burning wish to the correct specs

WeakAuras/Bindings.xml, WeakAuras/WeakAuras.lua
Small additions just to add an easy binding the the main game's KeyBindings settings. I would find this useful, personally, and it's unobtrusive enough that it shouldn't bother anyone that wouldn't find it useful.
=> Add bindings

WeakAuras/Types.lua
GetShapeshiftFormInfo() doesn't return name
=> fix form_types

WeakAuras/BuffTrigger.lua
UnitAura does not take a spell name anymore so we have to loop over
all auras.
=> Fix UnitAura (unit, spellName, ...)

WeakAuras/BuffTrigger.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
But only getting close.
Github-Issue: 399
=> Workaround SmoothStatusBarMixin not setting the targetValue

WeakAuras/GenericTrigger.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/WeakAuras.lua
=> Handle errors again

WeakAuras/WeakAuras.lua
Doing a find/replace all wasn't that good of a idea
=> Fix error handling.

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
=> Ignore Load tab when copying display

WeakAuras/Prototypes.lua
check C_SpecializationInfo.GetPvpTalentSlotInfo doesn't return nil
=> fix CheckPvpTalentByIndex nil index error

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
The whole frame:SetScript("onHide", ...) block was run when WeakAuras.CreateFrame() is called
An other solution if the frame:Hide() is needed, i don't see why it's there, is to move the block after the frame:Hide() call
=> OnHide code was run on frame creation, fix #474

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
Implements [wowace issue 644](https://www.wowace.com/projects/weakauras-2/issues/644).
=> add a static popup to confirm deletion of auras

WeakAuras/Prototypes.lua
=> trigger.itemSlot can be nil

WeakAuras/WeakAuras.lua
Cleanup of old code, simplify a few functions. There should be no actual changes in behavior.
=> small changes

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
To be more like 2.6.0, minus minor bug fixes.
=> Tweak Loaded vs Unloaded Display for the Options window

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
=> Use id instead of index in hybrid sorting

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
follow up #490
I made the mistake to not use topic branch before i did #490 (as recommended in CONTRIBUTING.md) so it created a new PR.
=> fix hiding adjusted timers on obselete timers

WeakAuras/Prototypes.lua
And not just the condition check
Github-Issue: 540
=> Item Cooldown: Also fix onCooldown check in trigger

WeakAuras/BuffTrigger.lua
fix https://www.wowace.com/projects/weakauras-2/issues/1162
=> fix nil error with use tooltip size instead of stacks

WeakAuras/BuffTrigger.lua, WeakAurasOptions/BuffTrigger.lua
add remainingTime option to aura trigger with fullscan
=> aura trigger with fullscan support remainingTime

WeakAuras/WeakAuras.lua
After removing code that lead too to many timers, more bugs were
exposed.
Ticket-Nr: 1174
=> Fix Conditions remaining time check

WeakAuras/Prototypes.lua
=> fix rangecheck condition threat nil as false #598

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
=> Add a "WarMode Active" load condition

WeakAuras/Transmission.lua
Specifically:
1. default to Importing as a copy. 'Choose a mode' localization phrase removed
2. Prepare code review during update process. Also as a TODO, we would ideally indicate somehow if a code hasn't been changed in the code review
3. Shift some of the buttons around a few pixels for better alignment. The button labels too.
=> UI tweaks for update tooltip

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Transmission.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/BuffTrigger.lua, WeakAurasOptions/GenericTrigger.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasTemplates/TriggerTemplates.lua
This behaves just like the timed duration, except that the duration
comes from a duration function.
Github-Issue: 413
=> Add a dynamic hide duration for event triggers

WeakAuras/WeakAuras.lua
Forgot remove a "or true" used for debugging.
Github-Issue: 621
=> Fix schedule ConditionsTimers

WeakAuras/GenericTrigger.lua
=> fix autoHide for custom event w/ custom duration

WeakAurasOptions/RegionOptions/DynamicGroup.lua
=> Hide child thumbnail regions when they're no longer useful

WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua, WeakAurasTemplates/TriggerTemplates.lua
- refactor "changes"
- small fixes for texture color, and "inverse" usage
- removed some progress bar templates, kept only horizontal & vertical, with green color default   << this will need approval
=> Templates smallfixes

WeakAurasTemplates/TriggerTemplates.lua
use a more generic term for glow => highlight
=> Templates smallfix

WeakAurasOptions/ConditionOptions.lua
=> Fix regression in Copy Conditions to All

WeakAuras/Prototypes.lua
=> Fix PvP Load condition for Characters without a PvP talent selected

WeakAuras/BuffTrigger.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Transmission.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/GenericTrigger.lua, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasTemplates/TriggerTemplates.lua
This pull request introduces an internalVersion change, and moves all trigger data into a single table, for ease of manipulation. There should be no change in behavior that is apparent to the end user.
=> cleanup trigger data

WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua
> fix totem glow
> typo in a description
> new "overlayGlow" subType for spells with procs
> added and fixed a few spells
=> Templates fixes

WeakAurasOptions/WeakAurasOptions.lua
=> Use both columns for multiselect's multiselect widget

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasTemplates/TriggerTemplates.lua
Allow multi-selection with CTRL and create a batch of auras at once
A "Batch" button appear when you select labels with CTRL.
"subType" selection screen
Click "Create Auras" will make all of them at once
=> Templates Batch creation + make new auras in a group

generate_changelog.sh
This adds a highlights section to the changelog, drawn from the annotated tag message so we can point out new stuff better
=> add a highlights section to the changelog

.luacheckrc, WeakAuras/Init.lua, WeakAuras/Profiling.lua
Adds a popup frame that we print the profiling data into instead of spamming the chat.
Currently looks like this
the frame is draggable via right clicks.
Pending an answer from @kesava-wow if I can use his popup code since KuiNameplates is All Rights Reserved. Edit: Got the ok!
Fixes #702
=> Add a popup frame for profiling prints

WeakAuras/AuraEnvironment.lua
=> Fix WA_IterateGroupMembers to iterate over all  party members.

WeakAuras/Prototypes.lua
Use "[=[" instead of "[[" as string interpolation.
linked too #753 #754
=> fix DBM trigger

WeakAuras/WeakAuras.lua, WeakAurasTemplates/TriggerTemplatesData.lua
=> templates: fix 2 wrong spellids

WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua
Power
- new type "power"
- inverse = false
- left text and icon removed
- show cost of casts
Health
- new type "health"
- inverse = false
- left text and icon removed
- show incoming heal and absorb
Cast
- new type "cast"
- inverse = false
- condition: uninterruptible = red
Shaman
- removed totem empty category
- added missing mana templates for the 3 specs
=> Improved Health, Power and Cast Templates

WeakAuras/WeakAuras.lua
Added the condition Attackable Target as requested in #781.
=> Added Condition:Attackable Target

WeakAurasTemplates/TriggerTemplatesData.lua
i used to copypaste that trait and forgot to remove it for beast masters
=> removes placeholder trait

WeakAuras/WeakAuras.lua
=> Fix Conditions

WeakAurasOptions/Locales/enUS.lua
Since UNIT_POWER is now UNIT_POWER_UPDATE
=> change tooltip phrase

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua
It works only if the first aura selected and the second are both in the same group or are top level.
implement #810
=> multi-selection of auras with shift modifier

WeakAuras/GenericTrigger.lua
=> Guard against mistakes in the custom variables input

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
thanks to foxlit's Globe for finding these
=> remove 2 redundant table keys

WeakAuras/Prototypes.lua
=> Fix Talent Selected trigger

WeakAuras/WeakAuras.lua, WeakAurasOptions/ConditionOptions.lua
=> Fix error on showing tooltip for a message filed on a group

WeakAuras/Types.lua
=> set event triggers default value, duration="1" and unevent="timed"

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
=> shift-selection: fix duplicates in tempGroup

.pkgmeta, WeakAuras/Profiling.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAuras/embeds.xml
note that it add a new dependency for LibDBIcon-1.0, i have not edited packaging script
=> add minimap icon

WeakAuras/Transmission.lua
When sending addonmessage trough the "WHISPER" channel, first check if unit is on same realm
If not then check if on same group or raid and send the message trough the "PARTY" or "RAID" channel with a prefix "§§destinationName-destinationServer:message"
Then when receiving messages, when it is from channel "PARTY" or "RAID", check for the prefix, and check if your are the right recipient.
=> handle sharing of auras with people crossrealm in same group

WeakAurasOptions/ActionOptions.lua
Be extra careful and handle cases and check for non tables as that could
have happened with 2.9.0
Ticket-Nr: 1258
=> Fix glow color settings on Actions Tab

WeakAuras/Init.lua, WeakAuras/WeakAuras.lua
Decisions I made:
- lower the slash command message in case people want to do /wa hElP etc 
- Display Discord URL but not GitHub because Discord can pre-filter most problems
- Display the version mismatch warning 1s after load so all the other addons don't spam it away, maybe display on options open as well?
Closes #925
=> Add help text and game restart warning

README.md
Hello,
I am a 4th-year Computer Science student at Simon Fraser University taking a technical writing course. The final project of the course asks us to use our technical writing skills and help edit documents online.
I've been using WeakAuras since I started in WotLK and truly love this powerful tool that helps improve my gameplay. If you find my edits useful, please incorporate them to your master repo. I truly appreciate your help.
Thank you,
William.
=====================================
Pull request:
Edited README.md
Rewording of the intro paragraph:
* removed 'you' (for a more formal tone since the paragraph serves as the introduction to this addon)
* reword of 'a whole host of similar types of' -> 'other relevant' (wordy compound adj.)
* 'It' -> 'This addon' (unambiguous …
=> Edited README.md for concision and readability

WeakAuras/WeakAuras.lua
=> Fix resets of conditions properly

WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AuthorOptions.lua
which is essentially a shortcut for a description with no text.
But space is good for a UI, so it's a good idea to highlight that opportunity to users.
=> add space option type

WeakAuras/WeakAuras.lua, WeakAurasOptions/AuthorOptions.lua, WeakAurasOptions/WeakAurasOptions.lua
Give it a namespace so that multiple places can use it
=> Move Collpased Data out of AuthorOptions.lua

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
=> fix renaming causing Multipick tooltip to not show

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAurasOptions/ConditionOptions.lua
ready for review :)
solve #817 
also target check in trigger and condition
this can be use for all abilities with late targeting like zek'voz eye beam or zul's shadow barrage
TODO: 
- ~~auto-clone break conditions, ex: condition target=player work only once, then need to target someone else before it work again~~ #875 fixed it
- ~~target condition can't use "specific unit", workaround or remove it from the list ?~~ fixed
- double check that there are no useless events in the list
=> cast trigger: slight rework, add multi, auto-clone and target options

WeakAuras/BuffTrigger2.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua
And ensure that we use them even when restoring from settings
=> Increase min width/height

WeakAurasOptions/AuthorOptions.lua, WeakAurasOptions/ForAllIndentsAndPurposes.lua, WeakAurasOptions/WeakAurasOptions.lua
* Default to collpased
* Add alpha to Author Options color
=> Tweak AuthorOptions

CONTRIBUTING.md
=> fix warnings in CONTRIBUTING

.github/PULL_REQUEST_TEMPLATE.md
=> update PR template text

WeakAurasTemplates/TriggerTemplatesData.lua
only the changes mentioned here:
https://blue.mmo-champion.com/topic/1104471-tides-of-vengeance-update-notes/
**Does this address an existing feature request? If so, link it here:**
no
**Is there any additional work that needs to be done?**
no but I think infus used to delete whitespace that was magically caused by web-PR
=> Updated Azerite Traits for 8.1

WeakAuras/RegionTypes/AuraBar.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
=> Smallerpatches

WeakAuras/GenericTrigger.lua
Fixes another issue noted in:
Ticket-Nr: 1303
Fixes #(issue)
=> Tweak check for insignificant cooldown to <= 1 instead of <1

WeakAuras/Prototypes.lua, WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua
=> Fix cast trigger focus changed + add templates with duration on spell cast success

WeakAuras/RegionTypes/Icon.lua
=> Fix masque integration

WeakAurasTemplates/TriggerTemplatesData.lua
=> Templates: sham elem buffs update #1153

WeakAuras/Prototypes.lua
=> add current tier zoneId and zoneGroupId list in tooltips #1151

WeakAuras/GenericTrigger.lua
=> Fix Spell Charges being overwritten by GetSpellCount

WeakAurasTemplates/TriggerTemplatesData.lua
=> Templates: add overlayGlow for Lava Burst

WeakAuras/RegionTypes/Text.lua
=> Fix Texts width Fixed Width in Dynamic Groups

WeakAurasOptions/AuthorOptions.lua
This is a case of a bug that is fixed by removing code.
Unfortunately, this is not as rare as it should be.
Fixes #1178
Verified that the steps to reproduce now produce the expected behavior
=> Fix userValue generation

WeakAuras/GenericTrigger.lua
=> Fix performance problems due to cooldown tracking

WeakAurasOptions/AuthorOptions.lua
Otherwise unsetting the max/min will brick the aura :p
=> guard against nil

WeakAurasOptions/AuthorOptions.lua
=> set option max to the *max*, not the min

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
Show "Duplicate" option on groups
Fixes #1106
=> Allow duplicate on groups

.luacheckrc, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua, WeakAurasTemplates/TriggerTemplatesData.lua
Fixes #1244
Tests are for losers
=> sanitize more input #1244

WeakAurasOptions/OptionsFrames/MoverSizer.lua
Add button for moving auras and groups by 1pxl to help build pixel perfect ui
Fixes #948
Do you have suggestions for buttons texture, position, and mouseover + button press effect ?
=> add buttons for moving auras by 1 pixel

WeakAurasOptions/OptionsFrames/MoverSizer.lua
=> change position of movers when they get out of screen

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/Types.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/WeakAurasOptions.lua
Implements WoWAce ticket [705](https://www.wowace.com/projects/weakauras-2/issues/705)
Ensured that all new options behave as expected.
=> Add Dynamic Group grid layout

WeakAuras/BuffTrigger2.lua
=> add new feature indicator

WeakAuras/BuffTrigger2.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/WeakAuras.lua
=> Wrap Anchoring in pcall and show a somewhat descriptive error message

WeakAuras/WeakAuras.lua
=> Fix stupid errors

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/MoverSizer.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua
Add alignment snapping for auras and groups
Pressing shift ignore the snapping
https://i.imgur.com/Yl0rKDs.gif
=> Add alignment snapping for auras and groups

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
=> Clear region scripts and disable mouse on hiding options 

WeakAuras/BuffTrigger2.lua, WeakAuras/Transmission.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/OptionsFrames/ImportExport.lua, WeakAurasOptions/WeakAurasOptions.lua
Allow to choose multiple debuff class instead of just one
**It add a data migration that is backward incompatible with previous versions of weakauras**
=> BuffTrigger2: multiselect for buffclass

WeakAuras/BuffTrigger2.lua
=> BuffTrigger2: Add code to recheck auras on PLAYER_ENTERING_WORLD

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/MoverSizer.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua
=> fix auras with strata=TOOLTIP highjacking cursor's clicks

WeakAurasOptions/AuthorOptions.lua
Fixes #1279
can no longer reproduce
=> regenerate option name and key if necessary

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua
=> check icon visibility for tooltip (fix #1283)

WeakAuras/RegionTypes/AuraBar.lua
=> Fix tooltip frame not having a parent for AuraBar

WeakAuras/WeakAuras.lua
This way, people can see errors which appear during the login process and report them to us.
Enhancement, i guess
I checked to see that it works
=> collect errors from login thread

WeakAuras/Prototypes.lua
=> Crucible of Storms encounter ids

WeakAuras/AuraEnvironment.lua, WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/OptionsFrames/TextEditor.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/WeakAurasOptions.lua
This is the real pull request! See #1243 for previous discussion. I decided to go ahead and not mock out regionData for now. If it becomes a problem, then we can guard against it. Otherwise, people should just be expected to write halfway decent code.
Basic functionality test.
=> Custom Grow & Sort

WeakAuras/WeakAuras.lua, WeakAurasOptions/AuthorOptions.lua
A few refactors. WeakAuras.Add should do a bit less unnecessary work, as well as Custom Options when a group is selected.
Smoke test
=> Refactorings

WeakAurasOptions/ConditionOptions.lua
This solves https://github.com/WeakAuras/WeakAuras2/projects/8#card-18039065.
I checked to see if it worked and it did.
=> collapsible headers for conditions

WeakAurasOptions/ConditionOptions.lua
=> don't collapse conditions by default for now

WeakAuras/Prototypes.lua
=> Fix nil error if spell name is empty

WeakAuras/RegionTypes/DynamicGroup.lua
=> Fix Custom Sort For Dynamic Groups

WeakAuras/WeakAuras.lua
This change will enable a feature that was broken
=> fix WeakAuras.CountWagoUpdates

WeakAuras/RegionTypes/DynamicGroup.lua
=> don't bother positioning children if there are none active

WeakAuras/BuffTrigger2.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/Cache.lua
This probably affects more places, but I'm too lazy to test them all...
Fixes: #1378
=> Fix inserting > 32bit values into the name field

WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/Icon.lua
fixes https://www.wowace.com/projects/weakauras-2/issues/1345 and https://www.wowace.com/projects/weakauras-2/issues/1344
=> Fix GTFO trigger and reduce default glow pixel thickness

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Fixes #1401
I have not added all the arguments to the Combat Log trigger but it should be good enough for most usage (as a lot of arguments are already ignored for some other subevents)
=> add _ABSORBED subevent suffix

WeakAuras/Profiling.lua
=> add a close button to the profiling popup

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/RegionTypes/RegionPrototype.lua
Fixes #1424
WoWAce Issue: 1351
=> Fix various errors related to anchor restricted frames

WeakAuras/Types.lua
=> use file id for lich king apocalypse

WeakAuras/WeakAuras.lua
This is designed to make custom options slightly more robust against corrupted data, by deleting corrupt options. Not the most ideal fix, but if the data is actually missing, then there is no way to know what should have been there.
Fixes #1434 
can no longer reproduce issue with these changes
=> delete corrupted custom options

.pkgmeta-classic, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.toc, WeakAuras/embeds.xml, WeakAurasOptions/WeakAurasOptions.toc
Fix libclassiccast & libclassicdurations not loading
Fix .toc files trying to load Model & ModelPicker files
Following error needs to be fixed upstream (or fork?)
```
2x ...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100192.lua:1049: Attempt to register unknown event "PLAYER_TALENT_UPDATE"
[C]: in function `RegisterEvent'
...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100192.lua:1049: in function `activate'
...akAuras\Libs\LibRangeCheck-2.0\LibRangeCheck-2.0-100192.lua:1093: in main chunk
Locals:
(*temporary) = <unnamed> {
0 = <userdata>
}
(*temporary) = "PLAYER_TALENT_UPDATE"
```
=> fix embeds.xml & WeakAuras.toc packaging conditions for classic

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
Fix error on minimize button press
=> classic: ignore modelPicker from minimize button

WeakAuras/Prototypes.lua
=> fix stance trigger on retail

WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/Icon.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTwoColumnDropDown.lua, WeakAurasOptions/RegionOptions/Icon.lua
Allow set a default value for the 2 columns widget by setting "true" as 3rd element of "display" table
Fixes #1517
=> Default values for 2 columns widget

WeakAuras/BuffTrigger2.lua
Follow change in syntax from https://github.com/rgd87/LibClassicDurations
=> classic: improve support for libClassicDurations

.pkgmeta-classic, WeakAuras/Prototypes.lua, WeakAuras/embeds.xml
remove support for LibClassicCast
> CLEU don't give spellid anymore, so can't give accurate cast duration
> And maintainer of LibClassicCast is not doing any update for a while
=> Cast trigger: only unit=player for classic for now

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
- war stomp reset melee swing timer
- CLEU trigger: disable spellId field for classic #1540
=> Classic fixes

WeakAuras/Prototypes.lua
=> Add UNIT_FLAGS to vehicle events

WeakAurasTemplates/TriggerTemplatesData.lua
add and remove some rogue buff/debuff/ability on Templates for Classic
=> Classic Rogue Templates

WeakAuras/Prototypes.lua
Thx blizzard for letting me in beta <3
=> classic combo points: fix division per 0 for class with no combo points

.pkgmeta-classic, WeakAuras/Prototypes.lua, WeakAuras/embeds.xml
cast trigger: re-add support for all units using LibClassicCasterino by d87
https://github.com/rgd87/LibClassicCasterino
=> classic: use LibClassicCasterino for cast trigger

WeakAuras/BuffTrigger2.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/Types.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
All of these are at least 4 months old, and were released in mid April 2019.
=> remove stale feature indicators

.pkgmeta-classic, WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua, WeakAurasTemplates/WeakAurasTemplates.toc
Disable Templates for classic, and don't show error message on retail for classic only spells
=> Templates: disable for classic

WeakAuras/SubRegionTypes/Border.lua, WeakAuras/WeakAuras.lua
=> Border subregion: set default anchor to "bar" for aurabar

WeakAuras/WeakAuras.lua
fix was working but it seems it wasn't applied because internal version of auras was already bumped
I test this with SV given in https://github.com/WeakAuras/WeakAuras2/issues/1608 could replicate issue, and after /reload with this fix it's all good
=> bump internalVersion for stance/form migration fix

WeakAuras/BuffTrigger.lua
As these can also happen in some certain circumstances.
Fixes: #1607
Fixes: #1614
=> BuffTrigger: Don't use the spellcache for creating fallback states

.luacheckrc
=> .luacheckrc wrong local var

WeakAuras/Prototypes.lua
=> Fix regression Talent Selected Trigger

WeakAuras/BuffTrigger.lua, WeakAuras/Prototypes.lua
test for classic before register player_focus_changed in bufftrigger legacy
=> classic: fix register unknown event in bufftrigger1

WeakAuras/AuraEnvironment.lua
=> fix WA_GetUnitAura for classic

WeakAuras/RegionTypes/RegionPrototype.lua
=> now that sticky.duration is gone, we can optimize this code path a bit

WeakAuras/BuffTrigger2.lua, WeakAuras/SubRegionTypes/BarModel.lua, WeakAuras/WeakAuras.toc, WeakAurasOptions/OptionsFrames/ModelPicker.lua, WeakAurasOptions/SubRegionOptions/BarModel.lua, WeakAurasOptions/WeakAurasOptions.toc, WeakAurasTemplates/TriggerTemplatesData.lua
At least I hope so.
Fixes: #1486
=> BuffTriger2: Fix nameplate group unit

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Use events from LibClassicCasterino's readme (was still using those from old lib)
=> fix cast trigger events for classic

WeakAuras/Prototypes.lua
=> fix error when importing power trigger for stagger on classic

WeakAurasOptions/AuthorOptions.lua
=> use min/max/etc for range slider

WeakAuras/WeakAuras.lua
=> fix "set parent to anchor" option for custom anchors

WeakAurasOptions/SubRegionOptions/SubText.lua
Collected feedback from friends and community, this is most named problem people have with the new UI and I agree. We can revisit as soon as `Defaults` lands.
=> Move Font and Font Size out of Pencil menu

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
Fixes #1677
I couldn't reproduce the issue but it should fix it
=> fix nil error when clicking minimize button #1677

WeakAuras/GenericTrigger.lua
=> Fix lua error on wrong input into variables

WeakAuras/SubRegionTypes/SubText.lua
=> fix potential error with text subregion with nil text_justify

WeakAuras/WeakAuras.lua
=> Fix error in UnloadAll

WeakAuras/GenericTrigger.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
- Re-add old behavior for ranged swing timer on retail
- Fix nil error in UnloadAll #1723 
Tested with a lvl 1 hunter on retail
=> Fix ranged swing timer on retail + UnloadAll bugfix

WeakAuras/Prototypes.lua
=> fix nil error in Action Usable spellInRange condition round 2

WeakAuras/GenericTrigger.lua
Fixes #1745
It has not been tested
=> Check if cooldown is ready after SPELLS_CHANGED fix #1745

README.md
=> fix github actions link

WeakAuras/Prototypes.lua
fixes #1752
have to use ScanUnitEvents to check events registered with AddUnitEventForEvents
=> use ScanUnitEvents callback for libclassiccasterino

WeakAuras/Prototypes.lua
fixes #1762
refresh on UNIT_INVENTORY_CHANGED
add a stacksFunc
=> update "Cooldown Progress (Equipment Slot)" for handling amno

WeakAuras/GenericTrigger.lua
reported on discord
https://i.imgur.com/1F6MNaC.png
=> swing timer: fix nil error if no offhand equiped

WeakAuras/WeakAuras.lua
=> adjust repair tool buttons

WeakAuras/Prototypes.lua
fixes #1805 the variable "form" was not set if trigger.use_form == nil
=> fix stance trigger when form checkbox is not selected

WeakAuras/BuffTrigger2.lua, WeakAuras/Prototypes.lua
=> Use proper callbacks for classic libraries

WeakAuras/Prototypes.lua
=> fix nil error in "Charges Changed (Spell)" trigger

WeakAuras/Prototypes.lua, WeakAuras/SubRegionTypes/Glow.lua, WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua, WeakAurasTemplates/WeakAurasTemplates.toc
Done
- Priest
- Mage
- Hunter
- Warlock
- Rogue
- Shaman
- Warrior
- Paladin
- Druid
Fixes #1562
=> Classic Templates

.pkgmeta-classic, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/embeds.xml
Re-implements Range Check library to Classic, as the library has since been updated for Classic compatibility.
=> Re-add Range Check to Classic.

.pkgmeta-classic, WeakAuras/Prototypes.lua, WeakAuras/embeds.xml, WeakAurasTemplates/TriggerTemplatesData.lua
GetTotemInfo() was removed in 1.13.3
Re-add Totem trigger using https://github.com/SwimmingTiger/LibTotemInfo
=> Classic totem

WeakAuras/Prototypes.lua
=> add Ny'alotha, the Waking City encounter ids

.luacheckrc, WeakAuras/Transmission.lua, WeakAuras/Types.lua
Closes #1149
i tested and it worked
=> remember update preferences for each aura

WeakAuras/ArchiveTypes/Repository.lua
we need data to be non nil and id to be a string in order to archive the data
Also, go ahead and use mixin in a few places for slightly shorter code
=> rewrite Set to not be broken

CONTRIBUTING.md
=> remove babelfish requirement

WeakAuras/GenericTrigger.lua
=> lower frequency of ITEM_COUNT_UPDATE for Item Count trigger fixes #1933

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
=> fix group type change

WeakAuras/Transmission.lua
Put serialized tables and their compressed strings in a dictionary for a few minutes. This way we only lag once when the entire raid starts clicking on our chat-linked aura.
Bonus: This also helps to prevent a possible DoS when someone is spam-requesting a single aura hundreds of times.
Tested with version 2.16.2, requesting/sending multiple large auras multiple times.
=> Cache deflated strings

.pkgmeta-classic
=> classic: WeakAurasTemplates was not moved to correct folder

WeakAuras/Types.lua
Fixes #1981
Instead of checking a set list of affixes id it check everything from 1 to 255
=> add lastest mythic_plus_affixes (should be almost future proof)

WeakAuras/Bindings.xml, WeakAuras/Init.lua, WeakAuras/Profiling.lua, WeakAuras/WeakAuras.lua
Show real time visual graph of profiling
Replace Profiling buttons & bindings
- resizable
=> Show realtime visual graph of profiling

WeakAuras/GenericTrigger.lua
=> stop swing timer when a cast is started fixes #2005

WeakAuras/Transmission.lua
=> clear authormode on any child imports too

WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/WeakAurasOptions.lua
Add a nameplate & unitframe anchor option for auras that are not already in a dynamic group
=> Anchor changes

WeakAuras/RegionTypes/RegionPrototype.lua
Fixes https://pastebin.com/CCtdLTta
=> fix auras anchored to an other aura

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
=> unit status trigger fixes

WeakAuras/Prototypes.lua
=> Health & Power triggers: fix division per 0

WeakAuras/Prototypes.lua
compare the name from CLEU event with given spell id
=> Classic: Combat Log trigger: re-add spellId

WeakAuras/WeakAuras.toc
=> bump toc version for classic to 11304

.pkgmeta-classic, WeakAuras/Prototypes.lua, WeakAuras/embeds.xml
=> remove LibTotemInfo (totem api restored with 1.13.4)

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
=> Combat Log trigger: fix srcUnit and dstUnit conditions

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
=> Re-Add Encounter Id(s) load condition and full list in tooltip

WeakAuras/AuraEnvironment.lua, WeakAuras/BuffTrigger2.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua
Action show/hide:
- Add Unit Frame option
- Add Nameplate option
- Add more custom glow options
- Remove all glows on hide
- Conditions
TODO:
- ~~run on hide when opening options~~
Fixes #1973
=> Supercharge glow actions / conditions

WeakAuras/WeakAuras.lua
Fix old action start/finish glows
=> data migration to set actions's glows to "FRAMESELECTOR"

WeakAuras/WeakAuras.lua
=> fix migration

WeakAuras/ArchiveTypes/Repository.lua, WeakAuras/History.lua, WeakAuras/WeakAuras.lua
to fix a dumb bug with restoring from migration snapshots
=> Add GetData method

WeakAuras/Transmission.lua, WeakAurasOptions/WeakAurasOptions.lua
This PR allows WA Update from a chat link. All functionality was already in WA just not used.
=> Allow WA Updates from chat links.

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasArchive/WeakAurasArchive.toc, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/WeakAurasOptions.toc, WeakAurasTemplates/WeakAurasTemplates.toc
> improve flow of glow external element conditions & actions
show options as you select them
> remove previous glow before applying a new one 
fix an issue when with conditions you change glow type it wouldn't remove previous glow and overwrite the unglow function
=> Glow external element fixes

WeakAuras/Prototypes.lua
=> Fix Health/Power triggers having not duration for animations

WeakAuras/WeakAuras.lua
fixes #2120 
This add a migration.
=> Add missing migration for action's glow_type

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
=> Add a "On Taxi" load option for classic

WeakAuras/BuffTrigger2.lua
=> BT2 Fix Multi by adjusting it to recent changes

WeakAuras/WeakAuras.lua
refactor anchor & glow to unitframe monitoring
always use WeakAuras.HiddenFrames if no unit frame found
fixes #2164
=> refactor anchor & glow to unitframe monitoring

WeakAurasTemplates/TriggerTemplates.lua
Also add condition isNotUsableBlue for basic Show on cooldown & Show on Ready
partially fixes #797
=> templates: add Show on Ready

WeakAuras/Profiling.lua, WeakAuras/WeakAuras.lua
In the words of the infamous philosopher Shaggy, it wasn't me.
Fixes #2188
=> Fix profiling bug

WeakAuras/Types.lua
=> fix nil error

WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua
=> remove ability to send messages to channels (which is protected) fixes #2200

WeakAuras/RegionTypes/RegionPrototype.lua
=> Revert even more spell checker changes

WeakAuras/Types.lua
=> Add missing CLEU subevent prefix, fixes #2224

.luacheckrc, WeakAuras/AuraEnvironment.lua, WeakAuras/BuffTrigger2.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/SubRegionTypes/SubText.lua, WeakAuras/Transmission.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/BuffTrigger.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/Cache.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/OptionsFrames/IconPicker.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/OptionsFrames/TextEditor.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/SubRegionOptions/SubText.lua, WeakAurasOptions/WeakAurasOptions.lua
TODO:
* multi selection
* with different actions extra options don't appear at all
* with different options, conditions are not highlighted as different
=> Add text formatting

WeakAuras/SubRegionTypes/Tick.lua, WeakAurasOptions/SubRegionOptions/Tick.lua
=> Fix recent changes to ticks.

WeakAuras/BuffTrigger2.lua, WeakAurasOptions/BuffTrigger2.lua
=> BuffTrigger2: Fix "Combine matches per Unit" regression

WeakAuras/Prototypes.lua
Use threat value and calculated total threat as value & total
Store Aggro & Status for use in conditions fixes #2261
Set canHaveDuration fixes #2257
=> Threat trigger update

.github/workflows/build.yml
=> update build.yml for 1.13.5

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/RegionOptions/Group.lua
surely an expansion change should warrant that
=> drop "old" new feature indicators

WeakAuras/WeakAuras.toc, WeakAurasArchive/WeakAurasArchive.toc, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasOptions/WeakAurasOptions.toc, WeakAurasTemplates/WeakAurasTemplates.toc
=> Shadowlands stuff

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
=> missed one

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
#Description
Closes #2053
it work
=> add fullCircle option

WeakAurasTemplates/TriggerTemplatesData.lua
=> Shadowlands templates

WeakAurasOptions/OptionsFrames/MoverSizer.lua
=> fix MoverSizer alignYFrom

WeakAuras/RegionTypes/AuraBar.lua
=> Fix AdditionalProgress when not a table pt. 2

WeakAuras/RegionTypes/DynamicGroup.lua
=> defend against silly user errors more

WeakAuras/Prototypes.lua
we shouldn't have to do this...thanks blizz
fixes #2353
=> guard against div/0

WeakAuras/WeakAuras.lua
=> Fix clonePool

.luacheckrc, WeakAuras/Prototypes.lua
add "Faction Reputation" trigger
I only tested it on classic.
=> add "Faction Reputation" trigger

WeakAuras/RegionTypes/Model.lua
=> Fix unit model auras on classic

.luacheckrc, WeakAuras/AuraEnvironment.lua, WeakAuras/Types.lua
Adds support for [ClassColors](https://www.curseforge.com/wow/addons/classcolors)
Fixes #2450 
=> Add support for Custom Class Colors

WeakAuras/Types.lua
adds bleed icon
adds bleed icon to the existing encounter journal icon table
=> adds bleed icon

WeakAurasOptions/AuthorOptions.lua
=> adjust nameSource when (re)moving children around

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
Swing Timer: add remaining time option fixes #2505
Also tiny refactoring
=> Swing Timer: add remaining time option fixes #2505

WeakAuras/RegionTypes/Icon.lua
=> better fix for omnicc error

WeakAuras/Types.lua
CUSTOM_CLASS_COLORS table does not have the method WrapTextInColorCode
=> fix nil error when using "Class Colors" addon

WeakAuras/Prototypes.lua
=> remove debug print

.luacheckrc, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
Adds a new load condition for player covenants
Fixes #2610
=> Add Covenant Load Option

WeakAurasOptions/Legendaries.lua
=> fix error when mouseovering Bonus ID load option on classic

WeakAuras/Prototypes.lua
Oops. This mistake causes WA to stop functioning.
=> Nil-check Bonus Id trigger

WeakAuras/Modernize.lua
=> sanity check modernize for data.subRegions

WeakAuras/AuraEnvironment.lua
Description intentionally left blank.
Fixes #2853
=> Add additional forbidden tables.

.luacheckrc, WeakAuras/Prototypes.lua, WeakAuras/Types.lua
The current CC trigger is entirely binary. People often want to know if they're controlled by a specific CC type for which they have a counter. 
=> Expand [status - crowd controlled] trigger

WeakAuras/GenericTrigger.lua
=> fix regression in TestForLongString

README.md
=> Fix broken links to extensions in README

.github/scripts/.gitignore, .github/scripts/csv_to_lua.lua, .github/scripts/wowtools.sh, .github/workflows/modelpaths-update.yml, .gitignore
To get source csv files from https://wow.tools/files/ click on "Listfile" >Community CSV Retail and/or ClassicRetail
Fixes #2829
=> update WeakAurasModelPaths from wow.tools csv export

WeakAurasOptions/OptionsFrames/ModelPicker.lua
Add a searchbox to model picker
=> add a searchbox to model picker

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Fixes #2920 
```
!WA:2!nEvZYTrUr4vwh8wS2Allw16AtTE9YiVwrEllAlYuoz3QsvruIsMoIumdjTSDumjMbyMb2ZaGaGrw0E1fw5GYFx0PCwNZj9i4NauQYtGEe8HCo9m8xrnMw8cX0OrJUB8HVUXCBMnmlol(OwI7JPkraQBtYb62UCzis3Uq(qQs1SRG0gzBlj7trAs7q0bli2kf1PU5wnpkKhX050(ewUfxEX85hkkF(fZHrHipY9Yry4blQeJZiYd2X1vr0ZjwkfZo0at4d(YUdwXPiMJpxwNtzA71lxRzzlXDtnuucsqadfsgiYmV4oZoMD4bCzNcrYaX34R1c1p9Gh8gKhppL)aXtc(dVyLw)w7huuIC0uot9ilLgj1)prUqIsbX5qtQ4rshsTlS13EkDgfKJ047M2kX()fmY7hQHg82JBuDnRMwRvzJZhk2jsP5Hx7emV9arDgTemrPLBG6QLuHCGqXVFlj4dyco3DF3yN(WFLk(7HB)H5w(UVBO7E4DF34e2H3ZsfVErXkmnr6ICi7TggVdtT3Ue0RxlsIu7vLGPO9AeRNAVg(CTxelp3Zt81tfVofhfO9GiiXY(IF5LYBxoVCztT645M(WzIZ7p …
```
=> Add 'Mine' affilation to combat log flag prototype

WeakAuras/GenericTrigger.lua
=> fix potential nil error in dbm & bw triggers

WeakAuras/Prototypes.lua
fix type error when they are use in conditions
fixes an error reported on discord https://pastebin.com/j8CHBhpi using this aura https://wago.io/8KnH9fmY3
=> ensure a few "percentX" property doesn't return a boolean

WeakAuras/WeakAuras.lua, WeakAurasOptions/AuthorOptions.lua, WeakAurasOptions/CommonOptions.lua, WeakAurasOptions/DisplayOptions.lua, WeakAurasOptions/OptionsFrames/IconPicker.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/SubRegionOptions/BarModel.lua, WeakAurasOptions/SubRegionOptions/Border.lua, WeakAurasOptions/SubRegionOptions/Glow.lua, WeakAurasOptions/SubRegionOptions/SubRegionCommon.lua, WeakAurasOptions/SubRegionOptions/SubText.lua, WeakAurasOptions/SubRegionOptions/Tick.lua, WeakAurasOptions/TriggerOptions.lua
Take some of Vardex commits, fix them and test them.
=> First small steps towards Nested

WeakAuras/WeakAuras.toc, WeakAurasArchive/WeakAurasArchive.toc, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasOptions/WeakAurasOptions.toc, WeakAurasTemplates/WeakAurasTemplates.toc
=> update classic toc to 11307

WeakAuras/AuraEnvironment.lua
Description intentionally left blank.
Fixes #3040
=> Add additional forbidden functions.

WeakAuras/AuraEnvironment.lua
Remove PickupContainerItem from the forbidden list
Fixes #3042
=> Remove PickupContainerItem from the forbidden list

.pkgmeta-bc, WeakAuras/GenericTrigger.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
Drop LibClassicSpellActionCount-1.0 on TBC
WeakAurasCompanion: fixes, nil checks, and support WeakAuras stuff moved to it's own table in next version
=> Tiny fixes

WeakAuras/Prototypes.lua
=> fix talents on TBC

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
Without any addon on classic this global is nil
=> fix MAX_NUM_TALENTS nil error on classic

WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesDataClassic.lua, WeakAurasTemplates/TriggerTemplatesDataTBC.lua, WeakAurasTemplates/WeakAurasTemplates.toc
Fixes #2995 & an error in toc file
=> Support "Action Queued" for classic/tbc Templates

WeakAuras/Types.lua
=> don't reset swing timer on Steady Shot

WeakAuras/Types.lua, WeakAurasOptions/WeakAurasOptions.lua
AddChild should only be done on init
shown buttons always need to be added to frame.buttonsScroll.children
=> fix scrolling with Ready for Install/Update

.github/scripts/csv_to_lua.lua, .github/scripts/wowtools.sh, WeakAuras/Prototypes.lua, WeakAurasModelPaths/WeakAurasModelPaths.toc
Fixes #3035
don't merge yet, classic_era build is not yet on wow.tools, fetching csv for this build make an error 500 right now
=> update wowtools script for classic_era and bcc

.pkgmeta, .pkgmeta-bcc, .pkgmeta-classic
=> Packaging fixes

WeakAuras/Prototypes.lua
=> Swing Timer trigger, fix remaining time check

WeakAuras/GenericTrigger.lua
=> swing timer: do not reset swing on SPELL_EXTRA_ATTACKS

WeakAuras/Prototypes.lua
=> add bcc encounter ids and show list in correct order

.luacheckrc, WeakAuras/Conditions.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua
New Text to Speech functions in the PTR, added to the WA interface. 
Started off thinking of them as sounds but really they're a chat output. 
Added a voice setting but thought it wasn't worth adding speed or volume (as that would add even more clutter to the HandleChatAction function)
It's a bit of a quick PR as I didn't have a massive amount of time and wanted to see about getting it in for 9.1 going live. 
=> Add TTS to chat types for Actions and Conditions

WeakAurasTemplates/TriggerTemplatesDataBCC.lua
=> update death wish & sweeping strike templates for bcc, fixes #3160

WeakAurasOptions/ConditionOptions.lua
Noticed a bad URL, that's all. 
=> Fix Custom chat message help link in Conditions

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Support new DBM_SetStage callback
`fireEvent("DBM_SetStage", self, self.id, self.vb.phase, encounterId)--Mod, modId, Stage, Encounter Id (if available).`
I didn't do any test, @MysticalOS can you check if it's working ?
=> Add DBM Stage trigger

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Swing Timer & Character stats triggers fixes
=> Swing Timer & Character stats triggers fixes

WeakAuras/Prototypes.lua
- Logged in and used weak aura used in original issue.
=> Fixing #3225

WeakAurasOptions/OptionsFrames/TextEditor.lua
=> Escape pipes when saving snippets

WeakAuras/GenericTrigger.lua
fix trigger not updating on swingEnd, and ranged attacks
=> Swing Timer fixes

WeakAuras/GenericTrigger.lua, WeakAuras/Types.lua
Fix 2 issues with swing timer, probably add more issues
=> Swingtimer

WeakAuras/BuffTrigger2.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/RegionOptions/AuraBar.lua
aura used for tests
```
!WA:2!fBvqVTrXx8ASuHU6FrTP0G6FvvmwQOMssutABOTqi4nXoofxBN1UjP0w5mENXEN21ZUAMztIdIdnId9CoYrFMtg4lqpYPrr8jOIBi4qoWrG3m7ItCtkIB8KIZmV3V9nV3BFVFZMQWiDgbpc(5tTtWgeUpQR4Q3T4C)2LmsX5(1hBKIZ9DNZiPbJ)43yea1FOL)S4C)83RLFiDpQBaRwqe3LCXtShks6fWRekPbmHfVBLwTeezQ(iMlOVAaLjBoF(Y1Z7SNieXFQtGePXMk8SdT)EbyIDU7xVIT29E7i502TjCr5pGNS83TLDdjnDJeYGo9WKMrTAvh0WlMVu1c3V0lfrnjBqyYAGb6w9BmFUA1BuREoN67hjineEbBwcjjm3URBhXOYMHqLGWDmpK98iHChnoTP1DyOoeH1oIqIV)syHL6T36n(LwrmxDWEf04ziJzLbeARmKmZoBMSvlL7b5DIpV8l04EvwzPYlMnJ0JWma1c6HzZ(4mZM5lhOrl6aduk5rKXhYGRhI1MGpwBsOU5dwM6AxBydBG8JGikthK0BsoIHd6CLPgxJBSHbIWyQozq(v5bT5eH4irMwoQgT0HY(3CgdGJ264HFe0F14)NhbhrJ1)qagMu70DIWbKvOBNDZAnS3i(cYr7uQuT6RRtXpWfE9QFJy6zgOhCIyyKMoOjhUv5vmM0G1cbrXateg26W)NtKrCw8Jd66hpN1qpZ1xNuKOqm8RJRhX9PQrJh1eHF4X23N5yZXbtOv5eyc1Pw18 …
```
=> Add texture support to aurabar overlays

WeakAuras/Prototypes.lua
=> Add deficit to health and power triggers

WeakAuras/Prototypes.lua
=> fix error when hovering ZoneID

WeakAuras/GenericTrigger.lua
Covers both the case in the ticket (end of string matches) and another rare case I discovered while investigating (beginning of string matches resulting in false negative).
Fixes #3344
I tested the string matches externally. I did not test in-game.
=> Fix Bonus ID partial matches.

.gitignore, WeakAuras/WeakAuras.lua, WeakAurasOptions/AuthorOptions.lua
dunno how this happens but we can't keep corrupt data like that, unique keys are an invariant on custom options
fixes #3368
=> yeet duplicate keys in custom options

WeakAuras/Prototypes.lua
=>  Reputation trigger: add "Use Watched Faction" option

WeakAuras/GenericTrigger.lua
An arms warrior's sword specialization talent will trigger the event
SPELL_EXTRA_ATTACKS with a SWING_DAMAGE/SWING_MISSED immediately
after. The swing timer should not be reset by the extra attack, but
the check requires the exact same timestamp for SPELL_EXTRA_ATTACKS
and the following SWING_DAMAGE/SWING_MISSED.
The events are timestamped separately, thus the timestamp does not
strictly have to be the same. Allow a small discrepancy between the
timestamps to not reset the swing timer on mid-swing sword
specialization procs unnecessarily.
Fixes #3308 #3289 #3141 
```
12/19 20:09:03.237  SPELL_CAST_SUCCESS,Player-4476-03920DBA,"Strfry-Gehennas",0x514,0x0,Creature-0-5571-548-16817-21246-00013F7D2A,"Serpentshrine Sporebat",0x10a48,0x4,25231,"Cleave",0x1,Player-4476-03920DBA,0000000000000000,1 …
```
=> Let timestamp differ slightly for extra attacks

WeakAuras/SubRegionTypes/Background.lua
=> subbackground should support everything but groups

WeakAuras/WeakAuras.toc, WeakAurasArchive/WeakAurasArchive.toc, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasTemplates/WeakAurasTemplates.toc
I'm not sure exactly when it was updated on servers, but last month.
=> update SOM toc version

WeakAuras/Types.lua
The boss unit option never worked on bcc as it's not supported by the game
=> remove boss unit for BBC

WeakAuras/Prototypes.lua
=> store %count text replacement in the tooltip

WeakAuras/Conditions.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/OptionsFrames/ImportExport.lua
=> don't show raidTarget symbol if index is X > 8, fixes #3473

WeakAuras/Init.lua
WOW_PROJECT_MAINLINE value changed from 5 to 1 in 9.2
=> fix unpackaged copy of weakauras not working on 9.2

WeakAurasOptions/OptionsFrames/IconPicker.lua, WeakAurasOptions/TriggerOptions.lua
=> fix iconPicker with spellCache change

WeakAuras/Types.lua
"prototype pantheon" & "generals boss in nathria" has more than 5 boss units
=> increase boss units up to boss10

WeakAuras/GenericTrigger.lua, WeakAuras/WeakAuras.lua
https://github.com/WeakAuras/WeakAuras2/commit/9927bf5b49d267a19fcb5938e8903c619d929be3 missed change to max number of boss in a few places
=> more fixes to support boss units up to 10

WeakAuras/BuffTrigger2.lua
stupid me didn't save file before last round of boss fixes commit
=> bufftrigger boss unit fix

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.toc, WeakAurasOptions/LoadOptions.lua
Similar to the previous tooltip addition to Bufftrigger2. "Smart Group" is the main thing that makes this useful I think. 
=> add a tooltip for unit selections in status triggers

WeakAuras/BuffTrigger2.lua, WeakAuras/Conditions.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/Types.lua, WeakAurasOptions/RegionOptions/Icon.lua
Use modRate modifier for spell cooldown
Fixes #3544
=> handle CDR with modRate

WeakAuras/BuffTrigger2.lua, WeakAurasOptions/BuffTrigger2.lua
Added headers to bufftrigger2's options and reordered some elements to better fit the discrete sections.     
Also changed the setting name "Debuff Type" to "Dispel Type" and added a couple of tooltips.
=> Add headers to bufftrigger2 to aid navigation of settings

WeakAurasOptions/RegionOptions/StopMotion.lua
Make texture picker handle stopmotion files with settings in name
Show animated preview instead of a tiled texture
=> make texture picker handle stopmotion files with settings in name

WeakAurasOptions/RegionOptions/StopMotion.lua
stopmotion picker too fast too furious
=> stopmotion picker: slow down animation frame rate

WeakAuras/Conditions.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAurasOptions/CommonOptions.lua, WeakAurasOptions/ConditionOptions.lua
Add a new global condition for testing range with group & enemies
=> new global range check condtion

WeakAurasOptions/WeakAurasOptions.lua
=> Fix shift-multiselection with aura installed from "Ready For Install"

WeakAuras/Prototypes.lua
=> extra Cooldown Progress: typo for showlossofcontrol

WeakAuras/Prototypes.lua
=> Threat Situation trigger: add unitexist check

WeakAuras/Types.lua, WeakAurasOptions/AuthorOptions.lua
i also added noMerge as a valid field in group types
=> fix array options again

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/RegionTypes/Icon.lua, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasOptions/AuthorOptions.lua, WeakAurasOptions/CommonOptions.lua, WeakAurasTemplates/TriggerTemplatesDataWrath.lua
Fixes #3716
TODO:
- review from peoples who knows more than me about wotlk
- deathknight was half copy pasta from retail to not start from scratch, but it's big WIP
=> wrath templates (WIP)

WeakAurasOptions/OptionsFrames/TextEditor.lua
=> Switch escape over to needing a modifier down to close without saving

WeakAurasOptions/OptionsFrames/TextEditor.lua
Previous fix was not properly tested. Very slap-dash of me :(
=> Really actually remove escape from the editor this time, honest

WeakAuras/Types.lua
The LoC Type "None" wasn't handled. 
Fixes #3782
I logged in and tested it
=> Add the LoC type NONE

WeakAuras/Transmission.lua, WeakAurasOptions/OptionsFrames/Update.lua, WeakAurasOptions/WeakAurasOptions.lua
https://github.com/WeakAuras/WeakAuras2/pull/3746
Fixes #(3745)
- [ x] Bug fix (non-breaking change which fixes an issue)
- [ x] This change requires a documentation update
=> Fix return on Async success of Weakauras.Import

WeakAuras/BuffTrigger2.lua
=> BT2: Fix UNIT_PET not considering all scanFuncs

WeakAurasOptions/OptionsFrames/Update.lua
Fixes Typo and ads ID to error msg
=> fixed typo and added ID to error msg on duplicate ID import

WeakAuras/Profiling.lua
Change in LibGetFrame: https://github.com/mrbuds/LibGetFrame/commit/6756d52c4f1910b1c6d7061c3fa675cd9ac7563e
=> Add LibGetFrame profiling data to profiling result

WeakAurasOptions/OptionsFrames/Update.lua
=> fixed typo added in https://github.com/WeakAuras/WeakAuras2/pull/3794

WeakAuras/WeakAuras.lua
Probably won't fix the actual issue, but will at least allow us to identify it by preventing the error from stopping execution.
It actually hasn't.
=> Fix variable name in AddMany.

WeakAuras/Modernize.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
Talent Known trigger: Fix on classic, use spellId instead of talent's index on Dragonflight
Fixes #3912
=> Talent Known trigger fixes

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasMiniTalent_Dragonflight.lua, WeakAurasOptions/LoadOptions.lua
Fixes #3952
The new Rank option works good when only one talent is selected
I tried hide option if not exactly one talent is selected but couldn't make "reloadOptions" work on talent selection
=> Talent Known: add rank check

WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/Types.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
aura used for my tests
```
!WA:2!fwvxVTrrx4AzkLSQusCtdTLcSkikPquvtEPLaIsjBIDtah701BAAbHsMD3XEhY6z2oZSXjbXf1QQQx7Fc(6ELF)bGuUGRhzH4hqUKlZVaoZSRt)qiyT06zoZ5mNVEopBH7xsm)Y4Dl1UuyPWNDDNwCwhN76U6Yh5Z4HyUdkyNqoljzCNyYbhG4H2EmwSKKW3REZMcSCLF7VE(P0p89ZfChBZ(tnardIy81zeQ0FPY18k72VzAC8seEqmE7UGRAKGcWf4OajHrf3YvirCPLFtcLiISCG)KwDLCsRwyU4YxLNV8P9dX(PnB6TFcMVs5QRxzJQosyJlkLJMVRibhhVAOW6irQpExmv2a0MS3GTwAXgEB1WBrxpNu4Y9tIr7J5UuuBSWY1OQ)kyuSm6etxNJbtDBSE5Qv7LsZdbRbbS4020Sm4yifXCkk((qCcPsNUPcCvsBImYfftArvJXHCtByH(Wf7IBPtylNygkSIVefdoAk32PqL1Ybc)GPuxZYnigje6vocYby9IH(5nKLyXm(3vSyX1lEJRFZUT4KqD1y6vUphrjTrsCKRiaU3I(zDYO(z)xoSfozIgpkfXX2vG2H9MrejUp3es674WW9H6bjaWcPj5w1a8)PDemU0HYO4EiEqvmTLm6jtb9rjs3)k4ZrHKuXtoBVSqaKDl1Bx5qmsGBi5g9pJAs1cddH2K(4T0nnUahWOHIUA90bGAbN2icTI62gTvFJ6oQVf()CVUKJa7GYkvwbqqmUV7IlV6gn8bP …
```
=> Dynamic Groups: add vertically & horizontally centered grows

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua
=> Texture picker: keep aspect ratio for atlas in preview

WeakAuras/SubRegionTypes/Glow.lua
Fixes #(issue)
- Quick test on retail showed no issues
=> Remove very old Masque workaround that should no longer be needed

WeakAurasOptions/Locales/enUS.lua
Small fix of example wording to make it easier to understand.
- I did not run any test of this as it is simply a text change.
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
=> chore(typo): Fix typo for example in enUS locale

WeakAuras/Prototypes.lua
=> add stagger stat

WeakAurasOptions/BuffTrigger2.lua
Fixed pronouns in buff trigger language
=> Fixed pronouns in buff trigger language

WeakAurasOptions/OptionsFrames/Update.lua
for slightly more accurate diffs when updating
=> fix ignored value checks

WeakAurasOptions/AuthorOptions.lua
love when a bug is easy to fix
=> decrement nameSource on deleting subOption that precedes the name source

WeakAuras/GenericTrigger.lua, WeakAuras/WeakAuras.lua
=> Fix WeakAuras.GetAuraInstanceTooltipInfo and getTenchName for 10.1

.luacheckrc, .luarc.json, WeakAuras/Dragonriding.lua
look ma, i found a new toy
https://wowpedia.fandom.com/wiki/API_C_PlayerInfo.GetGlidingInfo
=> simplify dragonriding detection

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
cherry-picked 2 commits from https://github.com/WeakAuras/WeakAuras2/pull/4495
=> Bigwigs trigger fixes

.luacheckrc, WeakAuras/Conditions.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasExpand.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasSpinBox.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/Texture.lua, WeakAurasOptions/TriggerOptions.lua, WeakAurasTemplates/TriggerTemplatesData.lua
=> More descriptive names for Triggers and Conditions in UI

WeakAuras/GenericTrigger.lua
Asked in https://github.com/WeakAuras/WeakAuras2/issues/4502
=> DBM Triggers: use count from callback instead of parsing text

WeakAuras/Types.lua
=> a pull request title

WeakAuras/Init.lua
Fixes [#(issue)](https://github.com/SavedInstances/SavedInstances/issues/778)
=> Hide addon compartment tooltip onLeave

README.md
=> Update PayPal link in README.md

WeakAuras/Types.lua
=> Colorize "Class and Specialization" options fixes #4657

WeakAuras/GenericTrigger.lua
fixes #4752
i did not test perf on this, FYI
=> batch B_U_D events

WeakAuras/Prototypes.lua
=> Use spellIds in classic

.luacheckrc, WeakAurasTemplates/TriggerTemplatesDataClassicEra.lua
Add Sod runes to templates
for now only mage runes are done
added a new "known = true" arg
=> Classic SoD runes template

WeakAuras/Prototypes.lua
=> Currency Trigger: use currency icon in options window

.github/workflows/build-beta.yml, .github/workflows/build.yml, .github/workflows/pull_request.yml, WeakAuras/Init.lua
...by having all of the code run, and then successively commenting out lines that are wrong for the build
honestly, this is how we should have done it anyways, but i didn't fully understand how the bw packager handles it at first
https://github.com/BigWigsMods/packager?tab=readme-ov-file#build-type-keywords
=> fix buildType detection

WeakAuras/Transmission.lua
Fixes #4898 (probably, my guinea pig went AFK before i could test this change).
=> only obliterate whispers when we actually find a weakauras link in them

WeakAuras/Modernize.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/Model.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/StopMotion.lua, WeakAuras/RegionTypes/Texture.lua, WeakAuras/SubRegionTypes/Model.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIContainer-WeakAurasTreeGroup.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasSpinBox.lua, WeakAurasOptions/OptionsFrames/ModelPicker.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/Model.lua, WeakAurasOptions/SubRegionOptions/Model.lua
=> Cata / Classic stuff

.github/ISSUE_TEMPLATE/bug_report.yml
Add a new field to issue templates.
=> update issue template

WeakAuras/WeakAuras.lua
otherwise, there's an edge case if Modernize is broken:
1. WeakAuras notices that WeakAurasSaved.dbVersion < internalVersion
2. AddMany is invoked with takeSnapshots == true, and thus calls SetMigrationSnapshot
3. Archivist successfully creates an archive, and because storeType == "ReadOnly", the aura data becomes an Archivist store object per spec
4. AddMany calls PreAdd, which notices data.internalVersion < internalVersion, & calls Modernize
5. Modernize, being broken, errors out & never updates data.internalVersion
6. AddMany calls Add, which notices data.internalVersion < internalVersion, & calls SetMigrationSnapshot a second time (preparing to Modernize)
7. Archivist notices that the object passed to it during CreateStore is already a store object, and barfs.
really, this error is …
=> improve AddMany data flow

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
On hold until waiting for confirmation this works at https://github.com/WeakAuras/WeakAuras2/issues/5106#issuecomment-2139631122
=> Remove legacy GetCurrencyInfo code for Cataclysm

WeakAuras/BuffTrigger2.lua, WeakAuras/Conditions.lua, WeakAuras/GenericTrigger.lua, WeakAuras/WeakAuras.lua
with 1600 auras (~8.9 MB SV file), this saves about 600MiB (40%) in memory allocation, and about 1 second (20%) in CPU time on login process
=> use table.concat to build various function strings

WeakAuras/GenericTrigger.lua, WeakAuras/Types.lua
https://warcraft.wiki.gg/wiki/API_BreakUpLargeNumbers
=> add BreakUpLargeNumbers format option

WeakAuras/Modernize.lua, WeakAuras/WeakAuras.lua
Add a migration 75 that will use (if available) data from the snapshot done for migration 74
To test this i did:
delete all weakauras data, archivist included
git checkout 1.13.2 => import
```
!WA:2!TB52ZTXvDC8SztXnIsirMeADdnUPnH2cjXwjPPbix8AlBRGJL6kz7KqaPJ29iTB8Q9S5SRKTmxJbkUq5Mc3HYfXDOq7ikukmCzYFb)gn8Eb)gVqHmmdVYVZzxzzhh3oPmmmmt0dsN9C2Z587YNFF)jLPJ7NyeAT4vIBg3CP9UCrg3KY1igZAYzEEBxZXEHfiCZ(ZXyob2E85txQKpny8)W)4jF2)5K)5tYRhnXF0AG)(EEP8)RwexdlgpdZ2nO4WjNmxs9wHN6Wmhg)mkkkQjQYD8UxRGap)3XHo0CKYSdAZoejzUYZvAe6OhAqoXiWM56)O6(beEqmnBx7GyflH)4BfBXaUD5YuUFF7Nhn8jAAslwTuPC19O8XtorMrNAcTa8bDsvojXI(EuhNuM(Xw2VArAnQBqw8TTNVv(HhkBU8zZnKEoDxsfQFmTQ4Dv0ZHuNY1LVAXXPeNaRv2Agof3QE2mjNyIgvDJmHyxh9yk3L4mnAAO1F1g(uNsYartT05YL(StKC0C8AHRQ2epoDAzHBgtZHrmNUyaXbp(DPxPkgRJP5BVaDxWBfh4rned0nCi((Ir8fyUu0F2C7Ir5QWORQQA …
```
=> Fix min/max progress with old auras

WeakAurasOptions/Cache.lua
I don't get why spellIds / iconIds were concatenated as strings instead of table of numbers, this should help with the known issue when storing a lot of strings in SV, and should run faster
comment with unused block of code is left to find new "holes" in spellIds for next classic versions
i tried it on classic_era/classic/retail/tww, retail & tww don't have such spellids holes
=> spellCache

.luacheckrc, WeakAuras/AuraEnvironment.lua
found these by grepping through blizzard interface code with `/Mixin = ".*Mixin"/`
=> add more mixins to exec_env

.luacheckrc, .luarc.json, WeakAuras/Init.lua, WeakAuras/WeakAuras.lua
=> Fix addon compartment for 11.0

WeakAuras/Compatibility.lua, WeakAuras/Prototypes.lua
=> Update GetWatchedFactionInfo to new API

WeakAurasTemplates/TriggerTemplatesData.lua
To everyone who read this, this is 99% automated, feel free to review the classes you know
=> WIP Templates update

WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/Cache.lua
also implement the Unknown Spell feature
=> teach BT2 how to interpret hyperlinks

WeakAuras/Modernize.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AuthorOptions.lua
=> drop nomerge headers

.github/workflows/discord-update.yaml
=> Default discord-update to not run on forks

babelfish.lua
=> deduplicate localization phrases

WeakAuras/WeakAuras.toc, WeakAuras/WeakAuras_Cata.toc, WeakAuras/WeakAuras_Vanilla.toc, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasModelPaths/WeakAurasModelPaths_Cata.toc, WeakAurasModelPaths/WeakAurasModelPaths_Vanilla.toc, WeakAurasOptions/WeakAurasOptions.toc, WeakAurasOptions/WeakAurasOptions_Cata.toc, WeakAurasOptions/WeakAurasOptions_Vanilla.toc, WeakAurasTemplates/WeakAurasTemplates.toc, WeakAurasTemplates/WeakAurasTemplates_Cata.toc, WeakAurasTemplates/WeakAurasTemplates_Vanilla.toc
Adding ## Notes-esMX to the .toc files and making them the same as ## Notes-esES and making any fixes as necessary
I added my local changes to my addons folder and tested
- [x ] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [ N/A] I have commented my code, particularly in hard-to-understand areas
- [ N/A] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
=> Add esMX to toc files

WeakAuras/AuraEnvironment.lua
=> put the mixins in private exec_env too

WeakAurasOptions/Locales/enUS.lua
=> pull enUS locale for Options from CF

WeakAuras/BossMods.lua
Fixes 
See also https://github.com/BigWigsMods/BigWigs/commit/0a1dbd5d65152a04d610bc1e605ea77f5f63bcc3
`/dump BigWigsAPI:GetLocale("BigWigs: Plugins")`
nil
`/dump BigWigsAPI:GetLocale("BigWigs").pull`
not nil, new location for these strings
=> Fix BigWigs locale for Break and Pull bars

WeakAuras/GenericTrigger.lua, WeakAuras/TSUHelpers.lua
this is achieved by saving the information in an external table `changedStates`
also add functions to the states table: IsChanged() and SetChanged()
fixes #5825
=> TSUHelper: hide __changed from pairs()

WeakAurasTemplates/TriggerTemplatesDataMists.lua, WeakAurasTemplates/WeakAurasTemplates_Mists.toc
=> Mists Templates

WeakAuras/AuraEnvironment.lua
I wanted to truncate a class-colored name and this seemed like the easiest way to do it. The `WA_ClassColorName` function needed to be moved after `WA_Utf8Sub` so that the former could call the latter. It's very possible that I overlooked an easier way to accomplish what I wanted.
Here is a simple test aura where the `maxlen` parameter can be excluded or adjusted to draw the target's name in the middle of the screen, possibly truncated.
```
!WA:2!1rvZUTTrq4iOdfGiOWrOWO)eGqOIgeJw4uOGKBPTMcIWjqrsLIUo9eZsUdf32v7Uy3LYw5Oqp0Z(rqxBrpOhHETxiek6dGFeYtqNLuPUWWMasAMrF7mZ33mlBf2zEhAh6VEGwwA5mbOhFs8WxmAquMKl1VSn(SHYmkozzmCUT7xKToR0yLZDEQ)kVuKzzsXJoWZhFy5(Ksnjbelo0yjwWNiOxl0HLcM13waI6J4E4Ymc3Vo(ZVj0)hqnyl1c)tpkPpNym9D94iYC4rouF1tp494QpaWnW1pz3jebW9hRar3gqcQN7JN3wtbHkp7hhNNBa79VZgIiRqQNizcBA)bJIheP8)Fsr …
```
=> Add optional length limit to `WA_ClassColorName`
