WeakAuras.lua
Auras with EncounterId load condition now has their Init script (if any)
run immediately upon entering on a raid instance.
=> Load Init script if the aura has EncounterID trigger

Types.lua
Not sure if this has been left out for a good reason or not?, but I updated Types.lua to include the "Dialog" sound channel as a selection during WeakAura creation.
=> Dialog as a Sound Channel

GenericTrigger.lua, Prototypes.lua, WeakAuras.lua
449 - BigWigs /pull bar doesn't get removed when a new /pull is executed
446 - LUA error when trying to create a BigWigs Timer trigger
447 - Allow multiple values in Encounter ID field
230 - Dynamic Group progress bars not disappearing (and overlapping)
The last fix should be tested for some time.
=> Fixes for various small tickets

Options/WeakAurasOptions.lua, Transmission.lua, Types.lua, WeakAuras.lua
Add capability to specify a custom trigger combination function that will be run to decide whether the overall aura is triggered based on the status of the individual triggers. This enhances the current funcitonality of ANY or ALL triggers to allow complex logic, such as "Trigger 1 AND (Trigger 2 OR Trigger 3)"
http://pastebin.com/Dw1nVVJs is an example aura using this change.
Additionally, this change REMOVES the checks in Tranmission.lua:scamCheck that only showed code int the code review if the code was enabled. With this change, if their is custom code present in the WA when transmitted, the code is shown.
remove checks in scamCheck that only showed enabled code. All code is shown in the transmitted aura
http://pastebin.com/ki2heZzx is an example of an aura that (in today's client) …
=> WeakAura Ticket 480

Options/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, Options/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua, Options/RegionOptions/aurabar.lua, Options/RegionOptions/progresstexture.lua, Options/RegionOptions/texture.lua, Options/WeakAurasOptions.lua, RegionTypes/text.lua, Transmission.lua, WeakAuras.lua
There are 3 parts to that preparation:
- In Transmission.lua change how the auras are created on login, basically some code moves from ADDON_LOADED to PLAYER_LOGIN. That allows other addons to register their region types in their ADDON_LOADED handler and be ready before the regions are created.
- Improve the code that deals with unknown region types. Regions that are not supported are displayed as text auras with a informative text message.
- Make the texture selector useable for the StopMotion addon, by allowing that addon to pass in the textures table and allow it to display it's special textures.
If I uploaded the current state of my StopMotion addon to: https://onedrive.live.com/redir?resid=6F73AA556E38CB8B%2154583
I do have plans for some additional features and more textures, but I …
=> WeakAuras: Prepare for StopMotion Addon

Options/WeakAurasOptions.lua
Testcase that shows the problems:
Import http://pastebin.com/rS4S5ePq, that is a group with two auras.
Both auras contain 3 identical triggers.
Bug 1:
Select the group, switch to the trigger tab. Notice that only
two triggers are listed in the choose trigger combo box.
Bug 2:
Choose both auras (not the group), switch to the trigger tab,
in the choose trigger combo select the second or third trigger
=> Fix editing multiple auras with multiple triggers

Options/WeakAurasOptions.lua
Use code provided by Semlar to make pasting a lot faster.
The edit box no longer shows the contents of the pasted text,
but that's not a huge loss.
=> Make pasting huge import strings lightning fast

BuffTrigger.lua, GenericTrigger.lua, Options/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, Options/RegionOptions/aurabar.lua, Options/RegionOptions/icon.lua, Options/RegionOptions/text.lua, Options/WeakAurasOptions.lua, Prototypes.lua, RegionTypes/aurabar.lua, RegionTypes/dynamicgroup.lua, RegionTypes/icon.lua, RegionTypes/progresstexture.lua, RegionTypes/text.lua, Transmission.lua, Types.lua, WeakAuras.lua
Those store all information of the triggers, e.g. duration, icons.
This allows for e.g. showing the information of the second trigger if the
first trigger is not active.
This is the basis of more to come.
Also first evaluate all triggers before applying change, fixing:
Ticket-Nr: 501
=> Add Trigger States to store information

BuffTrigger.lua, Prototypes.lua
Fix the multi trigger for SPELL_AURA_APPLIED again, after accidentally removing that with the trigger state commit.
Add sourceGUID to the aura_env.state, since destGUID is already there and it might have some uses.
=> Two small adjustments to the trigger state patch

GenericTrigger.lua
Make it check that the type is "event" or "status" similar to
every other function.
=> Fix GenericTrigger.GetNameAndIcon for custom triggers

GenericTrigger.lua, Prototypes.lua, WeakAuras.lua
Fix GetNameAndIcon for custom triggers
Fix error on enabling animations
Fix Cooldown Progress for Lava Burst with Ascendance active
Fix aura_env.state being empty for the first custom function
Rewrite gcd check to use the gcd
=> Various small patches

Options/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, Options/WeakAurasOptions.lua, RegionTypes/dynamicgroup.lua, WeakAuras.lua
Add a PauseAllDynamicGroups() and ResumeAllDynamicGroups() which
temporarily delays all ControlChildren calls.
The dynamic groups are paused before mass editing, such as importing,
clicking the view icon, deleting the group. This makes it significantly
faster to edit those auars.
Ticket-Nr: 581
=> Make gigantic dynamic groups editable in the options

Options/WeakAurasOptions.lua
In a recent commit to correct how groups and multiselection work,
I broke that by calling set(info, ..., not before), set gets passed
only the first value of in ...., but for colors 3 values need to be
passed.
So special case multiselection, and only pass the third value in
for multiselection.
The reason we need to pass in the third value for multiselection,
is that the set functions for multiselections by default only toggle
a value. If different auras in a group had different initial values,
toggling them leads to interesting behaviour.
=> Fix setAll for colors

WeakAuras.lua
Something like this custom trigger currently only works when none of the triggers used are of the 'aura' type:
```
function(values)
if values[2] and values[3] and values[4] then
ActionButton_ShowOverlayGlow(WeakAuras.regions[aura_env.id].region)
else
ActionButton_HideOverlayGlow(WeakAuras.regions[aura_env.id].region)
end
return values[1]
end
```
My patch fixes this by activating the environment in evaluateTriggerStateTriggers. I tested it for my broken case and everything seems to be working: https://wago.io/EkwSOOpKW
=> activating aura environment when aura triggers custom logic

Options/WeakAurasOptions.lua
This feels like a Blizzard bug. Apparently the scroll frame no
longer clips the mouse interaction. So increase the okay and cancel
button's frame level to ensure that they are in front.
=> Order the texture pickers's okay/cancel button and the textures

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
This PR implements ~~rudamentary~~ drag'n'drop support to the `DisplayButton`s in the Options.
Feature and Design is descripted in some [sketches](https://drive.google.com/drive/folders/0BzaKJginnJcgM3dHWUdDQlNRZGM?usp=sharing).
The implemented features make several `DisplayButton` controls in their current form obsolete.
Chiefly the side control of grouped  buttons (up, down, ungroup) which also distinguish grouped buttons from ungrouped one. 
(see https://www.wowace.com/projects/weakauras-2/issues/790 )
-    ~~If the `DisplayButtonList` is *not* scrolled to the top, the `DisplayButton` is not __*visually*__ dragged, but dropping it still works at the __cursor__ location.~~
-    ~~If the `DisplayButtonList` is being scrolled while dragging, the dragged element is shown in its original …
=> Drag'n'Drop implementation for DisplayButtons

WeakAuras/Prototypes.lua
Uses the same condition as Cooldown Progress (Spell) now
=> Fix Action Useable trigger

WeakAuras/Prototypes.lua
Reported on discord. For those triggers, unit is initialized from
the second event parameter. That is no longer guranteed to be
a unit id, since those triggers now watch for more events.
=> Fix Health/Power triggers

WeakAuras/GenericTrigger.lua
This is a non-breaking change that fixes the argument order in WeakAuras.GetBigWigsTimer.
=> fix wrong argument order in GetBigWigsTimer

WeakAuras/GenericTrigger.lua
Mostly, charges is 0 even if the Raging Blow is not on cooldown.
=> Fix GetUnifiedSpellCooldown for Raging Blow

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua
A long time ago, WeakAuras 1 had a conditions field for each
aura. That got replaced by a separate conditions trigger.
In my upcoming conditions feature I want to add a .conditions field
to auras.
Removing this Modernize code let's me switch to master without the
old Modernize code breaking my new conditions
=> Modernize: Remove old conditions modernize code

WeakAuras/GenericTrigger.lua
Another small tweak to unified cooldown function.
A spell on gcd cooldown is not a spell with a cooldown.
Ticket-Nr: 910
=> Fix Expel Harm again

WeakAuras/RegionTypes/ProgressTexture.lua
Apparently setting the bar to a zero width resets!! the width. The code
contains a work around for that ensuring that progress is at least
0.00001. Apply the same to when we inverse progress in SetInverse.
Also rename region.inverse to region.inverseDirection, as SetDurationInfo
does already use region.inverse
Ticket-Nr: 955
=> Fix Condition toggling inverse for Progress Bar breaking the display

WeakAuras/WeakAuras.lua
As it happens, there actually is a use for calling WeakAuras.ScanEvents inside of the init script of an aura: doing so triggers ActivateAuraEnvironment, which then runs the appropriate init script if it hasn't completed yet; handy if you want to ensure that one aura (a library of sorts) which defines several functions you use elsewhere is loaded first. However, the code has no notion of whether or not an init script has begun execution or not, which leads to the possibility of a ScanEvents chain leading back to your original init script. This leads to infinite recursion, and very quickly a stack overflow.
This PR addresses this by making data.init_completed trivalued; it can be 'not started', 'started', and 'complete', and ActivateAuraEnvironment will only run the init script when that …
=> Fix potential Stack overflow

WeakAuras/RegionTypes/Model.lua, WeakAurasOptions/RegionOptions/Model.lua
SetTransform is supposed to overwrite the camera that is set on
the model. But instead it apparently uses a random camera.
TheDanW promised a fix in 7.3, which unfortunately will change
the behaviour of models.
Thus, warn against using SetTransform in the option text, and
change the default for models to not use the SetTransform option.
Also reset the model transformation and others 2s after login, as
apparently the camera is different while still loading.
This fixes the aura attached to Ticket 968, and also works with
the aura in ticket 964.
Ticket-Nr: 968
=> Model Aura: Work around Blizzard bug with cameras

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/Locales/enUS.lua, WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua
Add a way to clamp progress for the display. Values below a user
set minimum are displayed as empty progress. Progress above
a maximum are displayed as full progress.
Usefull when several displays have the same size and should move
with the same speed but their triggers have different durations.
=> Custom Progress options for displays that show progress

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
New Feature: Allows a combat log event trigger to specify that the source or dest unit have a specific raid mark, any raid mark, or none.
=> Add raid flag checks

.editorconfig, .luacheckrc, WeakAurasOptions/OptionsFrames/ImportExport.lua, WeakAurasOptions/OptionsFrames/TextEditor.lua
I have decided to remove double and triple click word/line selection and do it in a future update
* ctrl + s closing and esc cancelclosing
* automatic bracket mathcing
* editor color themes
* ~~the following bug appears when changing themes, [pastebin link](https://pastebin.com/n09TWUcf)~~
* ~~Some issues with bracket matching when pasting code~~
* ~~editor themes not being saved across sessions~~
=> Editor bracket matching, ctrl+s saving and esc cancelclosing, editor color themes

WeakAuras/WeakAuras.lua
Gemcutting is a very difficult to master and refined delicate art and weakaura HUDs (which are the best) should not interfere with this delicate and intricate process.
On a more serious note this makes it that WeakAuras considers the shown gemcutting UI as a vehicle and a vehicle UI (the small icon that remains shown is part of me testing some other weakauras and is not part of the overal HUD)
=> Consider the gemcutting UI as a vehicle and vehicle UI as well

WeakAuras/WeakAuras.lua
If the user enables "ignore personal nameplate" in KNP, a WeakAura which is supposed to be anchored to the PRD simply isn't shown (since the .kui frame isn't shown, but still exists on the nameplate).
Also, you don't use KuiNameplatesPlayerAnchor. Am I doing something wrong with that? (not that using that would fix it, just wondering.)
<3
=> fix PRD hook when KNP option 'ignore personal nameplate' is used

WeakAuras/Prototypes.lua
As that can affect whether a unit such as party1 exists
Ticket-Nr: 1026
=> Add GROUP_ROSTER_UPDATE event for watching specific units

WeakAuras/Prototypes.lua
Some doofus broke it, when he added IsPlayerSpell
Ticket-Nr: 1028
=> Fix IsSpellKnown trigger for pet spells

WeakAuras/WeakAuras.lua
Dunno how else to post this. There are currently two different _G lookups that can be fed arbitrary keys from within custom display code to retrieve globals otherwise blocked through blockedFunctions. I can provide proof of concept code if needed (via Twitter pm @lqnrd), but will obviously not post that here.
Some comments about this pull:
- `_G` and `getglobal` being added to `blockedFunctions` is just a convenient way of having those two included in the check, and will not alter the rest of the code, as these two keys are checked and handled in `exec_env` before `blockedFunctions` is checked.
- The two functions `WeakAuras.PerformActions` and `GetAnchorFrame` will throw errors when called with malicious arguments, but should still function just as before with legitimate input. For now …
=> protect _G lookups

WeakAurasOptions/OptionsFrames/ImportExport.lua, WeakAurasOptions/OptionsFrames/TextEditor.lua
7.3.2 fixed the bug, so we can remove our workaround again.
This reverts commit 8305cd5733c6b4470a84a8df37bd725e104b9c1c.
=> Revert "Work around Editboxes buggyness with 7.3"

WeakAuras/RegionTypes/RegionPrototype.lua
```
Message: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:324: attempt to compare number with string
Time: 11/22/17 16:11:34
Count: 846
Stack: ...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:324: attempt to compare number with string
Interface\SharedXML\SharedBasicControls.lua:208: in function `origErrorHandler'
...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:317: in function <...rface\AddOns\TradeSkillMaster\Debug\ErrorHandler.lua:300>
[C]: ?
...ace\AddOns\WeakAuras\RegionTypes\RegionPrototype.lua:324: in function `SetDurationInfo'
Interface\AddOns\WeakAuras\WeakAuras.lua:3611: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3593>
Interface\AddOns\WeakAuras\WeakAuras.lua:3695: in function <Interface\AddOns\WeakAuras\WeakAuras.lua:3687> …
```
=> RegionPrototype.lua: attempt to compare number with string

WeakAuras/Transmission.lua
`WeakAuras.spellCache` is nil until WeakAurasOptons has been loaded.
Steps to reproduce: Reload interface. Have another person link a display with an Aura trigger (and Aura Name, like spellId). Click on link.
I'm not sure if the same can happen in line 468 in function `WeakAuras.DisplayToString`.
=> field 'spellCache' can be nil

WeakAuras/WeakAuras.lua
Hopefully using a current version this time :)
Pure quality of life change for people who use `WeakAuras.regions[aura_env.id].region` a lot.
=> adding region table into aura_env

WeakAuras/Prototypes.lua
Apparently there's a unknown parameter now (probably since the start
of Legion.)
Ticket-Nr: 1092
=> Combat Log Trigger: Fix SPELL_ENERGIZE

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
- Don't copy controlledChildren.
- In the context menu for groups offer only "Copy Group"
- Pasting a individual auras settings onto a group paste it to
each child.
=> Fix Copy/Paste code for Groups

WeakAuras/BuffTrigger.lua, WeakAuras/GenericTrigger.lua
Before b3e57359e128d4e23f9f7f3bf1b9c64f6300293b would overwrite
the duration information in the fallback state.
Github-Issue: 382
=> Setup fallback state so that it has no duration

WeakAuras/RegionTypes/RegionPrototype.lua
If a child of a dynamic group has anchorFrameType of SELECT and anchorFrameFrame refers to a frame which doesn't exist, then WeakAuras will get stuck in a loop trying to anchor, which eventually causes the group to fail to control its children. We can prevent this by forcing GetAnchorFrame to detect a dynamicgroup parent.
=> ticket #456

WeakAuras/HelperFunctions.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc
WeakAuras.UnitAura, WeakAuras.UnitBuff, WeakAuras.UnitDebuff - mimicking functionality from pre-8.0
WeakAuras.GroupMembers - Very popular in Legion.
This would be a bit of a step off the normal path so I totally understand if providing stuff for custom WA authors isn't something you want to get into, or if the functions I added simply aren't strong enough that you want them to be carried by your addon. 
However, I thought that if I throw a PR up then it at least sparks the discussion and you can always reject the PR if you're not keen.
=> Add functions commonly used by custom WA authors

WeakAuras/WeakAuras.lua
This shouldn't have been a problem, but sortHybridTable isn't properly maintained and can collect clutter if an index becomes no longer valid. Fix this by double checking before migrating that index.
=> ensure that the childID exists before using it

CONTRIBUTING.md
Added 2 links for people to follow if they want more information to explain why they need to force push after a rebase.  
Since rebasing can be a complicated subject on its own for newer programmers, some people may find it unsettling to have to force push if such an operation is so 'destructive', the way it is described in the CONTRIBUTING.md.  These links can help contributors understand why it must be done as well as the benefits of rebasing their branches.
=> Add links to explain force pushing for rebase

WeakAuras/RegionTypes/Icon.lua
Animation scale funcs can return 0, 0. This would set the width and height to 0.
But then the aspect ratio of that is NaN. So guard against that since SetTexCoord
doesn't like getting NaN.
Github issue #533
=> default to ratio of 1 if the aspect ratio is undefined

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
This option let you change the duration & expirationTime for bigwigs and dbm timers
I did this because bossmods tend to give timers that end when a boss start casting instead of when they finish their cast.
Tests done for both bigwigs and dbm 
- with and without remaining time set
- with and without clone per event set
- with positive and negative value
- with negative value > - duration (it skip bar creation)
screenshot of gui:
https://i.imgur.com/XBP7JO4.png
The timer adjustment is done in WeakAuras.CopyBarToState() and  WeakAuras.CopyBigWigsTimerToState()
To avoid that the bar stop prematurely from DBM_TimerStop or BigWigs_StopBar events i made it skip them if extendTimer is set, and use state.autoHide = true instead
=> Add "Adjust Timer" option to DBM and BigWigs timers

WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/Locales/enUS.lua, WeakAurasOptions/RegionOptions/Icon.lua
This allows the user much finer control over custom text replacement,
including easily using custom text on multiple regions in a single aura
=> allow arbitrary return values from custom text function

WeakAuras/BuffTrigger.lua, WeakAuras/Types.lua, WeakAurasOptions/BuffTrigger.lua
The goal is to provide options in the group=unit settings for users to specify raiding roles to watch and also exclude themselves from results.
The use case I had in mind for this was be to track "tank swap" debuffs on other tanks. These settings would let users only see debuffs on other tanks which is a very common thing to want to see without a very satisfactory method currently. 
Currently while raiding as tank I would *always* focus my cotank and use the focus unit for tank monitoring Auras. This gets messy when there are 3 tanks and removes any other uses I might have for my focus. Other people have made complex TSU auras to track the other tank. 
Of course I expect that the setting could be useful for other stuff too.
=> Add group unit options

WeakAurasTemplates/TriggerTemplatesData.lua
The Luminous Barrier cooldown template sets Evangelism as a required talent in order to load the aura which will never happen since both talent share a row.
=> Fixing the Luminous Barrier CD template

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/RegionTypes/Group.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/WeakAuras.lua
The group/dynamic group now simply record the desired frame levels
in their modify function. And get the desired frame level in the
expand function.
Github-Issue: 613
=> Rewrite SetFrameLevel code to be more robust for clones

WeakAuras/Transmission.lua, WeakAuras/Types.lua
Implements two requests in #579 - placing update category `metadata` at the bottom of the list, and using the `Import as Copy` phrase for when an identical import is received, and the only possible mode is to import as a copy.
All changes are entirely cosmetic and do not affect the functionality of importing.
=> Aura updating UI tweaks

WeakAuras/WeakAuras.lua
`securecall` can be used to break out of the environment. `ForceQuit` has been protected for some time now and can only be called from Blizzard code.
=> add securecall to blocked functions, remove ForceQuit

WeakAuras/BuffTrigger.lua
An early modernization (v1 -> v2) was unintentionally changed, which unfortunately breaks the v5 -> v6 modernization.
So revert that.
Reported on Discord.
=> revert a bad change to an earlier modernization

WeakAuras/RegionTypes/Icon.lua
Allows Masque to handle the Glow which inludes a custom glow for Circular Icons.
=> Let Masque Skin the Glow

WeakAuras/WeakAuras.lua, WeakAurasOptions/OptionsFrames/IconPicker.lua
Also check player talents on input and get the spell id from them. Allows to create auras for talents you are currently don't specced into.
=> add talent checking to inputs

WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasTemplates/TriggerTemplates.lua
=> use correct field for color
=> for aura and totem, use yellow color instead of glow for all regionTypes except "icon"
=> model : no conditions
Rename isUsableBlue => isNotUsableBlue
#660
=> Fix templates for all regionTypes

WeakAuras/Transmission.lua
If a user clicks on a link in chat, then the import tooltip will appear and allow them to import an aura. This is fine, but importPendingData calls WeakAuras.CloseImportExport, which assumes that the options frame has been created. So, Load WeakAurasOptions and Show the options Frame, and if that fails then back out of the import job.
All of this would be solved if we weren't abusing the tooltip like we are.
Issue reported on Discord.
=> Ensure that Options Frame exists before commiting to an import job

WeakAuras/RegionTypes/ProgressTexture.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua
A rare case where fixing a bug involves only removing code.
Apparently at some point circular progress textures were meant to use
a different crop setting that applied to both x and y. While the option
was visible the actual aura used the crop_x/crop_y settings shared by
normal progress textures.
Thus simply removing the superflous option and making the normal crop
settings fixes the bug.
Github-Issue: 674
=> Fix crop for Circular Progress Textures

WeakAuras/RegionTypes/Text.lua
Blizzard's anchoring code changed with BfA and it is suggested to use GetStringHeight for FontStrings.
From IRC:
```
[23:49:10] nevcairiel: Stanzilla: basically dont use GetHeight on FontStrings, use GetStringHeight instead
[23:50:00] nevcairiel: the big performance issue was fixed in beta already after i reported it
[23:52:15] nevcairiel: its only an issue if the fontstring is not fully anchored  yet
[23:52:33] nevcairiel: because it then tries to resolve anchors that are not valid yet and does a lot of extra work
```
=> replace GetHeight with GetStringHeight

WeakAuras/WeakAuras.lua
This is necessary because the Animated Expand & Collapse feature animates the dynamic group region itself.
This eventually calls ActivateAuraEnvironment, which tries to get the aura environment for the dynamic group.
Before the aura_env support was split off, this would fallback to an empty table, which is rather wasteful since a new extra table would be
created every frame for every dynamic group which is animating an expand or collapse.
=> Create an Aura Environment for group regions as well.

WeakAuras/AuraEnvironment.lua, WeakAuras/WeakAuras.lua
Unfortunately, pAdd does still need to flag the aura as not initialized (since every change to aura data which would require a re-initialization goes through Add), so we do still need a method to do that, so right now it kind of does both.
=> revert back to lazy aura environment creation

.gitignore, .pkgmeta, WeakAuras/Libs/LibDeflate/LibDeflate.lua, WeakAuras/Transmission.lua, WeakAuras/embeds.xml
implement LibDeflate
From my testing, this is approximately a 80% decrease in the size of large string exports, and a further decrease in the size of addon channel transmissions.
This implementation is also backwards compatible with legacy strings, which were compressed and encoded using LibCompress, and older versions without LibDeflate will correctly detect that they cannot decode and decompress the data.
GitHub ticket #406
=>  implement LibDeflate

WeakAuras/AuraEnvironment.lua
the previous fix caused iterations in a party to have an extra unexpected unit, like party5. For whatever reason, GetNumGroupMembers() is inconsistent with GetNumSubgroupMembers(), and GetNumSubGroupMembers() never seems to count the player itself. Since this iterator already squeezes in the player as party0, we can just use GetNumSubgroupMembers() for all party iterations
=> fix WA_IterateGroupMembers again

WeakAuras/RegionTypes/Icon.lua, WeakAurasOptions/ConditionOptions.lua
I like to have the zoom property set to 30% for non glowing icons but if they glow it looks better with 0% zoom, so I added an option to also set the zoom property of an icon via the condition tab.
I used the 'UpdateSize' function to apply the change, it seems a bit heavy but my goal was to keep the change as small as possible. I'm sure there is a better (less CPU heavy) way of doing this.
=> Change Zoom property by Condition

WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua
new "buffId" for abilities that put a buff or debuff with a different spellId
DeathKnight fix for all specs
=> templates: "buffId" & various dk fix

WeakAuras/WeakAuras.lua
the current usage will let the frame be redrawn after it has been working for 16 milliseconds. But this doesn't imply 60 fps, since it will go frame update -> 16ms of work from weakauras -> next frame update.
So, instead, measure the time difference between last frame, and now. This will ensure that weakauras by itself will not consume too much cpu time per frame, though fps might still drop below 60 if another addon has work to do after weakauras finishes its threads.
=> Tweak dynFrame timings

WeakAuras/WeakAuras.lua
This needs to iterate over all existing clones and hide the ones that
are not longer visible, instead of iterating over the list of new
states.
Github-Issue: 874
=> Fix deactivation of conditions on collapsing clones

WeakAuras/RegionTypes/Icon.lua
Whether that's worth it is debatable, but users are always anxious when
kilobytes are used up and in this case there's no good reason for
temporary tables to be created.
Github-Issue: #867
=> Fix garbarge creation in Icon::UpdateSize

WeakAuras/RegionTypes/Icon.lua, WeakAurasOptions/RegionOptions/Icon.lua
Added a description to useGlowColor to explain what exactly it does.
Set glow sub options to hide themselves if the main glow option is disabled.
Added a default glow color of white (1,1,1,1) to the icon region.
GitHub issue #880
=> tweak glow options

WeakAuras/BuffTrigger2.lua
Group triggers are stored in a separate structured, so we need to remove
it from there to on unloading.
The way group triggers are slightly different from normal triggers for
match functions is unfortunate, but requires a bit of refactoring to
fix, and that's not something that should be done before the first
release.
Github-Issue: 893
=> Fix group triggers unloading

WeakAuras/RegionTypes/ProgressTexture.lua
This mostly reverts commit 5a289439da0a32f6a29328cd9cd52b0f42ee9c26,
because it turns out region.scalex and region.scale_x are meant to be
separate. Rename one of them to the more correct crop_x.
Github-Issue: #899
=> Fix interaction between crop setting and circular progress textures

WeakAurasOptions/BuffTrigger2.lua
By moving name pattern out of the way
Github-Issue: #902
=> Fix layout of exact spell ids

WeakAuras/BuffTrigger2.lua, WeakAurasOptions/BuffTrigger2.lua
At least theoretically. I haven't tested more than 20. The actual
trigger code shouldn't care about the number, but the options window
might get slower with 300 extra controls.
Github-Issue: #902
=> Allow up to 100 names/spell ids

WeakAuras/Transmission.lua, WeakAuras/WeakAuras.lua
UnitFullName("player") return nil for server when loading weakauras at login
moved the call when the information is needed
=> fix cross-server transmission after login #934

WeakAuras/WeakAuras.lua
I'm still to scared to simply add it to collapse as that is called in
far too many places to tell whether that would work correctly. Although
it sounds like the right thing to do.
Github-Issue: #939
=> Fix another case where conditions weren't correctly reset

WeakAurasOptions/RegionOptions/Icon.lua
This is a bandaid fix to directly address the concerns in the issue.
There is a more fundamental issue present, which requires more time to resolve.
Specifically, there are several options which show/hide a 'subregion'
and also show/hide several sub options for that 'subregion'. So, it is
impossible to edit a subregion's sub options without showing it. Before now, this
was not an issue, since there was no subregion which you could hide or show in
a condition, and also which had sub options. But now the glow subregion does, and
I expect that future development will cause this same problem to appear with other
subregions.
GitHub Issue #915
=> make glow type option visible when glow is disabled

WeakAuras/RegionTypes/Icon.lua
In 30fa1f72d8ce6d8f54093020746167e68a32c874 I applied a workaround to
SetInverse of clearing and reseting the cooldown time, because otherwise
SetInverse would not show up until the next frame.
Setting a Cooldown does make the cooldown visible though, so apply the
workaround only if the cooldown is visible.
Github-Issue: fix #936
=> Fix SetInverse for hidden cooldowns

WeakAuras/RegionTypes/Icon.lua, WeakAurasOptions/RegionOptions/Icon.lua
Hi, I'd like icons with stacks (eg. spells with charges) to display like the default actionbars show them: the cooldown swipe is visible if there are no stacks remaining, and the swipe edge is visible if the spell is recharging with stacks remaining.
This is a quick and dirty stab at doing that; it might not be desirable for all icons to behave this way.
=> hide cooldown swipe & show edge on icons with stacks

WeakAurasOptions/BuffTrigger2.lua
Since 'invalid unit' can mean either nonexistent unit,
or that the unit exists but is not a valid target for the tracked aura.
So, explicitly call it a nonexistent unit, instead of just invalid.
Reported on discord.
=> adjust trigger.unitExists option name

WeakAurasOptions/ForAllIndentsAndPurposes.lua
fix ```60: attempt to index global 'L' (a nil value)[C]: in function `xpcall'``` when using cast trigger with option "inverse"
=> fix texteditor crashing on PTR - ticket #971

WeakAuras/RegionTypes/Icon.lua
There is [code](https://github.com/WeakAuras/WeakAuras2/blob/master/WeakAuras/RegionTypes/Icon.lua#L225) for making frameId of icon regions unique, however it does not work currently.
=> Make frameId unique

WeakAurasOptions/AuthorOptions.lua
=> Check for tables for default in AuthorOptions

.luacheckrc, WeakAuras/WeakAuras.lua
since (2 - 0.1)/0.1 is ever so slightly less than 19, according to a computer
This is a slight behavior change, since number inputs will round instead of flooring.
Reported on Discord.
=> Fix floating point error

WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/RegionOptions/Group.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/RegionOptions/Model.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/RegionOptions/Texture.lua, WeakAurasOptions/WeakAurasOptions.lua
This will cause a slight appearance change in the UI, when auras of disparate region types are Picked. Instead of a large font description header, an actual header type is chosen (this can of course be adjusted if necessary). Beyond that, there should be no user-facing changes from this pull request.
=> Prepare for collapsible groups

WeakAuras/WeakAuras.lua
WoWAce Issue: [1279](https://www.wowace.com/projects/weakauras-2/issues/1279)
- Without this change, auras attached to the PRD are actually located approximately halfway between the PRD and bottom right corner of the screen.
- With this change, auras attached to the PRD are correctly positioned
=> fix PRD regression

WeakAuras/WeakAuras.lua
This is a better fix of the login issue introduced with the WoW 8.1 patch (which seems to limit the amount of time that we have to perform the login process to 19 seconds).
=> Fix login process

WeakAuras/Transmission.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
- Show a small icon on groups when there is an aura in the group that can be updated
This give a way to see where you have updates when groups are collapsed and the group itself doesn't have update data.
The icon position and look can probably be improved
- Match updataData with companion addon's data by uid instead of "slug"
It make the assumption that an uid is set on every aura, which require a patch **TODO**
- Move version information from url to it's own field, added migration and bumped internalVersion to 10
We want Wago to add the version field on each aura now **TODO**
These 2 points require to use a branch of the Companion that i have not merged yet https://github.com/WeakAuras/WeakAuras-Companion/tree/uidkey it's ready for merge tho.
- Moved matching and update data retrieval to …
=> Companion: Indicator on group, match by uid, version field

WeakAuras/WeakAuras.lua
If a user has enough auras that the login thread takes > 15 seconds to finish, then the game will begin properly before login is done. So ensure that the regions created by SetRegion do not start out shown.
- Bug fix (non-breaking change which fixes an issue)
=> Teach SetRegion to create regions initially hidden

WeakAurasTemplates/TriggerTemplates.lua
Templates with aura active => glow for abilities used wrong field for condition check
With Bufftrigger2 :
- when show on = Aura Found, condition check have to test field "show"
- when show on = Always, condition check have to test field "buffed"
=> template: fix aura active = glow when trigger use Show On = Aura Found

WeakAuras/WeakAuras.lua
In 1779683 SetRegion was changed to hide all regions initially.
While auras are shown/hidden after processing a trigger update, groups
are unaffected by that and need to be always visible.
Argueably they should the check the status of their children, but that's
bigger change, so just revert it for groups/dynamicgroups.
Fixes #(issue)
=> Fix SetRegion hiding groups

WeakAurasOptions/WeakAurasOptions.lua
fix https://github.com/WeakAuras/WeakAuras2/pull/1030/files#r242282479
=> make RefreshGroupUpdateIcon iterate only on its children

WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/RegionOptions/Group.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/RegionOptions/Model.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/RegionOptions/Texture.lua, WeakAurasOptions/WeakAurasOptions.lua
We merge the options of various different region types with a simple
union, thus if e.g.:
Icon returns
icon.__index == 1
position.__index == 2
And Aurabar returns
aurabar.__index == 1
border.__index == 2
position.__index == 3
Then the merged list will contain
aurabar.__index == 1
icon.__index == 1
border.__index == 2
position._index either 2 or 3, depending on which gets unioned last
This means that fixMetaOrder can not figure out which of border or
position should come first. (It does that correctly only due to sorting
border/position alphabetically.)
Fix that by usign the same __index for Position and Border settings.
This is not ideal, but the correct algorithm is rather complicated.
And keep the api stable, as the stop motion plugin depends on it.
=> Fix ordering of options on multi-selection

WeakAuras/AuraEnvironment.lua, WeakAuras/Transmission.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/ImportExport.lua
Fixes #1029 by updating the Import API to accept a target. Additionally, fix a bug where importing old auras with no uid would cause them to always be interpreted as a new aura, and never as an update.
Specifically, `WeakAuras.Import` has been introduced, which accepts either an encoded string, or the equivalent decoded lua table, and optionally a uid or data table which functions as a target for the update. If a valid target is provided, then the imported data will always be interpreted as an update. If no valid target is provided, then the database will be searched for a match as usual.
For the sake of backwards compatibility, `WeakAuras.ImportString` is provided as an alias for `WeakAuras.Import`. Any addon which currently calls `WeakAuras.ImportString` will be unaffected by this …
=> Update ImportString API

WeakAuras/Transmission.lua, WeakAurasOptions/AuthorOptions.lua
User-facing strings in custom options now accept [UI escape sequence](https://wow.gamepedia.com/UI_escape_sequences) patterns. In particular, option name, description text, and tooltip text now can be formatted.
1. Add any option, and then write `|cFFFF8800Orange|r|cFFFF0000Red|r!` into the name, description text, or tooltip text.
2. Enter `User Mode`. You should see the string you entered colored appropriately.
=> Allow custom options to format text

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
fix wago menu at same position for auras and groups
rename "Ignore this Update" to "Skip this Version"
rename "Stop ignoring this Update" to "Don't skip this Version"
show skip version option, and update option, only if aura as update data
=> fix wago menu

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
Fix error reported on discord
```
4x WeakAuras\WeakAuras-2.11.0-beta2.lua:4381: ...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1519: attempt to compare nil with number
[C]: in function `assert'
WeakAuras\WeakAuras-2.11.0-beta2.lua:4381: in function <WeakAuras\WeakAuras.lua:4364>
Locals:
(temporary) = false
(temporary) = "...eGUI-Widgets\AceGUIWidget-WeakAurasDisplayButton.lua:1519: attempt to compare nil with number"
```
=> fix nil error in version comparison

WeakAuras/WeakAuras.lua
After migration to internalVersion 10, auras can have their "version" field not matching the version taken from wago url, and keep their outdated number.
It can lead to problem like https://github.com/WeakAuras/WeakAuras-Companion/issues/53 where companion wants to updates childs with broken version field while parent has correct version.
Also previous migration didn't convert the version to type number.
=> Migration 10 did not update "version" if field was already set

WeakAurasOptions/AuthorOptions.lua
Fixes #1092.
This is not a retroactive fix, since it's a data issue and the relevant feature hasn't yet been released beyond beta. New auras will be correct automatically. Older auras with this problem can be fixed by cycling the defaults to generate the correct data.
1. Import the test case in #1092
2. Change the default values on all of the elements of the toggle list option at the end of the Custom Options.
3. `User Mode` works correctly now.
=> fix default values for multiselect

WeakAuras/WeakAuras.lua
This way, we can actually see what the stack trace is.
This:
is much better than this:
1. Cause an error in one of our coroutines (like, for example, attempting to reproduce #1107)
2. Notice that the reported error is much more informative.
=> improve coroutine error handling

WeakAurasTemplates/TriggerTemplatesData.lua
Templates were lacking the new raid's trinket related itemIDs/spellIDs so I added them.
- no testing , i trust my sick wowhead lookup-the-spellID skills
Even though I was careful, there might be whitespace somewhere 🤔 , if there is then i blame web-pr
=> adds battle for dazar'alor raid trinkets to templates

WeakAuras/Types.lua, WeakAurasOptions/AuthorOptions.lua
A few things which didn't make it into 2.11:
- Merge `User Mode` of multiple auras, instead of rendering them separately, done for usability reasons in large groups with Custom Options. **This is a breaking UI change!**
- Separator Option type
- Option key field in `Author Mode` now turns red and warns you if you have duplicate keys
Basic usage tests:
- Merged `User Mode`:
1. Create any aura, add any number of options to it.
2. Duplicate the aura.
3. Select both, and then navigate to Custom Options in `User Mode`.
4. Notice that the options are no longer separated, but are instead merged.
5. Change or add options on just one of the auras.
6. Repeat step 3.
7. Notice that the options are now merged in a similar fashion as in the rest of the addon.
- Separator Option type
1. Create any …
=> More improvements for Custom Options

WeakAurasOptions/WeakAurasOptions.lua
fixes #1107
1. Create any aura
2. Go to trigger tab, ensure that the trigger type is `Aura`.
3. Enable "Exact Spell ID", then enter `2147483648` into the input field and click OK.
4. Notice that the field does not accept this value, and reverts to its previous value.
=> guard against invalid inputs to auraspellids

WeakAuras/RegionTypes/Icon.lua
Masque doesn't unskin buttons correctly.
We reuse buttons e.g. two buff triggers checking for buffs on
focus/target will reuse the same button. If a button was already in a
group and we change the masqueId and thus want to add the button to a
new group, but the new group is disabled, masque applies a "Blizzard"
skin.
So revert that for now, and report a bug for masque
Fixes: #1127
Fixes #(issue)
=> Partily revert 7f62571f434c, Masque integration fixes

WeakAurasOptions/ConditionOptions.lua
When adding a new condition with type="Unit", it show a value on initialization which is not set in aura's data. Select an other value, and re-select previous value fixed it.
With this change default value is empty to force user to select a value. (like it is for any "select" condition)
Fixes #1135
=> Don't show a default value for unit type condition #1135

WeakAuras/RegionTypes/Icon.lua, WeakAuras/Transmission.lua
Fixes #1123
Follow the steps to reproduce in #1123. The expected behavior is now the actual behavior.
The starting animation will play again on size change, which is unfortunate. But that is a problem best solved upstream in LibCustomGlow.
=> reset glow on size change

WeakAuras/BuffTrigger2.lua
On a CLEU SPELL_AURA_REMOVED too much data was removed, so that later
events would not correctly know what to remove.
Fixes: #1159
Fixes #(issue)
=> BuffTrigger2: Fix Multi Target clearing too much data

WeakAuras/Prototypes.lua
Fix cast trigger not untriggering correctly => regression from #1143 => Fix #1155
Fix UNIT_TARGET event registered when not needed (with current blizzard bug on this event duplicating this is very bad)
=> Fix cast trigger not untriggering correctly

WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
On login, show this message :
Add icon on weakauras's button if there is a legacy trigger 
Fixes #1049
Deleting the legacy trigger doesn't refresh the button
=> add warning icon on auras with legacy aura trigger

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua
fix icon not hiding after converting to BT2 or on removing trigger
show trigger on icon click
Need to click a second time to show the "trigger" tab when triggers options were not loaded (ace3 bug??)
=> BT2upgrade icon update

WeakAurasOptions/ForAllIndentsAndPurposes.lua
Fix adding trailing line break when editing custom code
=> fix padWithLinebreaks by switching to upstream FAIAP

.luacheckrc, .vscode/settings.json, WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/WeakAurasOptions.lua
This is a rewrite of the dynamic group code (in particular the sorting and positioning code), in order to do less work. By using a differential form of insertion sort instead of <whatever table.sort() does>, we can cut down on the total work done significantly. With these changes, [the most popular set of raiding auras](https://wago.io/bfaraid2) would consume an estimated 2-5 fewer seconds of CPU time during an average raid encounter. What's more, the main optimization involves simply doing fewer things whenever the children of a dynamic group updates. This should greatly reduce the amount of stuttering which dynamic groups can cause, which is the most visible kind of performance problem.
**There are no new features implemented in this pull request!** Some new features (such as grid type, …
=> Dynamic group Rewrite

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/WeakAurasOptions.lua
Address comments on https://github.com/WeakAuras/WeakAuras2/pull/1226/commits/e8fd7808a221b4692ee6945e7a7861be7ad71b6a
Also fix `newData.parent`getting incorrect id when using `newParent` argument
=> optimize and fix parenting issue on WeakAuras.DuplicateAura

WeakAurasOptions/OptionsFrames/MoverSizer.lua
Don't require a reloadui for updating uiscale
=> don't require a reloadui for updating uiscale

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua
This reverts commit dc684ec89f4aca49c6fdc9a6aa39c4692e7eb8cd,
and fixes the issue differently.
Github-Issue: #1284
=> Fix tooltip frame not having a parent and thus eating mouse events

WeakAuras/RegionTypes/DynamicGroup.lua
A bug that is fixed by removing code! This was reported on discord
Import this:
```
!T3zFtjosta8Vlw1tvAvEUqqq92N9QcbwLBrWIG3E(C1fjegG5mKWMmG6(h(z)P7zsc5LjHGVFkNxHyyET7E6PNF0jRwrTEAQt1uhQP6QPwNSaFlCP76mAKlHP1U4HhSxXkhDKc8MYAQlioUuBl46AQ6wgtSD(QJ(usV7Mr0uvR1TrJ24hqNQZWIHnUoL)BgViw2wWRdN7W)8Rex0LyyBn0vJbVLP7WYFXhrTOUtYD5HAysNsHPfmvMtHjTYVx(Nnu)Fh3y)lHR4yQPoHXM5(RF6t3Op2EpQ9NQEO9r)5GZwu6t4u2XOfXAmBIw7svka1WL0I3Gd0uV1xK9lkhD4Ehw5GdlF4HWVu0unSnNp1sDMUbXtYHcicwl95mqi2zgoEDHjcmeD0hsN7Q1wPa0do23SSEo2mHCTn8j4W)uciUM4YGP99975OBCnXrtDa87Xo2ZTGs0MlrG)6gq9257G2HAXiow6M)rGQCFOk2odXQkkUqZEUnuun1AnA3Rrx)IeyxubNwwG(YI9vDdMnu5UvR38cvuGpDb2yf3RWEWa11guPEQgO8JhdFgobCiJH(xy6m8ol9PudCupdkLHUPygJAoAizd0tE)bmpOmXf9nAcBqWv2JDOdfTF36HflnT4ZHc82FeDSOUM26CBFdtDxEpmDUjJ63wU0FssEXzeJ4xehLM0XwlLCmhkoPX2SnFb3ClVlj64L)b2GM …
```
=> Fix Anchoring issue with dynamic group when using children that have SELECTFRAME anchorFrameType

WeakAuras/Prototypes.lua
this was actually added in 2.11
=> add new feature indicator

.pkgmeta, .travis.yml, WeakAuras/WeakAuras.toc
Our build stages were a bit out of order, resulting in the `after_failure` step we previously used to trigger a Discord notification on build failure to never trigger.
I also removed the previous workaround we had for in-expansion-work tags and added automatic uploads to WoWInterface at https://www.wowinterface.com/downloads/info24910-2.12.0.html. I still need to fix the description text over there. The packager, by default, only updates tags there, so we don't have to worry about alpha builds.
=> move travis to a better layout and also deploy to WowInterface

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
The old code defaulted to a exact check, but sometimes a check on the
spell name is more useful.
Fixes: #1309
=> Add a Exact Spell Id option to Spell Known triggers

WeakAuras/RegionTypes/Icon.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasTemplates/TriggerTemplates.lua
I think in 2.13, these features will have aged enough to not count as "new" anymore.
Templates from 2.7.3
Custom Options, Glow, Cooldown Settings from 2.10.0
=> remove stale feature indicators

WeakAuras/GenericTrigger.lua
AddUnitChangeInternalEvents register event with uppercase unit
`tinsert(t, "UNIT_CHANGED_" .. string.upper(unit))`
WeakAuras.WatchUnitChange was sending events without ensuring uppercase
Fixes #1313
=> fix WatchUnitChange sending lowercase unit event #1313

WeakAuras/RegionTypes/Icon.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/WeakAurasOptions.lua
Move glow options in a collapsible group and add more options supported by libcustomglow
Fixes #1299
demo: https://i.imgur.com/Ba9lZiI.gif (border option for pixel glow is out of the screenshot window)
new conditions: https://i.imgur.com/ScQZSOz.png
Rivers talked about using the pencil button for collapsible options, i didn't manage to use it but made it with a collapsible group, should i go back to the drawing board and get it work with pencil collapse ?
I could check how infus did it with the new text options PR.
=> New glow options for icons

WeakAuras/Prototypes.lua
Fixes #1326
Command to get journal's ids
```Lua
local function get_encounter_list()
local encounter_list = ""
EJ_SelectTier(EJ_GetNumTiers())
for _,inRaid in ipairs({false, true}) do
local instance_index = 1
local instance_id
local title = inRaid and "Raids" or "Dungeons"
encounter_list = ("%s|cffffd200%s|r\n"):format(encounter_list, title)
repeat
instance_id, dungeon_name = EJ_GetInstanceByIndex(instance_index, inRaid)
instance_index = instance_index + 1
if instance_id then
EJ_SelectInstance(instance_id)
local encounter_index = 1
encounter_list = ("%s|cffffd200%s|r\n"):format(encounter_list, dungeon_name)
repeat
local encounter_name,_, encounter_id = EJ_GetEncounterInfoByIndex(encounter_index)
encounter_index = encounter_index + 1
if encounter_id then
encounter_list = ("%s%s: …
```
=> Eternal Palace encounter ids

WeakAuras/Init.lua, WeakAuras/Prototypes.lua
Fixes #1343
Disable companion -> reload -> icons show in waoptions
New icon -> cast trigger -> unit="player", caster's target="player" -> select pnj, cast HS, select self (not working on master)
=> Fix cast trigger event + force enable WeakAurasCompanion addon

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
- fix AddUnitChangeEvents for "pet"
- support CLEU with subevent filtering by generic triggers, this is not used yet, but i use it for the cast trigger on target for classic branch 
Fixes https://www.wowace.com/projects/weakauras-2/issues/1340
=> Event filtering fix for unit=pet + one new little feature

WeakAuras/GenericTrigger.lua
Fixes 
```
1x WeakAuras\GenericTrigger.lua:1174: bad argument #1 to 'tinsert' (table expected, got nil)
[C]: ?
WeakAuras\GenericTrigger.lua:1174: in function `Add'
WeakAuras\WeakAuras-@project-version@.lua:3280: in function <WeakAuras\WeakAuras.lua:3260>
WeakAuras\WeakAuras.lua:3343: in function `Add'
WeakAuras\WeakAuras.lua:3030: in function `load'
WeakAuras\WeakAuras.lua:3037: in function `AddMany'
WeakAuras\WeakAuras.lua:1346: in function <WeakAuras\WeakAuras.lua:1334>
```
=> fix nil error while inserting in prototype.subevents

WeakAuras/Prototypes.lua
Forgot to swap text and text operator parameters in `WeakAuras.GetDBMTimer` and `WeakAuras.GetBigWigsTimer`
Fixes #1358
=> fix DBM and BW Timers message filter

WeakAuras/RegionTypes/Icon.lua
Fixes #1363
Confirmed that Glow Y offset is now a usable property change.
=> use sane values for y offset parameters

WeakAuras/Prototypes.lua
I can't reproduce the problem described in the Ticket, but the code
appeared to have a small race, since we only recheck the conditions at
the event.
Fixes: #1365
=> Item Slot Cooldown: Use our own cooldown tracking for durationFunc

WeakAuras/WeakAuras.lua
Fix Companion nag & minimap icon update counter wrongly includes auras with "Skip this version" enable
=> WeakAuras.CountWagoUpdates: don't count skipped versions

WeakAuras/Prototypes.lua
Fixes 
```
52x WeakAuras\Prototypes.lua:3705: attempt to compare number with nil
[C]: in function `xpcall'
WeakAuras\GenericTrigger.lua:371: in function <WeakAuras\GenericTrigger.lua:367>
WeakAuras\GenericTrigger.lua:489: in function `ActivateEvent'
WeakAuras\GenericTrigger.lua:547: in function <WeakAuras\GenericTrigger.lua:519>
WeakAuras\GenericTrigger.lua:672: in function `ScanEventsInternal'
WeakAuras\GenericTrigger.lua:632: in function `ScanEvents'
WeakAuras\GenericTrigger.lua:721: in function <WeakAuras\GenericTrigger.lua:712
```
=> Action Usable trigger: Fix nil comparison error with spellCount

WeakAurasOptions/AuthorOptions.lua
That way, users can delete the entry they want to, instead of always the last one.
=> delete the currently selected entry

WeakAuras/Transmission.lua
A recent 8.2 change forbids use of Show/HideUIPanel in combat
This is to address https://github.com/tomrus88/BlizzardInterfaceCode/commit/86da24305529deb6512ada1bdb894b606394f1ef#diff-1cd1eb166f5fb0f41a5a29500af2be34R3185
Did a simple import from chat
=> Use a simple Show/Hide for the ItemRefTooltip

WeakAuras/RegionTypes/DynamicGroup.lua
This way, users who want to write custom growth/sort functions can use them as building blocks
=> expose dynamic group helper functions

WeakAuras/BuffTrigger2.lua, WeakAuras/Types.lua, WeakAurasTemplates/TriggerTemplatesData.lua
Add debuffClassIcon state to BuffTrigger2 
Fixes #946
this allow to do this with just typing %debuffClassIcon
=> add debuffClassIcon state to BuffTrigger2 fix #946

WeakAuras/Prototypes.lua, WeakAurasOptions/WeakAurasOptions.lua
moved WeakAuras.ValidateNumeric to Protypes.lua
- fix "Item Set Equipped" itemSetId validation
- fix "Power" stagger > scaleStagger validation fix #1414
WeakAuras.ConstructOptions copy validate property for
arg.type == "string", "tristatestring", "longstring", "spell", "aura", "item"
Note:
user with corrupted data will still have error, this only fix the field validation in weakauras options.
=> fix validate property for event_prototypes

WeakAuras/RegionTypes/RegionPrototype.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua
We can't know if a given sound path is actually valid and PlaySound complains now if the sound path isn't valid. So just trap all the errors that would be generated.
Fixes #1421
didn't
=> wrap PlaySound and friends in pcall

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/Model.lua
Two bugs there:
* The Unit Characteristics trigger was missing WA_DELAYED_PEW
* Calling SetUnit too "early" doesn't work. Apparently 4s after the
PLAYER_ENTERED_WORLD is about the time where it can be called.
=> Fix Model: Show Model of Unit

WeakAurasTemplates/TriggerTemplates.lua, WeakAurasTemplates/TriggerTemplatesData.lua
- When creating multiple auras at once, pre-select the last template option for each aura instead of the first : https://i.imgur.com/eue62Gn.jpg
- Added a few spells for all specs of warlock and rogue
Fixes https://www.wowace.com/projects/weakauras-2/issues/1348
PS: maybe don't merge it yet, Infus expressed concerned about adding resource builder/spender spell without cooldown in templates, also this doesn't add these spells for all classes, so it can be considered has a work in progress for the new spells part of this PR
=> Templates update

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
They are filter filtered at the event registration level
Removed "multi" and added a migration to convert it to "nameplate", multi could be seen as listening to CLEUE which is confusing
There is a small regression between previous multi & new nameplate: nameplate listen to NAME_PLATE_UNIT_ADDED and NAME_PLATE_UNIT_REMOVED
=> Cast Trigger: add meta units "group", "arena", "boss", "nameplate"

WeakAuras/embeds.xml
with this change libclassicdurations & libclassiccast needs to be installed standalone with dev non-packaged build
=> another attempt at fixing packager condition in embeds.xml

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
- Load condition function was using incorrect number of args
- Cast trigger was incorrectly using UNIT_SPELLCAST_FAILED as untrigger
Fixes https://www.wowace.com/projects/weakauras-2#c2232
=> Fix classic load condition + cast trigger hidding on buttons press

WeakAuras/BuffTrigger.lua, WeakAuras/BuffTrigger2.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
This fixes a problem where trying to use a custom sort on e.g. a buff trigger that sorts by stacks doesn't properly keep the list sorted.
Reported on discord
=> resort any region which is changed

WeakAuras/Transmission.lua
Securely hook SetItemRef instead of replacing the function.
Fix taint issue with at least community invite links (maybe more)
Need to test this on next Classic stress test, but SetItemRef on classic branch of wow ui source is same as retail at the moment.
=> fix SetItemRef taint

.pkgmeta, WeakAuras/AuraEnvironment.lua, WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/RegionTypes/Group.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/Transmission.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAuras/embeds.xml, WeakAurasOptions/OptionsFrames/IconPicker.lua, WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/RegionOptions/Group.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/RegionOptions/Model.lua, WeakAurasOptions/RegionOptions/ProgressTexture.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/RegionOptions/Texture.lua, WeakAurasOptions/WeakAurasOptions.lua
- Killed group & dynamicgroup thumbnail, use the animated icons instead, with ability to set your own
- Renamed and reorganized a few options in Group and Display tab
https://i.imgur.com/hJIWwj3.png
https://i.imgur.com/sfXrmLt.png
- Use same border settings for both groups and dynamic groups and changed default settings for something closer to pixel perfect style
- New dependency LibGetFrame, publicly accessible with WeakAuras.GetUnitFrame documentation at <https://github.com/mrbuds/LibGetFrame/blob/master/README.md>
- All regions can use a custom anchor function, custom function needs to return a frame
```Lua
function()
return SUFUnitplayer
end
```
- Dynamic group's growers have a new option "Group by Frame", it can be "unit frame", "nameplates" or a custom function. Enabling this option …
=> Custom Anchor - Dynamic Group "Group by Frame" - Border Settings - Groups thumbnails

WeakAuras/Profiling.lua
This allow 3rd party addons to use WeakAuras profiling data
Example with Details "custom display"
```
1fv4kUnmm4xNEqAy7Vd2pcDJTeyDdCzhh3nruJvUAMJDWw(GXy(PzVj7fB2jnx7AVHi2ksF6tYFcEnSde(oNAKbH22H6y7g7WEKlsobpBh2ynmQmKlfP24z00rX23gBlllJnhRHTmQlY3JPtCWgm8eOxvC87zOsKXPu3s43Rco0xo6S9kn9UuMsmhj2eB6TUetP)QLP6Fk2QmX2ru58RYuCtIjBcx7SP6tykjno6jzAooqMtjxS1Rx8oolQoR5FNfb(ejlLk)Og)H)(5()TLa1z8xr7f60BQKYVI6qsLw9ZRrFPzWHz9C5TEvf)Q4S32nNYtgzSz6i2C2cyISlNPpq8UmKkJ8JQhpqEEAexLO7ST1lu12WqvhBtQEUZnoIdoZ)zH3CYabg4dwhi2QK4F(9678wJ0rGqs(oqaIS2dIAdtUESJEOEZN3kEy37)0xarwtaXZlLy70vItMDQ9bMG9GGr3Jep5zTAwncI5o7hjTwjZz82GRlJMb4V
```
and
```
1f1FRTrmm0VoPW1JU)DW(Jq2ylh00coSrHI4uoRKyQp7dB5cJr9NM(nzFXM8LFsshIZNXVNE6jj4tWsqf7cMbguwFhAZTZ89RqUsUKISVFM3XOXrb5L5UiJUok3(LCBDDDUzFoSNrBv5)GCI9(KJhjDx1(VJu1iJJq)IWxMMcySEi4xBS0xfK …
```
=> make profiling data accessible from 3rd party

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAurasOptions/GenericTrigger.lua
Allow usage of multi units (nameplate, boss, arena, group) by custom and generic triggers
exemple of event for a TSU: 
`UNIT_SPELLCAST_START:nameplate`
=> Multiunits

.pkgmeta-classic, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
Fix 2 issues
But on sandbox currently weakauras is not usable due to a bug in ace3
```
1x ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-77.lua:567: CreateFrame(): Couldn't find inherited node "DialogBorderDarkTemplate"
[C]: in function `CreateFrame'
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-77.lua:567: in main chunk
Locals:
(*temporary) = "Frame"
(*temporary) = nil
(*temporary) = <unnamed> {
0 = <userdata>
}
(*temporary) = "DialogBorderDarkTemplate"
```
=> Classic fixes

babelfish.lua
The signs `<` and `>` break the json import string (error 500).
Escape them fix the problem.
https://travis-ci.org/WeakAuras/WeakAuras2/builds/568530798#L267
- Tested the babelfish.lua itself
- Import tested with an test string ">><>Test<><<" ( on another project )
- Export with bigwigs packager ( on another project )
=> fix import error with escape from < and >

WeakAuras/Prototypes.lua
events SPELL_ACTIVATION_OVERLAY_GLOW_SHOW* doesnt exists on classic
=> classic: removed "Spell Activation Overlay" trigger

WeakAuras/Prototypes.lua
fix error when importing a cooldown spell trigger for a spell that doesn't exists
=> Cooldown Spell trigger: guard against nil error when copying aura from retail to classic

WeakAuras/History.lua, WeakAuras/Transmission.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, babelfish.lua
History is a uid-indexed table containing historical information about displays:
source: string indicating where this data came from. Possible values:
"user": aura was created by the user via the WeakAuras interface
"import": aura was imported via WeakAuras.Import (i.e. pasted string or addon channel transmission)
"addon": aura was imported via WeakAuras.RegisterDisplay (i.e. an addon requested the addition)
data: snapshot of data as it was at last import, or nil if source == "user", and the user has not chosen to save their changes to history
addon: if source == "addon", then this string indicates which addon supplied the last import
skippedVersions: record of versions that the user has indicated they don't wish to see update notifications for
allowUpdates: if false, then WeakAuras will …
=> Add history collection

WeakAuras/Prototypes.lua
CLEU: fix ignored parameter on classic for SPELL/RANGE/DAMAGE prefix
=> CLEU: fix ignored parameter on classic for SPELL/RANGE/DAMAGE prefix

WeakAuras/WeakAuras.lua
removed 'spec' parameter from load condition on classic, it was disabled in prototype.lua but not on the function loading it
=> fix load condition error on classic

WeakAuras/Transmission.lua, WeakAuras/WeakAuras.lua
Once upon a time, there was an addon called SpeedrunSplits.
It was a good addon, used by many, in oldschool WoW.
Then, Blizzard decided to make oldschool WoW new again, and a lot of people were very happy.
The author of SpeedrunSplits decided to make his addon available for Clasasic WoW, and again, a lot of people were very happy.
But then, it was  covered that SpeedrunSplits broke the WeakAuras database accidentally, and a lot of people were very sad.
So, we the developers of WeakAuras will make the database more robust against what broke,
And hopefully people will be happy again.
...More seriously, the bug here was that SpeedrunSplits was replacing the tContains function with another
which had incompatible behavior, thus confusing SyncParentChildRelationships into thinking that groups …
=> enhance parent-child validation

WeakAuras/Types.lua, WeakAurasOptions/AuthorOptions.lua
=> allow string custom option to give a multiline edit box

WeakAuras/RegionTypes/Icon.lua
Otherwise these'd be considered part of a different tree of options.
That would be confusing.
=> move *new* glow feature indicators into subtree

WeakAurasOptions/AuthorOptions.lua
Sometimes options might be merged with differing heights.
So resolve this by using 1 as the default height
=> default to height of 1

WeakAurasOptions/OptionsFrames/MoverSizer.lua
fix issue with moversizer not clickable when region strata >= "HIGH"
=> Increase moversizer strata

WeakAurasOptions/OptionsFrames/MoverSizer.lua
This way moversizer isn't above options frame with default auras strata
=> set moversizer strata just above region strata

WeakAuras/WeakAuras.lua
Presumably this was done to eliminate nils here. But `false or true` evaluates to true, so anybody who disabled text1 on icons will wake up to a nasty surprise.
=> fix migration

WeakAuras/RegionTypes/ProgressTexture.lua
The callers and the function disagreed on how many arguments to pass.
Fixes: #1604
=> Fix drawLayer calculation

WeakAuras/Prototypes.lua
fix #1625
I don't understand how it can happen but it seems it's possible that state.extend can be nil which result in an arithmetic error, use 0 instead of nil if that happen
=> bossmod triggers: fix arithmetic error if state.extend is nil

WeakAuras/RegionTypes/Text.lua, WeakAuras/Transmission.lua, WeakAurasOptions/WeakAurasOptions.lua
Importing a model or a group including one break weakauras
This prevent importing an aura of an unsupported region, but doesn't fix the issue if there is already one imported. I have not found a proper solution for this
=> fix "fallback" regionType

WeakAuras/GenericTrigger.lua
With classic release Weapon Enchantment is used again, currently the trigger doesn't return stacks information (like number of poison stacks for rogue) and duration on offhand is wrong.
I currently fixed the duration problem for the offhand, and I'm working on adding stacks information on the trigger.
Not been tested yet.
=> Fix Weapon Enchantment Trigger

WeakAuras/AuraEnvironment.lua, WeakAuras/WeakAuras.lua
fix #1622
Custom anchor function is run on group's Add, before children are added
It activate environment for the group which activate environment for it's children, but that don't work because they are not added yet.
This skip activating environment for group children for this custom function.
=> don't load environment of children for custom anchor function

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
With classic release, shaman and rogue use enchant on their weapon, this pull request aim to add stacks information for weapon enchantment (like rogue poison charges) and improve the weapon enchant trigger interface.
Since I don't have the level to use poisons on my rogue I asked some players to test it for me.
It seem like `Crippling Poison` doesn't return stacks with `GetWeaponEnchantInfo()`.
=> Improve Weapon Enchant Trigger

.pkgmeta-classic
since we don't support models currently in classic WA
=> don't package modelpaths for WeakAuras classic

WeakAuras/History.lua, WeakAuras/Locales/enUS.lua, WeakAuras/WeakAuras.lua
This adds a repair tool. When the database version changes, then a snapshot of each aura is stored into history before running Modernize on that data. If the user then downgrades their WA version past this migration, then WeakAuras detects the change and asks the user to run the repair tool, which will overwrite the database with the migration snapshots.
The user can also manually run the repair tool via /wa repair. This may be handy for fixing bad migrations caught in alpha (though of course, alpha testers should still keep backups 😉).
For now, I would like to mark this feature as experimental, rather than something fully fledged and ready for the most "user" of users to use. I don't believe this will make things worse, but I also don't want to create the expectation that users can just …
=> Add Experimental Repair Tool

WeakAuras/Prototypes.lua
This check was done for "Cooldown Progress (Spell)" trigger but not for "Action Usable"
Fixes #1697
=> fix nil error in Action Usable spellInRange condition #1697

WeakAuras/Prototypes.lua
Option is disabled but if you import an aura with it enable it make nil error
reported on discord
```
"Message: Interface\AddOns\WeakAuras\Prototypes.lua:1549: attempt to call global 'UnitGetIncomingHeals' (a nil value)
Time: Mon Sep 16 08:54:48 2019
Count: 997
Stack: Interface\AddOns\WeakAuras\Prototypes.lua:1549: attempt to call global 'UnitGetIncomingHeals' (a nil value)"
```
=> disable Health trigger overlays in Classic

WeakAuras/Prototypes.lua
fixes #1752
- most LibClassicCasterino callbacks were ignored by ScanEvents because the events were not added the result table of the "events" function
- UNIT_SPELLCAST_FAILED was not handled by the cast trigger at all
=> Classic: cast trigger fix events registration

WeakAuras/Prototypes.lua
fixes #1766
LibClassicCasterino send the callback UNIT_SPELLCAST_FAILED when unit dies or when it detect an enemy player is moving, so i re-added this event for hiding the castbar, but this is an issue on retail because it trigger when you spam your spells.
Depending on @rgd87 answer on https://github.com/rgd87/LibClassicCasterino/issues/20 i wish to delay next weakauras release to after this is changed on LibClassicCasterino
=> cast trigger: don't hide cast bar on UNIT_SPELLCAST_FAILED

WeakAuras/GenericTrigger.lua
Fix an error on getting the shorted name of weapon enchant.
Fix #1787 
`/dump WeakAuras.GetMHTenchInfo()`
=> Fix weapon enchant shortened name

.gitignore, WeakAuras/Types.lua, WeakAurasOptions/AuthorOptions.lua
This is only approximately 80% complete, and needs some heavy testing of edge cases.
This enhancement adds a new dropdown to `Author Mode` of array type options, "Name Source". This dropdown controls how the page selector in `User Mode` displays each entry in the array.
Possible Values:
- Fixed Names
- Only available on arrays with a fixed size. In this mode, the author is expected to specify the name of each entry manually.
- Entry Order
- This provides the default behavior, where each entry is names "Entry N".
- Any key of a suitable sub option.
- There may be 0 or more of these. Any Range, Number, or String type option is a suitable name source. In this mode, the chosen option's user value will be used to name the entry.
=> Allow authors (and users) to customize array option's entry names

WeakAuras/BuffTrigger2.lua
fixes #1809
UnitAura("target", 1) always return nil if i target an enemy.
LibClassicDurations implement it's own UnitAura replacement that works with ennemies buffs.
=> Classic: Use LibClassicDurations's UnitAuraDirect instead of UnitAura

.luacheckrc, WeakAuras/Prototypes.lua, WeakAurasTemplates/TriggerTemplatesData.lua
Add a new trigger "Current Action" for queued spells
Test on a warrior with heroic strike
before use: https://i.imgur.com/iCK1PYw.jpg
when used: https://i.imgur.com/0Pf4ewa.jpg
queued but no more rage: https://i.imgur.com/3aimgfl.jpg
=> Add "Current Action" trigger for classic fixes #1628

WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/WeakAuras.lua
Adds a Property Change that allows the user to adjust the position of a Region relative to its current location. Renames current similar Property Changes to "Absolute X/Y Offset" to help clearly indicate the difference between the two.
Fixes #1561
Initially I wanted to have the Property Changes be additive (such that one Condition could add 10, and another could add 10, for a change in 20) but I realized this was inconsistent with existing interactions (or lack thereof) between Property Changes.
=> Add Relative Offset Property Change

WeakAurasOptions/AuthorOptions.lua
Correctly displays intended fallback name when using a noninteractive display type.
Uses fallback name when name field is an empty string, in Author Mode _only_.
Removes inconsistency between default names and fallback names.
Fixes #1847
=> Custom Options Author Names Tweaks

.pkgmeta-classic, WeakAuras/GenericTrigger.lua, WeakAuras/embeds.xml
Work around GetSpellCount returning 0 for all spells since last classic update
copy/pasta from https://github.com/tullamods/Dominos/blob/master/Dominos/bars/getActionReagentUses.lua adapted to use localized spell name instead of spell ids
Fixes #1849
ps: it's highly possible a lib doing this will be release
=> classic: workaround GetSpellCount change in 1.13.03 #1849

.luacheckrc, .pkgmeta, .pkgmeta-classic, WeakAuras/ArchiveTypes/Repository.lua, WeakAuras/History.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAuras/embeds.xml, WeakAurasArchive/WeakAurasArchive.lua, WeakAurasArchive/WeakAurasArchive.toc
This adds a new external to WeakAuras, which I have been writing on and off for a little while - see https://github.com/emptyrivers/Archivist.
The basic idea here is that for the data we don’t need instantly on every login (so, history data), we can shunt that data into a LoadOnDemand addon to avoid having to load it every time. Since some users have a large volume of data (I’ve seen upwards of 30 MB in extreme cases), I decided to create a utility to maintain this archived data in a compressed format (hence the Archivist project).
This also creates a convenient location for authors to store saved data, without risking the same kind of SV bloat that history data created.
=> Add WeakAurasArchive

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
Perhaps will make custom sort functions a bit easier to manage. To use, write something like this in custom sort:
```lua
WeakAuras.CompareRegionData({"region", "state", "expirationTime"})
```
Seriously, that's it. There isn't even any need to wrap it in a `function(a, b) ... end`, though of course you can do so. In which case I would recommend caching the function that you get from CompareRegionData into `aura_env`, and then calling it yourself on the last line.
If you want to compare more than one value in the regionData object, you can compose them:
```lua
WeakAuras.ComposeSorts(
WeakAuras.CompareRegionData({"region", "state", "expirationTime"}),
WeakAuras.CompareRegionData({"region", "state", "index"})
)
```
By default, `CompareRegionData` will use the `<` operator to compare values. …
=> add ComposeSorts and CompareRegionData helpers

WeakAuras/GenericTrigger.lua
somehow this particular function wasn't being called in protected mode
presumably just an oversight.
Fixes #1942
=> swallow stacksfunc errors

WeakAuras/Types.lua
Just added the Raid Mark textures to Types. They're very useful and I was surprised at their current exclusion.
- [• ] New feature (non-breaking change which adds functionality)
Such a simple addition. Just made a few Texture and Progress Textures to see that it worked okay. Couldn't test on Classic as I don't have an account but AFAIK the texture paths are the same.
=> Add raid mark textures

WeakAuras/RegionTypes/AuraBar.lua
Reset the orientation flag in modify, so that we always set the new
layout.
Fixes: #1986
=> AuraBar: Fix modify not modyfying the layout

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
Talents points on classic doesn't use same events as in retail, fixed some places where the event is use.
(reported on discord)
Wiped talents, made aura with load condition for a specific talent point, added point.
Was not working, now fixed
=> classic: fix event for character points changed

WeakAuras/Types.lua
https://www.wowhead.com/item=168973/neural-synapse-enhancer&bonus=4777
=> Make Cooldown Progress (Equipment slot) able to use Mainhand and Offhand on retail.

WeakAuras/Types.lua, WeakAurasOptions/AuthorOptions.lua
I don't know if this is actually worth doing, but it was pretty easy to implement.
Basically, allow separators to force a break in merging, as well as visually. So if you have two complex sections in separate auras, not in a group, you can add a breaking separator to the top of each set of options, and WeakAuras will not attempt to merge them and possibly create a huge mess.
To see the difference:
https://wago.io/x4D57HonC (without separators)
https://wago.io/SZeDvSABI (with separators)
=> Allow separators to force a "page break" in custom options

WeakAuras/GenericTrigger.lua
Allows to add custom text tooltips via TSU. In my case I have a progress bar that counts players and want to display the player list on mouseover, which does not work using the currently available tooltip options.
=> Added option to supply pure text tooltips

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Saw a gif on Discord of someone using a translate animation (https://cdn.discordapp.com/attachments/218087027042811905/694561955016343573/Rogue_WA_Slide.gif from user <Holte#6934>) on Start and Finish, and felt that straight translates _really_ need a little easing to not look horrible. After some playing with arithmetic myself I saw that Blizz has some simple easing functions already. I chose what I feel is a good balance between subtle enough easing while still applying to noticeable effect. 
Example with Easing applied: https://i.imgur.com/zaz6Lip.gifv
Only tested on Retail but the EasingUtil exists in Classic files too (<https://github.com/tomrus88/BlizzardInterfaceCode/blob/classic/Interface/SharedXML/EasingUtil.lua>) and the addition is …
=> Eased translate animations

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua
Use LibGetFrame's FRAME_UNIT_UPDATE callback for automatic re-anchor with anchor on Unit Frames
- For single auras/clones => Fixes #2051 
- For dynamic groups => replaced previous method that was re-sorting everything, this should improve performance a lot
Use WeakAuras.GetUnitNameplate for all anchors to nameplates => this will do a regression for people using nameplate addons.
- ~~Handle region.state.unit's guid changed.~~
- Maybe move region.unitframe_monitor cleaning out of WeakAuras.PerformActions
- More testing.
=> [WIP] Auto re-anchor unitframes & slightly different anchors for nameplates addons

WeakAuras/SubRegionTypes/SubText.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasExpandSmall.lua, WeakAurasOptions/RegionOptions/Icon.lua, WeakAurasOptions/SubRegionOptions/Glow.lua, WeakAurasOptions/SubRegionOptions/SubText.lua, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasOptions/WeakAurasOptions.toc
Some Auras may block each other because the subtext is too long.
So I transplanted the Auto Width and Word Warp options in the text display to the subtext.
Create Subtext in aura and modify text and automatic width, width, and word warp
=> Add Text's Automatic Width and Word Warp for Subtext

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AnimationOptions.lua
A more thorough approach to adding some easing to animations. An Ease Type and Ease Strength setting is added to Start, Main and Finish custom animations.  Type being "In", "Out" and "InOut", and Strength being how aggressively the easing effect is applied. 
Easing code is from Blizz functions, https://github.com/tomrus88/BlizzardInterfaceCode/blob/46d53f88664c14d16a702c0f68c1cd215d9efd14/Interface/SharedXML/EasingUtil.lua#L3 - not sure what acknowledgements are needed. 
This would supersede my previous PR with a couple of specific Eased functions. Can that one be easily unmerged or is it not that simple? 
Tested on Retail.
=> Universal animation easing

WeakAuras/Types.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua
An argument could be made that it should always have been "Name Plate" but within the addon it's already "Nameplate" so I couldn't help but bump on the space every time I saw it. 
Barely at all, but only strings changed.
=> Triggered by the space

WeakAuras/Profiling.lua, WeakAuras/WeakAuras.lua
Provides several improvements to profiling:
- Largest time spent in a single debugprofilestop session
- Less empty space in profiling report
- Ability to profile the next instance of combat or encounter
- Save Real Time Profiling Window location between sessions
- Adds combat and encounter buttons to Real Time Profiling Window 
~~Experimental change:~~
~~- Most amount of time spent in a rolling x second window, configurable~~
=> Profiling Improvements

WeakAuras/Prototypes.lua
fixes #2145
The function `HasFullControl()` exists on classic and i found it work with Polymorph, but not with Ice Nova, Gouge, Sap, ... So not reliable enough to keep it on classic.
=> disable trigger "Crowd Controlled" for classic

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua
- anchor to hidden frame when can't find a unitframe
- handle new LibGetFrame Callback: FRAME_UNIT_REMOVED
Dynamic group anchoring to an invisible when GetFrame return nil fix an issue where the region is not registered in WeakAuras.dyngroup_unitframe_monitor for future FRAME_UNIT_UPDATE callback
FRAME_UNIT_REMOVED fix an issue with auras on "player" raid frame still showing after quitting a group
This change was made to LibGetFrame https://github.com/mrbuds/LibGetFrame/commit/33fd99afba2ab7a2e56ebc44e3e135c261af9cf8
Fixes #2051
=> DG anchored to Unit Frames: fix #2051

WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/AnimationOptions.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/GenericTrigger.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/SubRegionOptions/SubText.lua, WeakAurasOptions/WeakAurasOptions.lua
After making https://github.com/WeakAuras/WeakAuras2/wiki/Custom-Code-Blocks the next step is to update the in-game links to that page. 
The goal is that any code block in game provides access to direct and specific information on how that code block should be used. What, if anything, is sent in to the code block, and what the user is expected to do or return from it. 
The content created in the linked wiki page doesn't need to be final. I hope that the entries there will be edited and refined over time. But the in-game links provides such a good opportunity for giving precise and direct info about what the user might be struggling with that I think this is really worth doing. And the previous links were often just the closest thing that already happened to exist. 
Please delete options …
=> Update wiki links to new Custom Code Blocks page

WeakAuras/Init.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/SubRegionTypes/SubText.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/DefaultOptions.lua, WeakAurasOptions/WeakAurasOptions.toc
Adds a manual overwrite for the default font and font size until proper options are built
=> Add a way to overwrite default font and font size

WeakAurasOptions/OptionsFrames/TextEditor.lua
The Settings button was added after the error text but the right side anchor wasn't updated.
=> Fix anchor

WeakAuras/Transmission.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
Auras are exported with the field tocversion
On import the field tocbuild was checked instead, which is never set
=> on import, fix handling of aura's tocversion

.luacheckrc, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/SubRegionTypes/Tick.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAurasOptions/SubRegionOptions/Tick.lua, WeakAurasOptions/WeakAurasOptions.toc
Adds a simplistic Tick SubRegion (or Sub Element) to Aura Bar type auras. Feature allows for progress values (optionally in percentage form).
Fixes #1656
=> Tick SubRegion

WeakAuras/GenericTrigger.lua
This fix weapon enchant name pattern not working as expected with weapon enchant that have charge. It also fix some cases where `shortenedName` wasn't shortened as expected.
Tested in game on retail with a fishing pole and shiny bauble.
Tested on lua 5.1 with those cases:
* `Instant Poison IV (30 min) (70 charges)` ➔ Capture `Instant Poison IV` and `Instant Poison`
* `Windfury 4 (5 min)` ➔ Capture `Windfury 4` and `Windfury`
* `Crippling Poison (30 min)` ➔ Capture `Crippling Poison` and `Crippling Poison`
* `Sharpened +2 (30 min)` ➔ Capture `Sharpened +2` and `Sharpened`
* `(20 damage per second)` ➔ Doesn't match
=> Fix weapon enchant name pattern

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
…e more informations
If unit is not "At Least One Enemy"
- use UNIT_THREAT_LIST_UPDATE instead of UNIT_THREAT_SITUATION_UPDATE
- use UnitDetailedThreatSituation instead of UnitThreatSituation
- %threatpct, %rawthreatpct and %threatvalue can be use
- duration function use threatpct
=> Threat Situation trigger rework and enable it for WoW 1.13.5

WeakAuras/Prototypes.lua
- Add an exact spell option for "Queued Spell", this fixes an issue where the trigger won't work after learning a new rank
- Fix division per 0 in Threat Situation trigger
=> Fixes for Queued Spell and Threat Situation triggers

.pkgmeta, .pkgmeta-classic, WeakAuras/ArchiveTypes/Repository.lua, WeakAuras/History.lua, WeakAuras/Transmission.lua, WeakAuras/embeds.xml
We have a new option for serializing arbitrary data, thanks to @rossnichols. From experiments, it looks to be about a 20-25% reduction in the final size of the exported string, which is good enough imo to warrant adoption.
Since this change is not forwards-compatible, it warrants a minor version upgrade to `2.18`, I think. And once it's been released, we should advise people to ensure that they are up to date.
Build artifact will fail to load properly in game, until [this](https://github.com/rossnichols/LibSerialize/pull/1) change is complete.
as always, I was lazy and haven't done any thorough testing beyond the initial experiments.
=> Add LibSerialize

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua
Set the wrap mode on all the textures in the TexturePicker window so they don't repeat at the edges
Textures in the picker that don't have a >0px zero alpha border will repeat their edges. This looks unsightly but more importantly makes it difficult to discern the actual shape of the texture. Changing the wrap mode in the picker solves that. This change doesn't intend to do anything about how textures are used once selected. 
- [*] New feature (non-breaking change which adds functionality)
=> Tiny change to tidy up the texture picker

WeakAuras/RegionTypes/Icon.lua
A user in discord reported that icon auras with a static progress type didn't display the CD widget. Upon investigation, it was never implemented. It currently simply hides the widget if the progress type is static. This PR would make the CD widget work as expected, showing a static CD widget set to the given progress values.
=> Make CD Widget functional when using a static progress type on an icon aura.

WeakAurasOptions/CommonOptions.lua, WeakAurasOptions/SubRegionOptions/Border.lua
Because otherwise we risk a division by 0 error in the backdrop mixin
=> Set an absolute minimum to border size of 1

WeakAurasOptions/TriggerOptions.lua
When multiple triggers are present they are shown within the same page. Accidentally clicking the "delete" button immediately removes the trigger with no way to undo. This change introduces a confirmation popup for this action to avoid accidental deletion.
Fixes #2350
=> Add a confirmation popup when deleting trigger

WeakAurasOptions/OptionsFrames/FrameChooser.lua
could not repro this issue, but reporter likely has aura(s) connected to a nameplate
Fixes #2348 (probably)
=> clear all points on frameChooserBox first

.github/workflows/pull_request.yml, .pkgmeta, .pkgmeta-classic, WeakAuras/RegionTypes/Model.lua, WeakAuras/SubRegionTypes/BarModel.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAurasModelPaths/ModelPathsClassic.lua, WeakAurasModelPaths/WeakAurasModelPaths.toc, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/Model.lua, WeakAurasOptions/SubRegionOptions/BarModel.lua, WeakAurasOptions/WeakAurasOptions.toc
After seeing WeakAuras was forked on a chinese forum with models support https://bbs.nga.cn/read.php?tid=22060034&rand=116, my tests show that wrong models does not crash the game anymore.
I use the same ModelPaths.lua found on nga.cn forum for classic
=> re-enable model region for classic

WeakAuras/Prototypes.lua
It doesn't come up super often but it is a display that people occasionally want to make in WA. It also provides a way to trigger based on player level or rested amount, which people might want to use to set activation on Auras displaying other things. 
=> add player xp trigger

.gitignore, WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua
When options are open, this anchor to the fake PRD auras and dynamic groups anchored to nameplates for which the trigger does not return an existing nameplate
- With aura anchored to nameplate
- With a dynamic group with group by frame => nameplate
=> Fake nameplate anchor fixes  #1896

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/SubRegionTypes/Tick.lua
My approach was flawed. It worked in testing because I only tested one tick at a time. This adds a new event notifier for all aurabar type regions and utilizes it to properly update ticks.
=> Fix ticks not updating properly on size changes.

WeakAuras/RegionTypes/Icon.lua
Users with old versions of omnicc can't use WeakAuras anymore
```
2x WeakAuras\RegionTypes\Icon.lua:361: attempt to index field 'Cooldown' (a nil value)
WeakAuras\RegionTypes\Icon.lua:361: in function `modify'
WeakAuras\WeakAuras-3.0.3.lua:2863: in function `SetRegion'
WeakAuras\WeakAuras.lua:2758: in function <WeakAuras\WeakAuras.lua:2664>
WeakAuras\WeakAuras.lua:2793: in function `Add'
WeakAuras\WeakAuras.lua:2324: in function `load'
WeakAuras\WeakAuras.lua:2331: in function `AddMany'
WeakAuras\WeakAuras.lua:1010: in function <WeakAuras\WeakAuras.lua:982>
WeakAuras\WeakAuras-3.0.3.lua:1132: in function <WeakAuras\WeakAuras.lua:1083>
```
This make the addon more resilient for those who have not updated yet
=> Fix error with old versions of OmniCC

WeakAuras/Prototypes.lua
I get this warning with Status / Character Stats / Haste (%) trigger.
=> Fix leaked global in Character Stats trigger

WeakAuras/BuffTrigger2.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/BuffTrigger2.lua
Add MAINTANK and MAINASSIST filter instead of UnitGroupRolesAssigned filters for classic
- bufftrigger2
- various status triggers
- Load condition
fixes #2635
=> Classic: add support for MAINTANK and MAINASSIST filter

WeakAuras/RegionTypes/Text.lua, WeakAurasOptions/RegionOptions/Text.lua
Aura and Icon can both display tooltips on mouseover in certain situations.  Add the same feature to Text.
I am trying to create "data text" WeakAuras like the old [SLDataText](https://www.wowinterface.com/downloads/info8539-SLDataText.html).  These are Texts displaying basic information, sometimes with additional information in a tooltip on mouseover.  For example, the "ping" text shows one value returned from `GetNetStats`.  When mousing over the displayed value, all of the values returned from `GetNetStats` are displayed in a tooltip.
The [TSU docs](https://github.com/WeakAuras/WeakAuras2/wiki/Trigger-State-Updater-(TSU)#tooltips) make it seem like they would be an appropriate way to accomplish this by stating: "TSU triggers have the 'Tooltip on Mouseover' option available by default …
=> Add "Tooltip on Mouseover" support to Text

.luacheckrc, WeakAuras/WeakAuras.lua
Adding support for Plater personal resource frame anchoring.
Fixes https://github.com/Tercioo/Plater-Nameplates/issues/71
=> Adding support for Plater personal resource bar anchoring

WeakAuras/GenericTrigger.lua, WeakAuras/Legendaries.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.toc, WeakAurasOptions/WeakAurasOptions.toc
Changes the following:
* Adds state variables and conditions for bonus id, item id, item name,
icon, and item slot.
* Adds toggle to use Legendary icon instead of item icon. Fallbacks to
item icon.
* Adds option to check for bonus id on specific slot.
* Moves Legendaries.lua from WeakAurasOptions to WeakAuras.
Fixes #(2775)
All trigger, display tab, and condition options were tested on a level 60 with a legendary on retail WoW.
=> Improve Bonus Id trigger.

WeakAurasOptions/OptionsFrames/TextEditor.lua
Adds a menu to the Settings dropdown in the Editor to allow changing the number of tab spaces. 4 is a bit big when people are used to 2, and with Lua indenting so much. 
=> add tab space setting

WeakAuras/Types.lua
With the removal of old modernization data, the old format of talent load data was throwing errors when imported.
This issue was reported twice on discord.
See https://pastebin.com/4J88N5Mb for error.
See https://wago.io/E1ac3_Z9z for aura that when imported, causes issues.
These errors prevent WA from functioning in its entirety.
It's possible that this isn't the only change necessary, but this is the only occurrence I've seen and I've seen it twice thus far.
=> Add talent table to data stub.

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
remove "emphasize" option from "BigWigs Timer" trigger
https://github.com/BigWigsMods/BigWigs/commit/75c0c592a8d514cfcbd70489e63b9c00acb79aea replaced Emphasize by a Countdown option
BW authors added compatibility code but suggest us to remove the feature
=> remove "emphasize" option from "BigWigs Timer" trigger

WeakAuras/GenericTrigger.lua
Allows TSU tooltips to optionally use filters via `unitBuffFilter` and
`unitDebuffFilter` state variables.
Adds an additional tooltip option for UnitAura with the same Index and
Filter options via `unitAuraIndex` and `unitAuraFilter` state variables.
I particularly noticed this limitation when attempting to display proper tooltips for my stacking Torghast powers.
=> Add filters and UnitAura options to TSU tooltips.

WeakAuras/Legendaries.lua, WeakAuras/Prototypes.lua
Adds an inverse option to the Item Bonus Id trigger. Will show Legendary Power Name and Icon if the option is selected (now renamed to cover both the icon and the fallback name).
=> Bonus Id Trigger fixes and inverse option.

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Allows the Bonus Id trigger to work in Classic again. I don't remember doing this originally, but it's fixed now. In addition, prevented the Legendary setting from displaying in Classic.
Fixes bonus IDs on multiple items when using the Item Slot setting.
=> Bonus Id Fixes

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
New Overlay Latency option for Cast trigger using delay between CURRENT_SPELL_CAST_CHANGED and UNIT_SPELLCAST_START events
This is the method use by popular cast bar addon Quartz.
expected:
- stop casting a self heal before progress reach latency overlay = no heal
- stop casting a self heal after progress reach latency overlay and before full progress = heal
results: seems good :)
I don't like the hack in GenericTrigger.lua to make RunTriggerFunc not return false because of `statesParameter = "unit"` require an arg1, but i have not found a better way to do it
=> Cast trigger: add latency overlay

WeakAuras/Transmission.lua
This is a fix for the issue submitted in #2943, it simply changes the following check:
```lua
if type(target) ~= nil then
```
to:
```lua
if type(target) ~= 'nil' then
```
Fixes #2943
I ran the reproduction steps listed in #2943:
1. Add a print statement at the end of the Import function, or at the place where .Import is being called logging the status and message.
2. Open the aura import popup
3. Enter a valid import string
4. ~See the import info popup appear and a message in the chat frame with false "Invalid update target. Importing as an unknown payload."~
and confirmed that step 4 is no longer the case and the function properly returns `true, ""` if the import was successful.
=> Fix target type check to compare against a string

.luacheckrc, WeakAuras/BuffTrigger2.lua, WeakAuras/Conditions.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Modernize.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/SubRegionTypes/SubText.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/BuffTrigger2.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasTemplates/TriggerTemplatesData.lua
By making the dynamic threshold configurable.
And by using Blizzard's time formatting functions, as proposed by
Elvador in #2173. This patch offers basically the same functionality,
though quite differently presented to the user.
There's now a top-level option to choose between:
* Built-in:            63:42   3:07    10    2.4
* Old Blizzard         2h      3m 7s   10s   2.4
* Modern Blizzard      1h 3m   3m 7s   10s   2.4
All formats support (and default to) increased precision below a
threshold. The default threshold remains at 3s.
The threshold setting is also the off-switch for the additional
precision. Setting it to 0, disables that behaviour. This isn't the most
obvious user interface, but creating a special control for it is too
much work and a additional checkbox destroys the …
=> Make Time Formats more flexible

WeakAuras/Modernize.lua
After updating from 3.1.9-28-g99622d5 to 3.1.9-37-g62029a4 I noticed that my auras that used to show remaining time with one decimal now show it with no decimals.
https://github.com/WeakAuras/WeakAuras2/commit/4ea2b0024cd67cb1c05db728f97e935a5f66a7d0 (+ fix in https://github.com/WeakAuras/WeakAuras2/commit/62029a44722018a5c48cb36dec1178d366cd7b87) refactors time formatting to introduce new formatting options. However the Modernize step incorrectly disables decimals for time texts that have dynamic precision disable. Also, time texts that have decimals disabled but had dynamic previously enabled and still set to true in their data now show one decimal below 3 seconds.
Decimals for times higher than 3 seconds were achieved with `_time_dynamic = false`, showing selected precision for values …
=> Fix Modernize for time format with non-dynamic decimal precision

WeakAuras/Prototypes.lua
Use spellName instead of spellId to get icon id for classic
Fixes  #2959
=> fix combat log trigger's icon for classic

.luacheckrc, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/RegionTypes/stopmotion.lua, WeakAuras/SubRegionTypes/Tick.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
As I don't think we have a way to pause a timed aura, this will handle DBM_TimerPause like a DBM_TimerStop event, and DBM_TimerResume like a DBM_TimerStart event
and same for BigWigs_PauseBar and BigWigs_ResumeBar events
fixes #2951
I have not tested the change since it seems dbm will only fire them for a mythic boss i won't do
=> handle DBM & BW pause/resume callbacks

WeakAuras/Types.lua
Enable ranged swing timer for TBC. Add new TBC spell ranks and Steady Shot for swing timer resets. Add warrior/rogue ranged shots to reset melee swing timer.
Testing swing timer speeds with a warrior character on Shattrath dummies in WoW TBC Beta client.
=> TBC/Classic Swing timer fixes

WeakAuras/Transmission.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasOptions/WeakAurasOptions.toc
Add a WeakAuras.StashShow function that WeakAurasCompanion can use when there are auras pushed from Wago with weakauras-companion://wago/push/<wagoID>
- get last companion build (current https://github.com/WeakAuras/WeakAuras-Companion/suites/2521299971/artifacts/54607460)
- go to https://wago.io/d3cV99LwL
- ctrl+shift+k on firefox to open dev console and type/run `enableCompanion = true`
- press button "SEND TO WEAKAURA COMPANION APP"
- unfinished UI show in companion
- /reload in game
- make less ugly UI
- make less ugly UI
=> Add WeakAuras Import UI

.pkgmeta, .pkgmeta-bc, .pkgmeta-classic
I'm about to merge some incompatible changes to archivist, and I don't want to accidentally break the alpha builds until i've actually done the fixes for WeakAuras.
This will be reverted in a future patch.
=> lock archivist version

WeakAuras/GenericTrigger.lua
Fixes #3077
Aura linked in #3077 show timer for both melee and ranged on wanding, both wand timer & melee timer is correct
=> some spell reset both ranged & melee weapon timer

WeakAuras/Transmission.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingInstallButton.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua, WeakAurasOptions/WeakAurasOptions.toc
Add a section on top with all auras that can be updated called "Ready for Update"
The buttons for this section are not directly linked to target's aura, if there is multiple target you can choose with right click menu which aura to update.
A goal of this PR is to regroup all update functions to the top of the UI, to achieve this **all wago update related options are removed from normal auras buttons and right click menu**.
Ignoring/un-ignoring aura updates was set per aura, this pr completely remove the ability to do that in WeakAuras UI, Companion app and its clones can implement it on their side
=> Add Ready for Update section + fixes to Install section

WeakAuras/AuraEnvironment.lua
Timosh pointed this out recently - loadstring accepts a string as a second parameter, which will then be set as the name of the loaded chunk. This way we don't need to do a weird comment injection in order for custom code error messages to be identifiable.
=> set chunk name on loadstring instead of injecting a comment

WeakAuras/Transmission.lua
This make it easier to have correct position for urlEditBox for all locales
=> Import tooltip: remove "Source:"

.pkgmeta, .pkgmeta-bcc, .pkgmeta-classic
it wasn't updated on all .pkgmeta* and is currently raising a Lua error on BCC since last commit
=> use weakauras fork of LibRangeCheck-2.0 for all versions

WeakAurasOptions/LoadOptions.lua
=> fix CorrectSpellName for linked spells on TBC

WeakAuras/Transmission.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/CommonOptions.lua, WeakAurasOptions/ExternalAddons.lua, WeakAurasOptions/LoadOptions.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/WeakAurasOptions.lua
Moves the `SortDisplayButtons` from the public `WeakAuras` to the private table.
=> Move SortDisplayButtons to private namespace

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua
Fix load condition for dungeons on bcc, they use new index as seen in https://wow.tools/dbc/?dbc=difficulty&build=2.5.1.38988#page=1 thanks @raethkcj for pointing it
And re-add difficulty load condition to be able to distinguish between normal & heroic dungeons
=> Dungeons/Raids load condition BCC fix

WeakAuras/WeakAuras.lua
This changes the existing (#2614) behavior for the personal resource display detection when Plater is enabled but default blizzard personal resource display is used. The check is no longer performed against existing `unitFrame.Plater`, but against the "is the Plater unitFrame acutally on screen" indicator with `unitFrame.PlaterOnScreen` instead.
=> Fixing personal resource display anchor for disabled Plater personal bar module

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingInstallButton.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasPendingUpdateButton.lua
In rare situations it's possible for some of the data provided by the companion update to be invalid. In the usual scenario, this is a result of an old aura missing modern data used to display the thumbnail. This change validates and modernizes the data before attempting to use it.
Fixes an issue from Discord by Dradux.
First I imported an older version of an aura, where the most recent version is missing modern data:
https://wago.io/AggramarTechnique/0.0.4
Note the missing `barColor` and `orientation` fields necessary for aurabars to display their thumbnail.
Second I closed the game and loaded up the companion for updates.
Third I opened up the game again, logged in, and then opened WA Options. (You may need to Expand the Ready for Updates …
=> Validate Companion Data before showing it to the user as a potential update.

WeakAuras/GenericTrigger.lua
Fixes #3178
- Tested in TBC client, avoided classic only function "IsPlayerAttacking" and used events to track attack status instead
=> Prevent swingtimer from triggering when not in attacking state

WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/SubRegionOptions/Glow.lua
Quick addition. It was noticed on Discord that glow settings throughout the addon don't use hasAlpha, though the glow lib allows for it. 
=> Add alpha option for glows throughout settings

WeakAuras/Prototypes.lua
Fixes the Weapon Enchant trigger's name field. Appears to have been a copy-paste mistake.
Fixes #3242
=> Fix Weapon Enchant Trigger name state value.

WeakAuras/BuffTrigger2.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/BuffTrigger2.lua
This PR add an options to generic triggers and aura trigger with unit = party / raid / smart group to for including pets, or show only pets
Fixes #3111
=> change party/raid/group units to include pets support

WeakAuras/Prototypes.lua
reflect changes made by blizzard with build 2.5.1.38453
Don't merge yet, waiting for information from adam to know if it's intended
=> bcc: update encounter ids tooltip

WeakAuras/WeakAuras.lua
noninteractive options dont have keys, so we shouldn't assume that they always do
Fixes #3377
=> check that option key exists before writing

WeakAuras/Prototypes.lua
temporary fix for 2.5.3 UnitCastingInfo & UnitChannelInfo changes, spellid was moved to 9th arg (same as mainline/classic_era)
use them also for classic_era
=> UnitCastingInfo & UnitChannelInfo update

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
this option is supported since
https://github.com/DeadlyBossMods/DBM-Unified/commit/407e3ba5156409b5fe6becce35d0662014bb2d1a
Renamed previous "Stage" option to "Current Stage"
Called new option "Stage Total", i don't know if "Total Stage" is better or not.
=> DBM Stage Trigger: new "stage total" option

.luacheckrc, WeakAuras/WeakAuras.lua
Looks like Blizz made some changes since first implementation. The table that was being checked for volume and rate no longer exists so were always falling back to default values no matter what the user was setting in their interface. 
=> reflect Blizz changes to TTS volume and rate

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Add raid marker filter to Unit Characteristics, Health, Power, Alternate Power and Cast triggers
Fixes #3293
Review WeakAuras.WatchUnitChange
Only solo on target & nameplates
- filter works
- condition works
- %raidMark and %raidMarkIndex text replacements works
=> Raid Marker filter

WeakAuras/Prototypes.lua
The "incoming heal" API was added back in to Classic at some point so those checks for retail only can be removed. 
=> Remove the retail check on all incoming heal settings

WeakAuras/Modernize.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/Icon.lua, WeakAuras/RegionTypes/Model.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/RegionTypes/StopMotion.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/RegionTypes/Texture.lua, WeakAuras/WeakAuras.lua
fixes #3423
I could not find a way to reproduce exact same issue with icons & aurabar, but with this group <https://wago.io/ClassicBudsUI> all the 3 texts auras had 2 subbackground.
This PR bump internalVersion and replace the 2 last migrations
For both new subregions it check previous data, add them if they are missing and remove duplicates.
Tested with <https://wago.io/ClassicBudsUI> and bugged aura from #3423, their data are correct with the migration.
=> sanitize foreground/background subregions

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Looks like not all events with a UnitID as 1st arg start with `UNIT_`
List made from <https://wowpedia.fandom.com/wiki/Events> and some filters <https://docs.google.com/spreadsheets/d/1f6R0cwTaK_SO0IykWW-lhN4KQi_6AU-4mKkaGUBS3Bw/edit?usp=sharing>
=> Allow unitId filtering on various events, fixes #3432

WeakAuras/RegionTypes/AuraBar.lua, WeakAurasTemplates/TriggerTemplates.lua
rename aurabar_bar subregion before trying to add subforeground
=> fix bad order of aurabar foreground when importing old version, #3449

WeakAuras/Prototypes.lua
UnitCastingInfo & UnitChannelInfo are synced with retail now on tcc
=> fix cast trigger for tbc 2.5.3 #3448

WeakAuras/Conditions.lua, WeakAuras/Prototypes.lua
this should fix performance issues with the cooldown trigger with "Insufficient Resources" and "Spell Usable" conditions
add support for filtering in custom checks too
does not support multi units (group, nameplate, ...)
**This will break existing custom checks conditions using ":" as separator**
=> make condition events use RegisterUnitEvent when possible

WeakAuras/Types.lua
Update lists of spells resetting and not resetting swing timer.
Previous behavior:
- Drinking a swing-resetting potion would not cause swing timer to reset.
- Starting a cast of slam would pause the swing timer.
New behavior:
- Drinking a swing-resetting potion causes swing timer to reset.
- Starting a cast of slam does not pause swing timer.
Testing with a basic swing timer (https://wago.io/VF0rkqXwQ) and two handed sword in TBC Classic.
All basic non-zone specific potions/drinks have been tested. Leaves out Nethergon Vapor/Cenarion Healing Salve, but they should work the same.
Slam change is easily tested by starting a cast of slam mid-swing and then cancelling the slam-cast before it lands. The swing timer should be unaffected by this.
=> Fix swing timer resets and pauses

WeakAuras/RegionTypes/StopMotion.lua, WeakAurasOptions/CommonOptions.lua, WeakAurasOptions/RegionOptions/StopMotion.lua
With current options you need to have frames (width * cols) and (height * rows) to be a power of 2, this change let you use whatever individual frame size you want, only image size have to be a power of 2.
example image:  [monkeys.zip](https://github.com/WeakAuras/WeakAuras2/files/8053168/monkeys.zip)
this work with these settings:
```
cols: 5,
rows: 4,
frameCount: 19,
fileWidth: 1024,
fileHeight: 1024,
frameWidth: 186,
frameHeight: 249
```
- add a toggle?
- add background support
- tests
=> [WIP] StopMotion: support more flexible frame size

WeakAuras/Types.lua
Add the missing slam rank 5 to the list of spells that reset swing in BCC.
Players using rank 5 slam would not have their swing timer reset when slam is cast, because the list of slam IDs for BCC is missing slam rank 5.
I have advised people to fix Weakauras2 this way with success, so it is indirectly tested. 
You can verify the spell ID here:
https://tbc.wowhead.com/spell=25241/slam
=> Add slam rank 5 to spells resetting swing

WeakAuras/GenericTrigger.lua
Provides 2 improvements to swing timer when an attack is parried.
1. Account for multiple parries during the same swing timer.
2. Correct the amount the swing timer is progressed after a parry.
I noticed that any time an attack is parried while my swing timer is sitting between 20 and 60 percent, my next auto attack would occur before the swing timer completes. This happens because the current code only progresses the swing timer by an additional 20% when it should a varying amount. The correct logic is as follows:
_When a swing timer has more than 20% time remaining, a parried attack will progress the swing timer by an additional 40% or such an amount so that the swing timer has 20% time remaining, whichever is less._
I also noticed that the `timeLeft` variable was sometimes incorrect …
=> fix parry logic in swing timer

WeakAurasOptions/ConditionOptions.lua
Indenting for the 2nd line was wrong when using "All of" / "Any of"
=> Rangecheck condition: fix indenting

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua
Bring the change of 4d8a85e to right click. Currently right clicking on big group, freeze the game and trigger a script ran too long error. Still a quick solution for the problem of editing options of 1000+ auras, in the long term, I think the user should be asked if they really want to edit more than 1000 auras.
=> Make right click open group tab by defaut

WeakAurasOptions/AuthorOptions.lua
Aura-Groups containing an "Array"-type option group were not editable properly from the Aura-Groups "Custom Options" section. To recreate do the following:
- Create a new group
- Create 2 or more children
- Navigate into the groups (top-level aura) `Custom Options`-Section in Author-Mode
- Add a `Option Group` with the `Group Type` of `Array`
- Create at least one sub option that can be used as the `Entry Name Source` (for example `String`)
- Select some `Entry Name Source` for the `Option Group`
The following issues occur:
- In Author-Mode the `Entry Name Source` will always remain on `Entry Order` despite all auras within the group being updated properly
- In User-Mode all entries will be named as `Entry 1`, `Entry 2` etc. and not by the selected `Entry Name Source` as it is when …
=> Fixed issue with "Array"-type options in aura groups

WeakAuras/BuffTrigger2.lua, WeakAuras/GenericTrigger.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/GenericTrigger.lua, WeakAurasOptions/Locales/enUS.lua
When triggers are added catch the format "TRIGGER:#" where `#` is a trigger number and flag those triggers. On trigger updates, check for the flag and send a ScanEvents into the custom trigger that requested them, along with that trigger's allstates
This needs thorough testing but I wanted to get opinions (and some more people trying to find ways to break it)
=> Add a framework for built in trigger updates to fire into custom triggers

WeakAuras/RegionTypes/RegionPrototype.lua
Spot an error with `needToClear` initialised as `true` in place of `false` making the if unconsequential.
Also remove `needToClear` variable and put the `texture:SetTexture(nil)` directly inside the if as the assignation of  `wrapModeH` and `wrapModeV` to `texture` can occure after the `texture:SetTexture(nil)` making `needToClear` unnecessary.
The error seem to come from the following commit, when the function has been moved from ProgressTexture.lua to RegionPrototype.lua:
https://github.com/hexaheart/WeakAuras2/commit/a9ef1ff9c2a81d32f078c17c89bebd324b9d281d#diff-1b4576ed275670b486caa9bee1dc9c714518abe2f0017a5be16da9479b3a1f17L704
For the checklist:
I did not make any comment as the changes are quite modest.
I don't think the changes imply a documentation change.
Not sure what kind of …
=> Fix an error on SetTextureOrAtlas behavior

WeakAurasOptions/OptionsFrames/TextEditor.lua
Edited to incorporate feedback.
Adds a dropdown menue in the "Settings" button, allowing for the font size in the code editor to change. Starting from the default 12, up to 24, increasing by 2 each time.
There are no additional dependencies added. 
I did this because I asked a question in the Discord channel and was advised to open an issue requesting the feature. I started playing around with a group sorting function last night as I didn't find what I wanted. I found that I had a lot of fun making it. Today I wasn't particularly busy and decided to try my hand at actually implementing it as I've never contributed to an open source project before. 
I appreciate any feedback, I've probably made some mistakes as this is my first time.
Here is a preview:
Fixes #3742
I have tested this out …
=> Adds font size setting for code editor

WeakAuras/GenericTrigger.lua
Simply passes the `elapsed` value from OnUpdate through to the trigger if it uses the FRAME_UPDATE event. Just to provide another throttling option other than using GetTime()
=> Add elapsed to FRAME_UPDATE

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Combat log triggers have a raidFlags value that doesn't directly translate to a raidTargetIndex, meaning custom text functions would be needed for someone to show source/dest raid markers on a combat log trigger.  This PR provides and index value as well as a formatted "{rt}" text replacement. 
=> Add raid marks as a text replacement on combat log triggers

WeakAuras/Prototypes.lua
Fix incorrect label after https://github.com/WeakAuras/WeakAuras2/commit/978ca3403e6edf0d6b9c948fc54b014ba32149d5
Revert change https://github.com/WeakAuras/WeakAuras2/commit/a340e303013fcb5b06b1a6c873b9ae35664e44fe in the wrong place
=> Fix "Spec Role" load condition label on Retail again

WeakAurasOptions/AuthorOptions.lua
if author did not provide a softMax then we should use max as the softMax instead.
indeed, this is what is done further down the procedure, where if max is also nil then we fallback to 100.
Fixes #3834
=> don't use 20 as a fallback

.luacheckrc, WeakAuras/RegionTypes/Icon.lua
This change allow ElvUI Cooldown module to replace icon cooldowns handled by default Blizzard code or OmniCC.
Feature is enabled by default for all ElvUI users as Cooldown module is enabled by default. It can be controlled by normal WA options (_Hide Timer Text_) or in ElvUI options panel. Where users also can find options to change style of the CD.
As requested code execute extensive nil checks.
At the moment code need to be tested with `development` branch of ElvUI. But changes required will be merged and released soon. If somebody is using incompatible version of ElvUI code fail graciously.
ElvUI CD module operate only on text part of the cooldown frame so other elements like swipe are unaffected.
As requested following functions were tested:
- cooldown:SetReverse 
- …
=> Added support for ElvUI Cooldown module

WeakAuras/Types_Retail.lua
At the time this is written, on retail it show both shadowlands & dragonflight data, and on DF's beta it show dragonflight dungeons and season 1 dungeons
retail:
beta:
=> Zone Id tooltip: show dungeon/raid tiers from current to last one

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
Currently it is not possible to select a border for a dynamic group if Grow "custom" is selected ( https://i.imgur.com/5leQgy1.png )
Borders set up well to the region if the grow is accuracy centralized
This will work for most cases, and it won't matter if someone uses a custom border binding.
Tested on Retail WeakAuras 5.0.5 version. ( https://i.imgur.com/qujg6ml.png )
=> Enable border settings for custom grow in Dynamic Group

WeakAuras/Prototypes.lua
Historically this was disabled because classic didn't have the `C_LossOfControl` API, but with wrath launch it was added to both the wrath classic and vanilla classic clients.
=> Spell Cooldown: enable LOC option for classic

WeakAuras/Prototypes.lua
Added PLAYER_SPECIALIZATION_CHANGED event so this trigger is updated when the player changes their spec.
Example: Add icon to display feral druid's Adaptive Swarm cooldown, and set a trigger to only show this icon when that talent is learned. Change to guardian spec. Logout, login. Change back to feral spec.
Before this commit, the icon would not show unless I opened /wa, now it shows up directly after changing the spec.
See description above for before and after this commit.
=> Update "Talent Known" trigger on spec changes

WeakAuras/GenericTrigger.lua
The original code short circuits when it finds the first relevant power value, however this is not correct in certain scenarios. Using Holy Priest as an example, Flash Heal will return the Discipline Priest cost, as it is the first value found. I'm not sure why Blizzard's API works this way, but this is incorrectly showing 0.
To be precise, this problem shows up when attempting to cast Flash Heal or Smite as a Holy Priest with a progress bar with a default power trigger tracking mana and Overlay Cost of Casts enabled (export below).
I tested this with plenty of priest and shaman abilities (including the Maelstrom spender Elemental Blast)
```
!WA:2!1vvtpoXrtyp4iqyjqGtckRekIGcBGOaHSkWB(asWJxBSjl2MXdWses29mDBpDy80T6UN1R3le8HO9SpNdr(CozXpa0(lOL17pGOvr5hWEprP6ESwhqS(Gvvvxv31hp1Z4uT4GI4I4D)8Psos …
```
=> Fix power cost of abilities that change with certain auras.

.luacheckrc, .luarc.json, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasExpand.lua
The update dialog can sometimes set one of these widgets to have GameFontHighlight instead, which is smaller and if that widget is reused elsewhere it looks wrong
=> reset font object on acquire

WeakAuras/Modernize.lua, WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
from some (very) rough testing, this can in some cases cut time spent managing dynamic groups by upwards of  90%
tested this by hitting a dummy on a character with [this](https://wago.io/LuxthosMageDragonflight) installed. On both profiles, I (tried) to perform the same actions as much as possible.
on current main branch, a ~1 minute profile looks like this. Notice the dynamicgroup system time, and also that `Core - LWA - Mage` (a dynamic group which almost never does any significant relayouting) tops aura time.
```
Total time: 65069.13ms 
Time inside WA: 1774.47ms (10.22ms)
Time spent inside WA: 2.73%
Note: Not every aspect of each aura can be tracked.
You can ask on our discord https://discord.gg/weakauras for help interpreting this output. …
```
=> only run sort/grow when interesting state changes happen

.luacheckrc, WeakAuras/Init.lua, WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/RegionTypes/ProgressTexture.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/RegionTypes/StopMotion.lua, WeakAuras/RegionTypes/Text.lua, WeakAuras/SubRegionTypes/SubText.lua, WeakAuras/SubRegionTypes/Tick.lua, WeakAuras/SubscribableObject.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAuras/WeakAuras_TBC.toc, WeakAuras/WeakAuras_Vanilla.toc, WeakAuras/WeakAuras_Wrath.toc, WeakAurasOptions/AuthorOptions.lua
=> add media custom option

WeakAuras/SubscribableObject.lua
tIndexOF unfortunately returns nil if nothing is found, which causes tRemove to incorrectly remove the last element. So, do a quick nil check first.
Fixes #4238
=> be more careful about removing subscribers

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Fixes #4214
For each test: created a Progress Bar Aura with a Player/Unit Info - Power Trigger, with Overlay Cost of Casts checked.
=> Add support for queued spell costs

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasMiniTalent_Dragonflight.lua
Current state talent selector will replace the talent nodes' icon and tooltips with those of the talent that overrides them. Two examples:
1. Enhancement Shaman: If Elemental Blast and Lava Burst are both talented, Lava Burst's node in the class talent tree will be replaced by Elemental Blast (icon and tooltip), which is misleading.
2. Guardian Druid: If Raze is talented, Maul's node at the top of the spec tree will be replaced with Raze.
This update causes the talent icons to use the 8th return value from `GetSpellInfo`, `originalIcon`, to populate the button itself.  It also sets the `dontOverride` flag when using `GameTooltip:SetSpellByID` so that the original spell's tooltip is provided instead of the override.
Note that this fix is mildly incomplete, because even with `dontOverride` …
=> Improve talent selector for overridden spells

WeakAuras/GenericTrigger.lua
The cooldown check change is derived from tests done in https://github.com/WeakAuras/WeakAuras2/pull/4304 but keep it simple.
I have not seen any issue from this change in a few days for this trigger, but that's something i'd like to highlight to alpha users in #wow-addon to keep on eye on if/when this is merged.
For item quality, regarding @InfusOnWoW comment https://github.com/WeakAuras/WeakAuras2/issues/4116#issuecomment-1398806345
- a quality filter was not added as items with different quality does not have same itemid and i think it's a good enough way to filter quality without doing breaking changes.
- text replacement way was chosen, but a condition was added regardless
Trigger was converted to use `statesParameter = "one"` so it can have more fields in the state, the value & …
=> Reduce load of cooldown trigger

WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/InformationOptions.lua, WeakAurasOptions/WeakAurasOptions.lua
This pullrequest is supposed to add an option to the dropdownlist to be able to Unignore (and ignore) wago options for auras. Code is probably pretty suboptimal so please roast me to make things better thank you.
Having 2 popup dialogs that basically do exactly the same except having different texts should be changed but i wasn't sure how to handle this best.
Tried ignoring and unignoring updates which updated the auras fine in the SavedVariables.
Will prob need a change alongside in companion but i didn't doublecheck with buds https://github.com/WeakAuras/WeakAuras-Companion/issues/1543
=> add unignoring uption for WagoUpdates

WeakAuras/BossMods.lua
=> Bossmod Timer fix

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/Types.lua, WeakAurasOptions/RegionOptions/DynamicGroup.lua
This PR adds a new angle-based constant factor for circular dynamic group grow styles. It is similar to the existing circular growers Clockwise and Counter Clockwise, but with a few key differences. With this new constant factor:
- Spacing is constant, and is determined by a combination of the user-defined radius and angle.
- Auras fill the group sequentially from one end to the other, essentially being placed as points along that curve in order.
The motivation for this new style was a request from a friend - they were trying to use the existing circular grow styles to build a new UI that was based on circles using Masque and some custom textures, but they couldn't get some of their aura groups to fit and grow the way they wanted. My initial solution for them was to write a custom grow …
=> Add new angle-based constant factor for circular dynamic group grow styles

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua, WeakAuras/Types.lua
Classic Wrath's API for CurrencyInfo is not the same as on Retail. 
On Classic Era, currencies don't exist.
=> Currency Trigger: support classic wrath, disable on classic era

WeakAuras/Prototypes.lua
=> Currency trigger: don't specify test on value block

WeakAuras/Types.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasTextureButton.lua, WeakAurasOptions/OptionsFrames/TexturePicker.lua, WeakAurasOptions/RegionOptions/StopMotion.lua
Includes the following changes:
- Add new flipbooks and fix some others where the data was incorrect
- Make the flipbook display proportional in the texture picker
- Set region size to match the flipbook tile size when selecting a texture
- Fix StopMotion thumbnail
=> Update flipbooks for StopMotion

WeakAurasOptions/OptionsFrames/TexturePicker.lua
It fixes texture search in the texture picker.
Many atlas names may contain characters that have special meaning when used in patterns. For example, `!Barbershop-MiddleTile`. If you type `shop-M` into the search field, nothing will show up in the texture picker. Therefore, it's better to use the find function with pattern matching disabled
=> Fix texture search in the texture picker

.luacheckrc, WeakAuras/AuraWarnings.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasDisplayButton.lua, WeakAurasOptions/OptionsFrames/Update.lua, WeakAurasOptions/WeakAurasOptions.lua
This allow display buttons to have a list of status icons
Loaded icon and Warning icons are moved to this list
Groups shows an icon per unique status icon of each leaf
This solve a few ux issues:
- warning icon could show only one warning, now it can show multiple warning on same button
- warnings were not spread to parent group(s), user had to expand them
- with nested groups this help identify which ones have auras with different loaded status
https://github.com/WeakAuras/WeakAuras2/assets/189656/02894413-7f6e-44de-bdab-e9d364ebe07e
=> Add status icon system for display buttons

.github/workflows/build-beta.yml, .github/workflows/build.yml, .github/workflows/pull_request.yml
=> fetch all history on build

WeakAuras/Profiling.lua
I'm sorry; this is the first time I'm attempting a pull request. Please don't hate me. I'm not sure if I'm doing it correctly.
Color the spike based on the value as follows:
0 to 2: [Green gradient to yellow]
2 to 3: [Orange to red]
3 and above: [Red]
In game I guess with pprint
=> Coloring Spike for Profiling

WeakAuras/AuraWarnings.lua
This PR aims to ensure that Aura Warning titles are properly capitalized and localized. If there's an error it should fall back to showing what is already being shown today (all lowercase, non-localized severity "enum") 
I didn't 😅
=> Localize the title in AuraWarnings

WeakAuras/AnchorToWeakAuras.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/OptionsFrames/MoverSizer.lua
or rather, re-do the hardening, but in a slightly different way to before If PreAdd errors during AddMany, then that data & all descendants will not hydrate from the database & the user is asked to contact us for further help
Also, fix the data repair tool by taking a snapshot *before* PreAdd is called.
=> harden WeakAuras against bad migrations

WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
Adds support for Parent Zone IDs in the Player Location load option.
Parent Zone IDs must be prefixed with 'p'.
E.g. if you want it to load in all child maps of "Dragon Isles" : 'p1978'.
The child maps are gathered recursively meaning it would also load in childs of childs of childs.
E.g. 'p1978' makes it load in Dragon Isles > Thaldraszus > Valdrakken.
The Parent Zone is added to the tooltip, and I've added newlines to the bottomText for better readability.
=> Player Location: Parent Zone support

WeakAuras/GenericTrigger.lua
Trigger boolean types stored in the state are needed to make the option available for conditions, however this also shows them as an available text replacement. When a trigger features many of these boolean options, the text replacements tooltip becomes cluttered with options that are probably never used as output.
Before:
After:
`%capped, %isParagon, %isWeeklyRenownCapped` are removed from the tooltip, though they are still available.
=> Hide boolean types in text replacements tooltips

WeakAuras/BossMods.lua
DBM timers can call `:UpdateIcon` which will replace the default icon state from when a timer is started. This fires the `DBM_TimerUpdateIcon` event, and any WeakAuras that have listened to what the icon is should update the icon to reflect these changes.
The `DBM_TimerUpdateIcon` is newly implemented in <https://github.com/DeadlyBossMods/DeadlyBossMods/commit/5e75945aa704cf157d9e4ad198610cce26fee8c9>
=> Add DBM_TimerUpdateIcon event listener

WeakAurasOptions/ConditionOptions.lua
especially useful if WA is skinned by e.g. elvui, which causes the toggle to almost vanish when switched off
Before:
After:
=> add a label to bool property changes

.github/scripts/generate_twitter_post.py, .github/scripts/test_files/large_changelog_example.md, .github/workflows/release_notifications.yml, .github/workflows/release_notifications_manual_tests.yml, .github/workflows/release_notifications_setup.md
Add Github Actions to automatically post release notifications when a release is published to the following:
- Discord Webhook
- Twitter
- Mastodon
- Bluesky
Tested via my own personal fork of the code base, using GitHub Actions.  I provided a 'TEST' workflow as well that will use a custom made 'changelog' that has a large amount of changes to see what it looks like.  We can add other test files or change this one for future uses.  The test file also uses separate GitHub 'secrets', so that they don't interfere with the production channels.
I still need to test twitter once more, I think there was a daily rate limit on the free tier, so  I need to wait a day to test it again.
I will also go through and add extra comments some of files I created.  Please let me know if there is anything in …
=> Add GitHub Actions workflows for Release Notifications

WeakAuras/Types.lua
Unknown difficulty ID warnings coming from the latest WoW patch. This is a simple change to add them to `Types.lua`.
- Fixes https://github.com/WeakAuras/WeakAuras2/issues/4986
Tested locally.
=> Add missing difficulty IDs from latest WoW patch

WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua
Frame glow currently supports selecting a frame, but managing those values becomes cumbersome real quick. I have a WA that is set to be attached to an action button, and conditionally adds a glow to that action button. I also have a condition to hide the glow but not actually hide the WA. I've noticed that when I want to move my spells to another keybind I find myself having to go through all the tabs and replace the configured frame name, which is a lot of work and easy to make mistakes. It also makes sharing the WA a lot more effort as I have to instruct them what exactly needs to be changed on multiple tabs.
The summary of this change is that it adds a "Parent Frame" option to the "Glow Frame Type" options under "Conditions" , and the "On Show/Hide" options under "Actions".
- New …
=> Added "Parent Frame" as option to "Glow Frame Type"

WeakAuras/Transmission.lua
UnitIsSameServer returns true if user is on a connected realm (e.g. US ArgentDawn <=> TheScryers), so we should distinguish between the cases using UnitRealmRelationship, which returns 1 for same realm, 2 for coalesced (instanced/sharded together or whatever), and 3 for connected realms.
Since it seems that either whisper comms on connected realms never worked (and ~nobody plays on those realms so it took a long time to notice), or blizzard recently broke it, we simply fallback to trying raid/party. If that doesn't work, we already have a hint to the user to try grouping up.
Fixes #5018 (possibly)
=> only use whisper comms if target is on the actually same server

.github/pr-commenter.yml, .github/workflows/pull_request.yml
try opening a pull request (any kind!) over on my [fork](https://github.com/emptyrivers/WeakAuras2/pulls), or see emptyrivers/WeakAuras2#12 for an example.
Will only post links for pull requests with the feature preview label.
=> advertise a link to an experimental build, if one exists

WeakAuras/RegionTypes/DynamicGroup.lua, WeakAuras/RegionTypes/RegionPrototype.lua, WeakAuras/WeakAuras.lua
This is actually 2 problems in one:
- On initial spinup, our PRD anchor doesn't have a valid rect for 1 frame which would be fine, except we're creating it in the same frame we're anchoring dynamic groups to it. Thus, the dynamic group's children also won't have a valid rect. Fix this by forcing an early draw of the PRD anchor via an explicit GetSize call. (see https://warcraft.wiki.gg/wiki/API_ScriptRegion_IsRectValid for more details)
- After initial spinup, our PRD anchor is anchored to NamePlate1 (or something that's attached to it, depending on user's addons). Unfortunately for us, Blizzard in their extremely finite wisdom decided to make NamePlate1 a restricted region. Thus, calls to GetRect & friends on any frame in its anchor family will error. This went unnoticed because we …
=> ensure we always compute the correct rect for a dynamic group

WeakAuras/RegionTypes/AuraBar.lua, WeakAuras/Types.lua, WeakAurasOptions/AceGUI-Widgets/WeakAurasStatusbarAtlasWidget.lua, WeakAurasOptions/RegionOptions/AuraBar.lua, WeakAurasOptions/WeakAurasOptions.toc, WeakAurasOptions/WeakAurasOptions_Cata.toc, WeakAurasOptions/WeakAurasOptions_Vanilla.toc, WeakAurasOptions/WeakAurasOptions_Wrath.toc
classic sod and cataclysm:
dragonflight:
An other possibility is to not add these aliases to LSM dropdown, and in the Texture Picker widget make a curated list of usable textures, but i don't like to add a list to maintain manually, and i don't believe average user explore the texture picker much (as i don't see much users take advantage of the model subregion)
- WeakAurasStatusbarAtlasWidget.lua is almost a 1:1 copy of LSM30_Statusbar widget, only difference is the Atlas test for using SetAtlas in 2 places
- Funkeh raised concern on discord about mixing 2 types in the values, but we do that already with Private.SetTextureOrAtlas
- The texture picker option make auraBar intersect some functionalities with progressTexture, bonus is i think users naturally go to auraBar when they want a …
=> AuraBar: add some alias textures, and option to use texture picker

WeakAuras/RegionTypes/DynamicGroup.lua
otherwise the group gets 'stuck' on UIParent(CENTER) if it ever collapses due to 0 active children
Also, prevent all of this behavior during IsOptionsOpen, to avoid any potential edges case with the moversizer
Fixes #5065
=> always ReAnchor() if isRestricted, not just if numVisible > 0

WeakAurasOptions/AuthorOptions.lua
we already updated parentOption.nameSource when clicking up/down on the name source option, but that's not the only way to change the index of the name source. notably, moving an adjacent child option up or down can do can also move the name source, effectively usurping it. if the "new" name source isn't actually a valid name source (e.g. it's a toggle option), then WeakAuras correctly barfs on the garbage data.
Fixes #5074
=> be more careful about keeping nameSource accurate

.github/pr-commenter.yml, .github/workflows/pull_request.yml
slightly less spammy this way; the bot will only comment once, and then edit that comment as new builds become available.
since this makes it not as obvious when the nightly link changes, i added a timestamp to the comment.
=> add build date to pr comment & edit isntead of recreate

WeakAuras/Compatibility.lua, WeakAuras/Types.lua
Ensures we collect all player factions regardlesss of display settings.
`ExpandAllFactionHeaders()` does not correctly expand all faction headers. If subheaders are present it would remove all factions under the subheader which gives us an incomplete list. This PR fixes that by expanding headers individually.
=> Reputation trigger fixes

WeakAuras/WeakAuras.lua
nothing that we put into dynFrame threads is meant for in-combat execution anyways, so to avoid random unexpectedly short timeouts, pause execution if combat starts, and resume after combat ends.
There's potential for WeakAuras to be 'broken' during that combat session (due to dynamic groups being Pause()'d), but we probably couldn't have unbroken it given that ResumeAllDynamicGroups is too costly to call during combat lockdown without risking a timeout.
Fixes #4967 (or at least, reduces its likelihood)
=> hide dynFrame if combat starts with living threads

.luacheckrc, WeakAurasOptions/OptionsFrames/TextEditor.lua
This is a lighter version of https://github.com/WeakAuras/WeakAuras2/pull/4983 without the features i'm not happy with (for the reasons told in [this comment](https://github.com/WeakAuras/WeakAuras2/pull/4983#issuecomment-2153275292))
This does not include WeakAuras's API automatically generated + added to game's api documentation
This does not include a "intellisense" widget
=> TextEditor: add "Search API" side panel

WeakAuras/AuraEnvironment.lua, WeakAuras/Types.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAuras/WeakAuras_Cata.toc, WeakAuras/WeakAuras_Vanilla.toc
Add support for https://github.com/Jodsderechte/LibCustomNames
I think Jods addon needs a few reviews from addon authors before merging this to be sure interface isn't going to need too much changes
=> LibCustomNames support

WeakAuras/GenericTrigger.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasInput.lua, WeakAurasOptions/AceGUI-Widgets/AceGUIWidget-WeakAurasMultiLineEditBox.lua, WeakAurasOptions/ActionOptions.lua, WeakAurasOptions/ConditionOptions.lua, WeakAurasOptions/OptionsFrames/OptionsFrame.lua, WeakAurasOptions/RegionOptions/Text.lua, WeakAurasOptions/SubRegionOptions/SubText.lua
Automatically hide the window when input loses focus.
This PR also adds custom variables from TSU that have no display value to the list of available text replacements. In the case of no display value it falls back to the var's name
=> Auto-hide dynamic text window

.luacheckrc, WeakAuras/WeakAuras.lua
`GetAdditionalProperties()` should now collect all props from child auras if a group or multiple auras are selected.
conveniently also fixes #5272  :)
=> Dynamic Text: add props from child and multiselect auras.

WeakAurasTemplates/TriggerTemplatesData.lua
- Incorrect mount form id was changed in shadowlands
- balance druid missing moonkin form option
The correct trigger is made
Testing this has unveiled one issue (#5310 ), which i will also document - the form list does not update after spec change, only after reloading ui
=> Fix incorrect mount form id and add balance druid premade forms

WeakAurasTemplates/TriggerTemplatesData.lua
Add and update balance druid template spells
=> Druid template

WeakAuras/WeakAuras.lua
A few minutes ago, we had a user [on discord](https://discord.com/channels/172440238717665280/1273328571338854461) confused about where the error in an aura was actually happening. I spent a few seconds blinking in confusion myself, before remembering that the top line of the error message we send to bugsack isn't actually the start of the stack trace. So, why not identify things more clearly?
=> add a line to custom code errors to identify the stack trace

.github/pr-commenter.yml, .github/workflows/pull_request.yml, WeakAuras/WeakAuras.lua, WeakAurasOptions/Cache.lua, WeakAurasOptions/OptionsFrames/Update.lua, WeakAurasOptions/WeakAurasOptions.lua
the times selected are completely arbitrary. The primary reason for this is to make WA liable to defer Resume() until the next frame, if AddMany() takes a decent chunk of time (usually due to migrations).
A user who's really determined can still defeat this strategy by importing so many auras that Resume() itself takes > 19 seconds to execute, but there's very little we can do about that anyways.
Closes #5172 (not by fixing it, but by making it less likely)
=> reserve time for each action in login thread

WeakAuras/AuraEnvironment.lua, WeakAurasOptions/OptionsFrames/TextEditor.lua
Admittedly, it's a *really* small hole - a potential victim would need to open the text editor in order for a WA to escape the sandbox this way.
=> close a hole in the sandbox

WeakAuras/Prototypes.lua, WeakAuras/RegionTypes/RegionPrototype.lua
The progress settings for Set Minimum Progress and Set Maximum Progress have a special validation and parsing function which is too basic and quite broken.
Current implementation of the parser is the regex `"(%d+)%%"` - digits followed by a literal %, first such match in the string.
- `-12%` parsed as 12
- `12.34%` parsed as 34
- `12.34 %` not parsed
- `abcd 12% efgh` parsed as 12
- `12%34` parsed as 12
~~Find and replace first instance of a literal `%` with space (See 5th example for why not empty string). The rest of the work is offloaded to tonumber (which trims leading and trailing whitespace)~~
Find the `%` at the end of the string with regex `"%% *$"`. If it is found, the parsing is offloaded to tonumber on the substring before the find.
- `-12%` parsed as -12
- `12.34%` parsed as …
=> Fix percent progress validation and parsing

WeakAuras/WeakAuras.lua
turns out we were cleaning archive on almost every login, oops.
Also, reduce the frequency to once every 30 days, so that 28/29 days a user logs in there is a high chance that the addon never loads, and thus wow only rarely writes to the file. This should make it more likely that if the main addon SavedVariables are destroyed by e.g. user running out of disk space, the archive survives intact.
=> fix archive clean schedule

WeakAurasOptions/OptionsFrames/Update.lua
i've been meaning to try this for a while, i can't really tell if it improves anything or not
=> try moving history updates to background task

WeakAuras/Prototypes.lua, WeakAuras/Types.lua, WeakAurasOptions/LoadOptions.lua
Two changes made here:
- The latest Cataclysm patch made specialization indices start at 1, matching retail. This change undoes the offset needed previously.
- Specializations were previously sorted by ID. In Classic this appears rather messy. Instead this sorts (visually only) them alphabetically in class (using table.sort on the class file name) and then the specializations by index, which should match the talent pane. A small change was made to the Load Options to allow for this.
Here are some pictures:
- Original bug: 
- Unsorted order after fixing the bug in Classic: 
- Sorted order after these changes:
=> Specialization changes

WeakAurasOptions/OptionsFrames/Update.lua
the problem was actually that `type(ignoredForDiffChecking) == table` always evals as false, because type(...) returns a string value and table is the std table library! Whoopsie :)
Fixes #5520
=> fix recurseDiff ignore algorithm

WeakAuras/Types.lua
Added the following textures under `Blizzard Alerts`:
- Arcane Soul
- Hyperthermia
Fixes #5521
Open textures menu and navigate to bottom of `Blizzard Alerts` section. See both new mage spell alerts.
Select each and verify they appear on screen.
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
=> New Mage Spell Alerts

WeakAuras/BossMods.lua, WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
Primarily this ensures that we don't have any kind of reentrancy, which has the potential to break invariants.
=> defer calls to ScanEvents & friends if it doesn't come from WeakAuras

WeakAuras/Conditions.lua, WeakAuras/Modernize.lua, WeakAuras/Prototypes.lua, WeakAuras/WeakAuras.lua
very lightly tested, because i don't have a lot of guinea pigs around at this hour
=> upgrade Unit Characteristics trigger

WeakAuras/Prototypes.lua
inspired by [this post in discord](https://discord.com/channels/172440238717665280/1321645681580052554/1321645681580052554).
We could & maybe should add a shim for Ambiguate in our format options, but since the source GUID is, yknow, *right there* it seems silly to not make it available
=> add sourceGUID to chat msg trigger state

WeakAuras/GenericTrigger.lua, WeakAuras/WeakAuras.lua
I think we warned about CLEU causing issues for long enough
Revert https://github.com/WeakAuras/WeakAuras2/pull/9/commits/1f3888b10dabfe8d758e3dc3ee27977248427dc8
It was loading all "on init" scripts for auras with an encounterID load option when zoning in a raid
i tried a battery of tests, with on init script, ENCOUNTER_START event, and load options, everything is working fine, /reload doesn't break auras supposed to be loaded
```
!WA:2!nJ5AZTXvzCCRicnSPPe7KysstB1ycPYann20K0WqMbVYsnM6yzVs(s4M0E5iTNKv7U5S76BCRrekM7GGHcKj0bbm8Mqhgnmd3NPJFbV(ze8jWVOFa8xGYZ5C2v(AHoHYuEJ2Dp75SNNNN))E(VEDQ5giy0XjloqJbSgWATrAPZmNK4wp0(UdUHHhZIWu1nVLfZZ3)OQo0vxvNzLPSNNti1NTCXA1ciHx71D(D99s913byRepWNCX)XB(691xQo6UM2ESP9OUHg5Ypv58ATRf54KJYmDiv1c81njhKPBgs9CdUKwqOoluXOg1LgyROIhcvAgYO1RtybN(CS4tF52weJOA1kVIpHDT8toDHz …
```
=> Disable CLEU custom triggers without subevent filter, and don't pre-load on init in raid

WeakAuras/Prototypes.lua, WeakAuras/Types.lua
I'm not sure what makes more sense for players, finding this in the currency trigger or as its own trigger.
Adding it to the currency trigger also means I had to add additional checks and hide everything related to currencies when player money was selected. From a coding PoV, this is ugly, and I would prefer having Player Money as a seperate trigger.
Accepts a number:wowmoney
Has two options: 
- Gold format (big number with a "disable" option)
- Coin Precision
=> Add Money Formatting Option and Add Player Money to Currency Trigger

WeakAuras/GenericTrigger.lua, WeakAuras/Prototypes.lua
This PR adds the `Item in Range` conditional used by `Cooldown Progress (Item)` triggers to `Cooldown Progress (Slot)` triggers.
The motivation for the change is that many item slots in Classic for which you'd care about the cooldown can also have range limitations. Examples include:
- Goblin Rocket Helmet
- Gnomish Net-o-Matic Projector
- Tidal Charm
- (etc, there's so many)
Fixes #5638
I created a new WeakAura with a `Cooldown Progress (Slot)` trigger and used the added `Item in Range` conditional. I was able to verify its behavior for both the Helmet and Trinket 1 slots. Here is an export of that WeakAura:
```
!WA:2!DrvZUTTrqylRc4cv0wB1udK2CWWaniTOWiXaXaT3evOsCGSKkjDTtViTKCi5wtTlZUlLS8HceDkN1JGa6TEspc(jGqOOpa(qVx)e0zxr58Jbm183oZ33SZovAvFy9W6HV9rZPbCMlpxeapydXLDJIKGQYcs4VNlvq4jKl38Dku2MI …
```
=> Add itemInRange condition support to Equipment Slot triggers

WeakAuras/GenericTrigger.lua, WeakAuras/TSUHelpers.lua, WeakAuras/WeakAuras.lua, WeakAuras/WeakAuras.toc, WeakAuras/WeakAuras_Cata.toc, WeakAuras/WeakAuras_Vanilla.toc, WeakAurasOptions/OptionsFrames/TextEditor.lua
Add methods to the states/allstates table that helps with creating, updating or remove states in an optimized way
- If already created, update existing state, and return true if any value was changed, this can help reduce amount of resources an aura use
- Automatically add some fields: ~~`progressType`, `expirationTime`, `icon`,~~ `show`, `changed`
- Automatically `return true` when using these functions and any change was made
```Lua
function(states, event, ...)
if event == "PLAYER_TARGET_CHANGED" then
if UnitExists("target") then
-- if state exists it's updated, not replaced
-- show & changed fields can be skipped
states:Update("", {
name = UnitName("target"),
duration = 5,
expirationTime = GetTime() + 5,
progressType = "timed",
autoHide = true
})
else
-- wipe
states:RemoveAll()
end
end …
```
=> Allstates helper methods

.luacheckrc, WeakAuras/BossMods.lua, WeakAuras/Modernize.lua, WeakAuras/WeakAuras.lua
This make bigwigs, dbm (still active on classic), and bossmod triggers show timers regardless of bossmod bars settings
This is accomplished for BigWigs by using events `BigWigs_Timer` ~~and `BigWigs_CooldownTimer`~~ instead of `BigWigs_StartBar`
And for DBM by using `DBM_TimerBegin` instead of `DBM_TimerStart`
A new option allows to filter depending on the state of the bar in bossmod settings
Change in DBM: https://github.com/DeadlyBossMods/DeadlyBossMods/commit/3bf425b87a9b2196d8206f523e0202741e1e9b47
Change in BigWigs: https://github.com/BigWigsMods/BigWigs/commit/3d6a290bc2dab298b1992468bd370176db297e9a
Thanks @Justw8 and @MysticalOS
=> Bossmod triggers show timers regardless of bossmod settings

WeakAurasOptions/OptionsFrames/OptionsFrame.lua
Specifically the line would reach 130 characters before lineLength reached 130 characters, and that would cause automatic wrapping. This was because the comma and the period was not added to the line length.
Before: 
After:
=> Fix an issue with word wrapping in the Discord thanks list

WeakAuras/Types.lua
Adding Bleak Arrows (ID: 467718) to reset_ranged_swing_spells allows the generic Swing Timer triggers to properly function as Dark Ranger Hunter.
Create a Swing Timer WeakAura using the generic Player/Unit Info -> Swing Timer trigger.
- Before Commit:
Be a Hunter using Pack Leader. Begin attacking. Swing timer works as expected.
Be a Hunter using Dark Ranger with Bleak Arrows talent. Swing timer no longer functions.
- After Commit:
Generic Swing Timer trigger works as expected for both Pack Leader and Dark Ranger specializations.
I have tested this in LFR and at dummies as Beast Mastery.
=> Add Bleak Arrows to reset_ranged_swing_spells
